// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/accounting/accounting.proto

package accounting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DimensionKey represents different dimension types
type DimensionKeyEnum int32

const (
	DimensionKeyEnum_DIMENSION_KEY_UNSPECIFIED DimensionKeyEnum = 0
	DimensionKeyEnum_DIMENSION_KEY_DEPARTMENT  DimensionKeyEnum = 1
	DimensionKeyEnum_DIMENSION_KEY_PRODUCT     DimensionKeyEnum = 2
	DimensionKeyEnum_DIMENSION_KEY_PROJECT     DimensionKeyEnum = 3
	DimensionKeyEnum_DIMENSION_KEY_REGION      DimensionKeyEnum = 4
	DimensionKeyEnum_DIMENSION_KEY_COST_CENTER DimensionKeyEnum = 5
)

// Enum value maps for DimensionKeyEnum.
var (
	DimensionKeyEnum_name = map[int32]string{
		0: "DIMENSION_KEY_UNSPECIFIED",
		1: "DIMENSION_KEY_DEPARTMENT",
		2: "DIMENSION_KEY_PRODUCT",
		3: "DIMENSION_KEY_PROJECT",
		4: "DIMENSION_KEY_REGION",
		5: "DIMENSION_KEY_COST_CENTER",
	}
	DimensionKeyEnum_value = map[string]int32{
		"DIMENSION_KEY_UNSPECIFIED": 0,
		"DIMENSION_KEY_DEPARTMENT":  1,
		"DIMENSION_KEY_PRODUCT":     2,
		"DIMENSION_KEY_PROJECT":     3,
		"DIMENSION_KEY_REGION":      4,
		"DIMENSION_KEY_COST_CENTER": 5,
	}
)

func (x DimensionKeyEnum) Enum() *DimensionKeyEnum {
	p := new(DimensionKeyEnum)
	*p = x
	return p
}

func (x DimensionKeyEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DimensionKeyEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_accounting_proto_enumTypes[0].Descriptor()
}

func (DimensionKeyEnum) Type() protoreflect.EnumType {
	return &file_proto_accounting_accounting_proto_enumTypes[0]
}

func (x DimensionKeyEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DimensionKeyEnum.Descriptor instead.
func (DimensionKeyEnum) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{0}
}

// AccountType enum
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_ASSET       AccountType = 1
	AccountType_ACCOUNT_TYPE_LIABILITY   AccountType = 2
	AccountType_ACCOUNT_TYPE_EQUITY      AccountType = 3
	AccountType_ACCOUNT_TYPE_INCOME      AccountType = 4
	AccountType_ACCOUNT_TYPE_EXPENSE     AccountType = 5
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_ASSET",
		2: "ACCOUNT_TYPE_LIABILITY",
		3: "ACCOUNT_TYPE_EQUITY",
		4: "ACCOUNT_TYPE_INCOME",
		5: "ACCOUNT_TYPE_EXPENSE",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_ASSET":       1,
		"ACCOUNT_TYPE_LIABILITY":   2,
		"ACCOUNT_TYPE_EQUITY":      3,
		"ACCOUNT_TYPE_INCOME":      4,
		"ACCOUNT_TYPE_EXPENSE":     5,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_accounting_proto_enumTypes[1].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_proto_accounting_accounting_proto_enumTypes[1]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{1}
}

// EntryType enum
type EntryType int32

const (
	EntryType_ENTRY_TYPE_UNSPECIFIED EntryType = 0
	EntryType_ENTRY_TYPE_DEBIT       EntryType = 1
	EntryType_ENTRY_TYPE_CREDIT      EntryType = 2
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "ENTRY_TYPE_DEBIT",
		2: "ENTRY_TYPE_CREDIT",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED": 0,
		"ENTRY_TYPE_DEBIT":       1,
		"ENTRY_TYPE_CREDIT":      2,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_accounting_proto_enumTypes[2].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_proto_accounting_accounting_proto_enumTypes[2]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{2}
}

// TransactionStatus enum
type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	TransactionStatus_TRANSACTION_STATUS_PENDING     TransactionStatus = 1
	TransactionStatus_TRANSACTION_STATUS_POSTED      TransactionStatus = 2
	TransactionStatus_TRANSACTION_STATUS_REVERSED    TransactionStatus = 3
	TransactionStatus_TRANSACTION_STATUS_IN_BATCH    TransactionStatus = 4
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "TRANSACTION_STATUS_PENDING",
		2: "TRANSACTION_STATUS_POSTED",
		3: "TRANSACTION_STATUS_REVERSED",
		4: "TRANSACTION_STATUS_IN_BATCH",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"TRANSACTION_STATUS_PENDING":     1,
		"TRANSACTION_STATUS_POSTED":      2,
		"TRANSACTION_STATUS_REVERSED":    3,
		"TRANSACTION_STATUS_IN_BATCH":    4,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_accounting_proto_enumTypes[3].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_proto_accounting_accounting_proto_enumTypes[3]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{3}
}

// LedgerType enum
type LedgerType int32

const (
	LedgerType_LEDGER_TYPE_UNSPECIFIED LedgerType = 0
	LedgerType_LEDGER_TYPE_GL          LedgerType = 1
	LedgerType_LEDGER_TYPE_AR          LedgerType = 2
	LedgerType_LEDGER_TYPE_AP          LedgerType = 3
	LedgerType_LEDGER_TYPE_INV         LedgerType = 4
)

// Enum value maps for LedgerType.
var (
	LedgerType_name = map[int32]string{
		0: "LEDGER_TYPE_UNSPECIFIED",
		1: "LEDGER_TYPE_GL",
		2: "LEDGER_TYPE_AR",
		3: "LEDGER_TYPE_AP",
		4: "LEDGER_TYPE_INV",
	}
	LedgerType_value = map[string]int32{
		"LEDGER_TYPE_UNSPECIFIED": 0,
		"LEDGER_TYPE_GL":          1,
		"LEDGER_TYPE_AR":          2,
		"LEDGER_TYPE_AP":          3,
		"LEDGER_TYPE_INV":         4,
	}
)

func (x LedgerType) Enum() *LedgerType {
	p := new(LedgerType)
	*p = x
	return p
}

func (x LedgerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_accounting_proto_enumTypes[4].Descriptor()
}

func (LedgerType) Type() protoreflect.EnumType {
	return &file_proto_accounting_accounting_proto_enumTypes[4]
}

func (x LedgerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerType.Descriptor instead.
func (LedgerType) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{4}
}

// ReconciliationStatus enum
type ReconciliationStatus int32

const (
	ReconciliationStatus_RECONCILIATION_STATUS_UNSPECIFIED  ReconciliationStatus = 0
	ReconciliationStatus_RECONCILIATION_STATUS_UNRECONCILED ReconciliationStatus = 1
	ReconciliationStatus_RECONCILIATION_STATUS_RECONCILED   ReconciliationStatus = 2
	ReconciliationStatus_RECONCILIATION_STATUS_PARTIAL      ReconciliationStatus = 3
)

// Enum value maps for ReconciliationStatus.
var (
	ReconciliationStatus_name = map[int32]string{
		0: "RECONCILIATION_STATUS_UNSPECIFIED",
		1: "RECONCILIATION_STATUS_UNRECONCILED",
		2: "RECONCILIATION_STATUS_RECONCILED",
		3: "RECONCILIATION_STATUS_PARTIAL",
	}
	ReconciliationStatus_value = map[string]int32{
		"RECONCILIATION_STATUS_UNSPECIFIED":  0,
		"RECONCILIATION_STATUS_UNRECONCILED": 1,
		"RECONCILIATION_STATUS_RECONCILED":   2,
		"RECONCILIATION_STATUS_PARTIAL":      3,
	}
)

func (x ReconciliationStatus) Enum() *ReconciliationStatus {
	p := new(ReconciliationStatus)
	*p = x
	return p
}

func (x ReconciliationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReconciliationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_accounting_proto_enumTypes[5].Descriptor()
}

func (ReconciliationStatus) Type() protoreflect.EnumType {
	return &file_proto_accounting_accounting_proto_enumTypes[5]
}

func (x ReconciliationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReconciliationStatus.Descriptor instead.
func (ReconciliationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{5}
}

// ScheduleFrequency enum
type ScheduleFrequency int32

const (
	ScheduleFrequency_SCHEDULE_FREQUENCY_UNSPECIFIED ScheduleFrequency = 0
	ScheduleFrequency_SCHEDULE_FREQUENCY_MONTHLY     ScheduleFrequency = 1
	ScheduleFrequency_SCHEDULE_FREQUENCY_QUARTERLY   ScheduleFrequency = 2
	ScheduleFrequency_SCHEDULE_FREQUENCY_YEARLY      ScheduleFrequency = 3
)

// Enum value maps for ScheduleFrequency.
var (
	ScheduleFrequency_name = map[int32]string{
		0: "SCHEDULE_FREQUENCY_UNSPECIFIED",
		1: "SCHEDULE_FREQUENCY_MONTHLY",
		2: "SCHEDULE_FREQUENCY_QUARTERLY",
		3: "SCHEDULE_FREQUENCY_YEARLY",
	}
	ScheduleFrequency_value = map[string]int32{
		"SCHEDULE_FREQUENCY_UNSPECIFIED": 0,
		"SCHEDULE_FREQUENCY_MONTHLY":     1,
		"SCHEDULE_FREQUENCY_QUARTERLY":   2,
		"SCHEDULE_FREQUENCY_YEARLY":      3,
	}
)

func (x ScheduleFrequency) Enum() *ScheduleFrequency {
	p := new(ScheduleFrequency)
	*p = x
	return p
}

func (x ScheduleFrequency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleFrequency) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_accounting_proto_enumTypes[6].Descriptor()
}

func (ScheduleFrequency) Type() protoreflect.EnumType {
	return &file_proto_accounting_accounting_proto_enumTypes[6]
}

func (x ScheduleFrequency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleFrequency.Descriptor instead.
func (ScheduleFrequency) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{6}
}

// ReportingStandard enum
type ReportingStandard int32

const (
	ReportingStandard_REPORTING_STANDARD_UNSPECIFIED ReportingStandard = 0
	ReportingStandard_REPORTING_STANDARD_GAAP        ReportingStandard = 1
	ReportingStandard_REPORTING_STANDARD_IFRS        ReportingStandard = 2
)

// Enum value maps for ReportingStandard.
var (
	ReportingStandard_name = map[int32]string{
		0: "REPORTING_STANDARD_UNSPECIFIED",
		1: "REPORTING_STANDARD_GAAP",
		2: "REPORTING_STANDARD_IFRS",
	}
	ReportingStandard_value = map[string]int32{
		"REPORTING_STANDARD_UNSPECIFIED": 0,
		"REPORTING_STANDARD_GAAP":        1,
		"REPORTING_STANDARD_IFRS":        2,
	}
)

func (x ReportingStandard) Enum() *ReportingStandard {
	p := new(ReportingStandard)
	*p = x
	return p
}

func (x ReportingStandard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportingStandard) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_accounting_proto_enumTypes[7].Descriptor()
}

func (ReportingStandard) Type() protoreflect.EnumType {
	return &file_proto_accounting_accounting_proto_enumTypes[7]
}

func (x ReportingStandard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportingStandard.Descriptor instead.
func (ReportingStandard) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{7}
}

// Currency is an ISO-4217 code (e.g., "USD", "EGP")
type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_proto_accounting_accounting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accounting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Dimension is an arbitrary key/value tag for OLAP-style analytics
type Dimension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimension) Reset() {
	*x = Dimension{}
	mi := &file_proto_accounting_accounting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimension) ProtoMessage() {}

func (x *Dimension) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accounting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimension.ProtoReflect.Descriptor instead.
func (*Dimension) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{1}
}

func (x *Dimension) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Dimension) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Amount represents monetary values with multi-currency support
type Amount struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Value            int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Currency         string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	BaseValue        int64                  `protobuf:"varint,3,opt,name=base_value,json=baseValue,proto3" json:"base_value,omitempty"`
	BaseCurrency     string                 `protobuf:"bytes,4,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	ExchangeRate     float64                `protobuf:"fixed64,5,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	ExchangeRateDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=exchange_rate_date,json=exchangeRateDate,proto3" json:"exchange_rate_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_proto_accounting_accounting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accounting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{2}
}

func (x *Amount) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Amount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Amount) GetBaseValue() int64 {
	if x != nil {
		return x.BaseValue
	}
	return 0
}

func (x *Amount) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *Amount) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *Amount) GetExchangeRateDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExchangeRateDate
	}
	return nil
}

// Account is a node in a tree-structured Chart of Accounts
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type          AccountType            `protobuf:"varint,5,opt,name=type,proto3,enum=accounting.AccountType" json:"type,omitempty"`
	Dimensions    []*Dimension           `protobuf:"bytes,6,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClosedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_accounting_accounting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accounting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Account) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *Account) GetDimensions() []*Dimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

// Entry is a single debit or credit line
type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Type          EntryType              `protobuf:"varint,4,opt,name=type,proto3,enum=accounting.EntryType" json:"type,omitempty"`
	Amount        *Amount                `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Dimensions    []*Dimension           `protobuf:"bytes,6,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_accounting_accounting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accounting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{4}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Entry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Entry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *Entry) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Entry) GetDimensions() []*Dimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

// Transaction with bi-temporal coordinates
type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ValidTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=valid_time,json=validTime,proto3" json:"valid_time,omitempty"`
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	Status          TransactionStatus      `protobuf:"varint,5,opt,name=status,proto3,enum=accounting.TransactionStatus" json:"status,omitempty"`
	Entries         []*Entry               `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	SourceRef       string                 `protobuf:"bytes,7,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	UserId          string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_accounting_accounting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accounting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{5}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetValidTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTime
	}
	return nil
}

func (x *Transaction) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

func (x *Transaction) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *Transaction) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Transaction) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Period represents an accounting period
type Period struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	SoftClosedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=soft_closed_at,json=softClosedAt,proto3" json:"soft_closed_at,omitempty"`
	HardClosedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=hard_closed_at,json=hardClosedAt,proto3" json:"hard_closed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Period) Reset() {
	*x = Period{}
	mi := &file_proto_accounting_accounting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accounting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{6}
}

func (x *Period) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Period) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Period) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Period) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Period) GetSoftClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SoftClosedAt
	}
	return nil
}

func (x *Period) GetHardClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.HardClosedAt
	}
	return nil
}

// Ledger represents a ledger or sub-ledger
type Ledger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          LedgerType             `protobuf:"varint,3,opt,name=type,proto3,enum=accounting.LedgerType" json:"type,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ledger) Reset() {
	*x = Ledger{}
	mi := &file_proto_accounting_accounting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ledger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ledger) ProtoMessage() {}

func (x *Ledger) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accounting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ledger.ProtoReflect.Descriptor instead.
func (*Ledger) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{7}
}

func (x *Ledger) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ledger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ledger) GetType() LedgerType {
	if x != nil {
		return x.Type
	}
	return LedgerType_LEDGER_TYPE_UNSPECIFIED
}

func (x *Ledger) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Reconciliation tracks reconciliation of entries
type Reconciliation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalRef   string                 `protobuf:"bytes,2,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	EntryIds      []string               `protobuf:"bytes,3,rep,name=entry_ids,json=entryIds,proto3" json:"entry_ids,omitempty"`
	Status        ReconciliationStatus   `protobuf:"varint,4,opt,name=status,proto3,enum=accounting.ReconciliationStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reconciliation) Reset() {
	*x = Reconciliation{}
	mi := &file_proto_accounting_accounting_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reconciliation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reconciliation) ProtoMessage() {}

func (x *Reconciliation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accounting_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reconciliation.ProtoReflect.Descriptor instead.
func (*Reconciliation) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{8}
}

func (x *Reconciliation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reconciliation) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *Reconciliation) GetEntryIds() []string {
	if x != nil {
		return x.EntryIds
	}
	return nil
}

func (x *Reconciliation) GetStatus() ReconciliationStatus {
	if x != nil {
		return x.Status
	}
	return ReconciliationStatus_RECONCILIATION_STATUS_UNSPECIFIED
}

func (x *Reconciliation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Reconciliation) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// RecognitionSchedule for accrual/deferral
type RecognitionSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Frequency     ScheduleFrequency      `protobuf:"varint,3,opt,name=frequency,proto3,enum=accounting.ScheduleFrequency" json:"frequency,omitempty"`
	Occurrences   int32                  `protobuf:"varint,4,opt,name=occurrences,proto3" json:"occurrences,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognitionSchedule) Reset() {
	*x = RecognitionSchedule{}
	mi := &file_proto_accounting_accounting_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognitionSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognitionSchedule) ProtoMessage() {}

func (x *RecognitionSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accounting_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognitionSchedule.ProtoReflect.Descriptor instead.
func (*RecognitionSchedule) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{9}
}

func (x *RecognitionSchedule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecognitionSchedule) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RecognitionSchedule) GetFrequency() ScheduleFrequency {
	if x != nil {
		return x.Frequency
	}
	return ScheduleFrequency_SCHEDULE_FREQUENCY_UNSPECIFIED
}

func (x *RecognitionSchedule) GetOccurrences() int32 {
	if x != nil {
		return x.Occurrences
	}
	return 0
}

func (x *RecognitionSchedule) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *RecognitionSchedule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ReportingContext for compliance/reporting
type ReportingContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Standard      ReportingStandard      `protobuf:"varint,2,opt,name=standard,proto3,enum=accounting.ReportingStandard" json:"standard,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	PeriodId      string                 `protobuf:"bytes,4,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportingContext) Reset() {
	*x = ReportingContext{}
	mi := &file_proto_accounting_accounting_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportingContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportingContext) ProtoMessage() {}

func (x *ReportingContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accounting_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportingContext.ProtoReflect.Descriptor instead.
func (*ReportingContext) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{10}
}

func (x *ReportingContext) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReportingContext) GetStandard() ReportingStandard {
	if x != nil {
		return x.Standard
	}
	return ReportingStandard_REPORTING_STANDARD_UNSPECIFIED
}

func (x *ReportingContext) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ReportingContext) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

// JournalEvent is the atomic, append-only log record
type JournalEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventType       string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload         []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ValidTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=valid_time,json=validTime,proto3" json:"valid_time,omitempty"`
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	UserId          string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JournalEvent) Reset() {
	*x = JournalEvent{}
	mi := &file_proto_accounting_accounting_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEvent) ProtoMessage() {}

func (x *JournalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accounting_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEvent.ProtoReflect.Descriptor instead.
func (*JournalEvent) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accounting_proto_rawDescGZIP(), []int{11}
}

func (x *JournalEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JournalEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *JournalEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *JournalEvent) GetValidTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTime
	}
	return nil
}

func (x *JournalEvent) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

func (x *JournalEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_proto_accounting_accounting_proto protoreflect.FileDescriptor

const file_proto_accounting_accounting_proto_rawDesc = "" +
	"\n" +
	"!proto/accounting/accounting.proto\x12\n" +
	"accounting\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1e\n" +
	"\bCurrency\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"3\n" +
	"\tDimension\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xed\x01\n" +
	"\x06Amount\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"base_value\x18\x03 \x01(\x03R\tbaseValue\x12#\n" +
	"\rbase_currency\x18\x04 \x01(\tR\fbaseCurrency\x12#\n" +
	"\rexchange_rate\x18\x05 \x01(\x01R\fexchangeRate\x12H\n" +
	"\x12exchange_rate_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10exchangeRateDate\"\xd2\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12+\n" +
	"\x04type\x18\x05 \x01(\x0e2\x17.accounting.AccountTypeR\x04type\x125\n" +
	"\n" +
	"dimensions\x18\x06 \x03(\v2\x15.accounting.DimensionR\n" +
	"dimensions\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tclosed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\"\xeb\x01\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.accounting.EntryTypeR\x04type\x12*\n" +
	"\x06amount\x18\x05 \x01(\v2\x12.accounting.AmountR\x06amount\x125\n" +
	"\n" +
	"dimensions\x18\x06 \x03(\v2\x15.accounting.DimensionR\n" +
	"dimensions\"\xd3\x03\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"valid_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidTime\x12E\n" +
	"\x10transaction_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime\x125\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1d.accounting.TransactionStatusR\x06status\x12+\n" +
	"\aentries\x18\x06 \x03(\v2\x11.accounting.EntryR\aentries\x12\x1d\n" +
	"\n" +
	"source_ref\x18\a \x01(\tR\tsourceRef\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x90\x02\n" +
	"\x06Period\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12@\n" +
	"\x0esoft_closed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fsoftClosedAt\x12@\n" +
	"\x0ehard_closed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fhardClosedAt\"t\n" +
	"\x06Ledger\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.accounting.LedgerTypeR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\x94\x02\n" +
	"\x0eReconciliation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fexternal_ref\x18\x02 \x01(\tR\vexternalRef\x12\x1b\n" +
	"\tentry_ids\x18\x03 \x03(\tR\bentryIds\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2 .accounting.ReconciliationStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xa1\x02\n" +
	"\x13RecognitionSchedule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12;\n" +
	"\tfrequency\x18\x03 \x01(\x0e2\x1d.accounting.ScheduleFrequencyR\tfrequency\x12 \n" +
	"\voccurrences\x18\x04 \x01(\x05R\voccurrences\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x96\x01\n" +
	"\x10ReportingContext\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\bstandard\x18\x02 \x01(\x0e2\x1d.accounting.ReportingStandardR\bstandard\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1b\n" +
	"\tperiod_id\x18\x04 \x01(\tR\bperiodId\"\xf2\x01\n" +
	"\fJournalEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x129\n" +
	"\n" +
	"valid_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidTime\x12E\n" +
	"\x10transaction_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId*\xbe\x01\n" +
	"\x10DimensionKeyEnum\x12\x1d\n" +
	"\x19DIMENSION_KEY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DIMENSION_KEY_DEPARTMENT\x10\x01\x12\x19\n" +
	"\x15DIMENSION_KEY_PRODUCT\x10\x02\x12\x19\n" +
	"\x15DIMENSION_KEY_PROJECT\x10\x03\x12\x18\n" +
	"\x14DIMENSION_KEY_REGION\x10\x04\x12\x1d\n" +
	"\x19DIMENSION_KEY_COST_CENTER\x10\x05*\xab\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ACCOUNT_TYPE_ASSET\x10\x01\x12\x1a\n" +
	"\x16ACCOUNT_TYPE_LIABILITY\x10\x02\x12\x17\n" +
	"\x13ACCOUNT_TYPE_EQUITY\x10\x03\x12\x17\n" +
	"\x13ACCOUNT_TYPE_INCOME\x10\x04\x12\x18\n" +
	"\x14ACCOUNT_TYPE_EXPENSE\x10\x05*T\n" +
	"\tEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ENTRY_TYPE_DEBIT\x10\x01\x12\x15\n" +
	"\x11ENTRY_TYPE_CREDIT\x10\x02*\xb8\x01\n" +
	"\x11TransactionStatus\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19TRANSACTION_STATUS_POSTED\x10\x02\x12\x1f\n" +
	"\x1bTRANSACTION_STATUS_REVERSED\x10\x03\x12\x1f\n" +
	"\x1bTRANSACTION_STATUS_IN_BATCH\x10\x04*z\n" +
	"\n" +
	"LedgerType\x12\x1b\n" +
	"\x17LEDGER_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eLEDGER_TYPE_GL\x10\x01\x12\x12\n" +
	"\x0eLEDGER_TYPE_AR\x10\x02\x12\x12\n" +
	"\x0eLEDGER_TYPE_AP\x10\x03\x12\x13\n" +
	"\x0fLEDGER_TYPE_INV\x10\x04*\xae\x01\n" +
	"\x14ReconciliationStatus\x12%\n" +
	"!RECONCILIATION_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"RECONCILIATION_STATUS_UNRECONCILED\x10\x01\x12$\n" +
	" RECONCILIATION_STATUS_RECONCILED\x10\x02\x12!\n" +
	"\x1dRECONCILIATION_STATUS_PARTIAL\x10\x03*\x98\x01\n" +
	"\x11ScheduleFrequency\x12\"\n" +
	"\x1eSCHEDULE_FREQUENCY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSCHEDULE_FREQUENCY_MONTHLY\x10\x01\x12 \n" +
	"\x1cSCHEDULE_FREQUENCY_QUARTERLY\x10\x02\x12\x1d\n" +
	"\x19SCHEDULE_FREQUENCY_YEARLY\x10\x03*q\n" +
	"\x11ReportingStandard\x12\"\n" +
	"\x1eREPORTING_STANDARD_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17REPORTING_STANDARD_GAAP\x10\x01\x12\x1b\n" +
	"\x17REPORTING_STANDARD_IFRS\x10\x02B\x1dZ\x1baccounting/proto/accountingb\x06proto3"

var (
	file_proto_accounting_accounting_proto_rawDescOnce sync.Once
	file_proto_accounting_accounting_proto_rawDescData []byte
)

func file_proto_accounting_accounting_proto_rawDescGZIP() []byte {
	file_proto_accounting_accounting_proto_rawDescOnce.Do(func() {
		file_proto_accounting_accounting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accounting_accounting_proto_rawDesc), len(file_proto_accounting_accounting_proto_rawDesc)))
	})
	return file_proto_accounting_accounting_proto_rawDescData
}

var file_proto_accounting_accounting_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_proto_accounting_accounting_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_accounting_accounting_proto_goTypes = []any{
	(DimensionKeyEnum)(0),         // 0: accounting.DimensionKeyEnum
	(AccountType)(0),              // 1: accounting.AccountType
	(EntryType)(0),                // 2: accounting.EntryType
	(TransactionStatus)(0),        // 3: accounting.TransactionStatus
	(LedgerType)(0),               // 4: accounting.LedgerType
	(ReconciliationStatus)(0),     // 5: accounting.ReconciliationStatus
	(ScheduleFrequency)(0),        // 6: accounting.ScheduleFrequency
	(ReportingStandard)(0),        // 7: accounting.ReportingStandard
	(*Currency)(nil),              // 8: accounting.Currency
	(*Dimension)(nil),             // 9: accounting.Dimension
	(*Amount)(nil),                // 10: accounting.Amount
	(*Account)(nil),               // 11: accounting.Account
	(*Entry)(nil),                 // 12: accounting.Entry
	(*Transaction)(nil),           // 13: accounting.Transaction
	(*Period)(nil),                // 14: accounting.Period
	(*Ledger)(nil),                // 15: accounting.Ledger
	(*Reconciliation)(nil),        // 16: accounting.Reconciliation
	(*RecognitionSchedule)(nil),   // 17: accounting.RecognitionSchedule
	(*ReportingContext)(nil),      // 18: accounting.ReportingContext
	(*JournalEvent)(nil),          // 19: accounting.JournalEvent
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_proto_accounting_accounting_proto_depIdxs = []int32{
	20, // 0: accounting.Amount.exchange_rate_date:type_name -> google.protobuf.Timestamp
	1,  // 1: accounting.Account.type:type_name -> accounting.AccountType
	9,  // 2: accounting.Account.dimensions:type_name -> accounting.Dimension
	20, // 3: accounting.Account.created_at:type_name -> google.protobuf.Timestamp
	20, // 4: accounting.Account.closed_at:type_name -> google.protobuf.Timestamp
	2,  // 5: accounting.Entry.type:type_name -> accounting.EntryType
	10, // 6: accounting.Entry.amount:type_name -> accounting.Amount
	9,  // 7: accounting.Entry.dimensions:type_name -> accounting.Dimension
	20, // 8: accounting.Transaction.valid_time:type_name -> google.protobuf.Timestamp
	20, // 9: accounting.Transaction.transaction_time:type_name -> google.protobuf.Timestamp
	3,  // 10: accounting.Transaction.status:type_name -> accounting.TransactionStatus
	12, // 11: accounting.Transaction.entries:type_name -> accounting.Entry
	20, // 12: accounting.Transaction.created_at:type_name -> google.protobuf.Timestamp
	20, // 13: accounting.Transaction.updated_at:type_name -> google.protobuf.Timestamp
	20, // 14: accounting.Period.start:type_name -> google.protobuf.Timestamp
	20, // 15: accounting.Period.end:type_name -> google.protobuf.Timestamp
	20, // 16: accounting.Period.soft_closed_at:type_name -> google.protobuf.Timestamp
	20, // 17: accounting.Period.hard_closed_at:type_name -> google.protobuf.Timestamp
	4,  // 18: accounting.Ledger.type:type_name -> accounting.LedgerType
	5,  // 19: accounting.Reconciliation.status:type_name -> accounting.ReconciliationStatus
	20, // 20: accounting.Reconciliation.created_at:type_name -> google.protobuf.Timestamp
	20, // 21: accounting.Reconciliation.completed_at:type_name -> google.protobuf.Timestamp
	6,  // 22: accounting.RecognitionSchedule.frequency:type_name -> accounting.ScheduleFrequency
	20, // 23: accounting.RecognitionSchedule.start_time:type_name -> google.protobuf.Timestamp
	20, // 24: accounting.RecognitionSchedule.created_at:type_name -> google.protobuf.Timestamp
	7,  // 25: accounting.ReportingContext.standard:type_name -> accounting.ReportingStandard
	20, // 26: accounting.JournalEvent.valid_time:type_name -> google.protobuf.Timestamp
	20, // 27: accounting.JournalEvent.transaction_time:type_name -> google.protobuf.Timestamp
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_accounting_accounting_proto_init() }
func file_proto_accounting_accounting_proto_init() {
	if File_proto_accounting_accounting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accounting_accounting_proto_rawDesc), len(file_proto_accounting_accounting_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_accounting_accounting_proto_goTypes,
		DependencyIndexes: file_proto_accounting_accounting_proto_depIdxs,
		EnumInfos:         file_proto_accounting_accounting_proto_enumTypes,
		MessageInfos:      file_proto_accounting_accounting_proto_msgTypes,
	}.Build()
	File_proto_accounting_accounting_proto = out.File
	file_proto_accounting_accounting_proto_goTypes = nil
	file_proto_accounting_accounting_proto_depIdxs = nil
}
