// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/accounting/accrual.proto

package accounting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccrualType enum
type AccrualType int32

const (
	AccrualType_ACCRUAL_TYPE_UNSPECIFIED      AccrualType = 0
	AccrualType_ACCRUAL_TYPE_REVENUE          AccrualType = 1
	AccrualType_ACCRUAL_TYPE_EXPENSE          AccrualType = 2
	AccrualType_ACCRUAL_TYPE_DEFERRED_REVENUE AccrualType = 3
	AccrualType_ACCRUAL_TYPE_DEFERRED_EXPENSE AccrualType = 4
)

// Enum value maps for AccrualType.
var (
	AccrualType_name = map[int32]string{
		0: "ACCRUAL_TYPE_UNSPECIFIED",
		1: "ACCRUAL_TYPE_REVENUE",
		2: "ACCRUAL_TYPE_EXPENSE",
		3: "ACCRUAL_TYPE_DEFERRED_REVENUE",
		4: "ACCRUAL_TYPE_DEFERRED_EXPENSE",
	}
	AccrualType_value = map[string]int32{
		"ACCRUAL_TYPE_UNSPECIFIED":      0,
		"ACCRUAL_TYPE_REVENUE":          1,
		"ACCRUAL_TYPE_EXPENSE":          2,
		"ACCRUAL_TYPE_DEFERRED_REVENUE": 3,
		"ACCRUAL_TYPE_DEFERRED_EXPENSE": 4,
	}
)

func (x AccrualType) Enum() *AccrualType {
	p := new(AccrualType)
	*p = x
	return p
}

func (x AccrualType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccrualType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_accrual_proto_enumTypes[0].Descriptor()
}

func (AccrualType) Type() protoreflect.EnumType {
	return &file_proto_accounting_accrual_proto_enumTypes[0]
}

func (x AccrualType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccrualType.Descriptor instead.
func (AccrualType) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_accrual_proto_rawDescGZIP(), []int{0}
}

// RecognitionEntry
type RecognitionEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ScheduleId      string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	PeriodNumber    int32                  `protobuf:"varint,3,opt,name=period_number,json=periodNumber,proto3" json:"period_number,omitempty"`
	RecognitionDate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=recognition_date,json=recognitionDate,proto3" json:"recognition_date,omitempty"`
	Amount          *Amount                `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	TransactionId   string                 `protobuf:"bytes,7,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ProcessedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecognitionEntry) Reset() {
	*x = RecognitionEntry{}
	mi := &file_proto_accounting_accrual_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognitionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognitionEntry) ProtoMessage() {}

func (x *RecognitionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accrual_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognitionEntry.ProtoReflect.Descriptor instead.
func (*RecognitionEntry) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accrual_proto_rawDescGZIP(), []int{0}
}

func (x *RecognitionEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecognitionEntry) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *RecognitionEntry) GetPeriodNumber() int32 {
	if x != nil {
		return x.PeriodNumber
	}
	return 0
}

func (x *RecognitionEntry) GetRecognitionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RecognitionDate
	}
	return nil
}

func (x *RecognitionEntry) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *RecognitionEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecognitionEntry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RecognitionEntry) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

// AccrualTemplate
type AccrualTemplate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccrualType       AccrualType            `protobuf:"varint,3,opt,name=accrual_type,json=accrualType,proto3,enum=accounting.AccrualType" json:"accrual_type,omitempty"`
	AccrualAccountId  string                 `protobuf:"bytes,4,opt,name=accrual_account_id,json=accrualAccountId,proto3" json:"accrual_account_id,omitempty"`
	RevenueAccountId  string                 `protobuf:"bytes,5,opt,name=revenue_account_id,json=revenueAccountId,proto3" json:"revenue_account_id,omitempty"`
	ExpenseAccountId  string                 `protobuf:"bytes,6,opt,name=expense_account_id,json=expenseAccountId,proto3" json:"expense_account_id,omitempty"`
	DeferralAccountId string                 `protobuf:"bytes,7,opt,name=deferral_account_id,json=deferralAccountId,proto3" json:"deferral_account_id,omitempty"`
	Dimensions        []*Dimension           `protobuf:"bytes,8,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AccrualTemplate) Reset() {
	*x = AccrualTemplate{}
	mi := &file_proto_accounting_accrual_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccrualTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccrualTemplate) ProtoMessage() {}

func (x *AccrualTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_accrual_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccrualTemplate.ProtoReflect.Descriptor instead.
func (*AccrualTemplate) Descriptor() ([]byte, []int) {
	return file_proto_accounting_accrual_proto_rawDescGZIP(), []int{1}
}

func (x *AccrualTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccrualTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccrualTemplate) GetAccrualType() AccrualType {
	if x != nil {
		return x.AccrualType
	}
	return AccrualType_ACCRUAL_TYPE_UNSPECIFIED
}

func (x *AccrualTemplate) GetAccrualAccountId() string {
	if x != nil {
		return x.AccrualAccountId
	}
	return ""
}

func (x *AccrualTemplate) GetRevenueAccountId() string {
	if x != nil {
		return x.RevenueAccountId
	}
	return ""
}

func (x *AccrualTemplate) GetExpenseAccountId() string {
	if x != nil {
		return x.ExpenseAccountId
	}
	return ""
}

func (x *AccrualTemplate) GetDeferralAccountId() string {
	if x != nil {
		return x.DeferralAccountId
	}
	return ""
}

func (x *AccrualTemplate) GetDimensions() []*Dimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

var File_proto_accounting_accrual_proto protoreflect.FileDescriptor

const file_proto_accounting_accrual_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/accounting/accrual.proto\x12\n" +
	"accounting\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!proto/accounting/accounting.proto\"\xd9\x02\n" +
	"\x10RecognitionEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12#\n" +
	"\rperiod_number\x18\x03 \x01(\x05R\fperiodNumber\x12E\n" +
	"\x10recognition_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0frecognitionDate\x12*\n" +
	"\x06amount\x18\x05 \x01(\v2\x12.accounting.AmountR\x06amount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\a \x01(\tR\rtransactionId\x12=\n" +
	"\fprocessed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\"\xe2\x02\n" +
	"\x0fAccrualTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\faccrual_type\x18\x03 \x01(\x0e2\x17.accounting.AccrualTypeR\vaccrualType\x12,\n" +
	"\x12accrual_account_id\x18\x04 \x01(\tR\x10accrualAccountId\x12,\n" +
	"\x12revenue_account_id\x18\x05 \x01(\tR\x10revenueAccountId\x12,\n" +
	"\x12expense_account_id\x18\x06 \x01(\tR\x10expenseAccountId\x12.\n" +
	"\x13deferral_account_id\x18\a \x01(\tR\x11deferralAccountId\x125\n" +
	"\n" +
	"dimensions\x18\b \x03(\v2\x15.accounting.DimensionR\n" +
	"dimensions*\xa5\x01\n" +
	"\vAccrualType\x12\x1c\n" +
	"\x18ACCRUAL_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACCRUAL_TYPE_REVENUE\x10\x01\x12\x18\n" +
	"\x14ACCRUAL_TYPE_EXPENSE\x10\x02\x12!\n" +
	"\x1dACCRUAL_TYPE_DEFERRED_REVENUE\x10\x03\x12!\n" +
	"\x1dACCRUAL_TYPE_DEFERRED_EXPENSE\x10\x04B\x1dZ\x1baccounting/proto/accountingb\x06proto3"

var (
	file_proto_accounting_accrual_proto_rawDescOnce sync.Once
	file_proto_accounting_accrual_proto_rawDescData []byte
)

func file_proto_accounting_accrual_proto_rawDescGZIP() []byte {
	file_proto_accounting_accrual_proto_rawDescOnce.Do(func() {
		file_proto_accounting_accrual_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accounting_accrual_proto_rawDesc), len(file_proto_accounting_accrual_proto_rawDesc)))
	})
	return file_proto_accounting_accrual_proto_rawDescData
}

var file_proto_accounting_accrual_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_accounting_accrual_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_accounting_accrual_proto_goTypes = []any{
	(AccrualType)(0),              // 0: accounting.AccrualType
	(*RecognitionEntry)(nil),      // 1: accounting.RecognitionEntry
	(*AccrualTemplate)(nil),       // 2: accounting.AccrualTemplate
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*Amount)(nil),                // 4: accounting.Amount
	(*Dimension)(nil),             // 5: accounting.Dimension
}
var file_proto_accounting_accrual_proto_depIdxs = []int32{
	3, // 0: accounting.RecognitionEntry.recognition_date:type_name -> google.protobuf.Timestamp
	4, // 1: accounting.RecognitionEntry.amount:type_name -> accounting.Amount
	3, // 2: accounting.RecognitionEntry.processed_at:type_name -> google.protobuf.Timestamp
	0, // 3: accounting.AccrualTemplate.accrual_type:type_name -> accounting.AccrualType
	5, // 4: accounting.AccrualTemplate.dimensions:type_name -> accounting.Dimension
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_accounting_accrual_proto_init() }
func file_proto_accounting_accrual_proto_init() {
	if File_proto_accounting_accrual_proto != nil {
		return
	}
	file_proto_accounting_accounting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accounting_accrual_proto_rawDesc), len(file_proto_accounting_accrual_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_accounting_accrual_proto_goTypes,
		DependencyIndexes: file_proto_accounting_accrual_proto_depIdxs,
		EnumInfos:         file_proto_accounting_accrual_proto_enumTypes,
		MessageInfos:      file_proto_accounting_accrual_proto_msgTypes,
	}.Build()
	File_proto_accounting_accrual_proto = out.File
	file_proto_accounting_accrual_proto_goTypes = nil
	file_proto_accounting_accrual_proto_depIdxs = nil
}
