// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/accounting/aml.proto

package accounting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AMLFramework enum
type AMLFramework int32

const (
	AMLFramework_AML_FRAMEWORK_UNSPECIFIED AMLFramework = 0
	AMLFramework_AML_FRAMEWORK_BSA         AMLFramework = 1
	AMLFramework_AML_FRAMEWORK_AMLD        AMLFramework = 2
	AMLFramework_AML_FRAMEWORK_FATF        AMLFramework = 3
	AMLFramework_AML_FRAMEWORK_FINCEN      AMLFramework = 4
	AMLFramework_AML_FRAMEWORK_OFAC        AMLFramework = 5
)

// Enum value maps for AMLFramework.
var (
	AMLFramework_name = map[int32]string{
		0: "AML_FRAMEWORK_UNSPECIFIED",
		1: "AML_FRAMEWORK_BSA",
		2: "AML_FRAMEWORK_AMLD",
		3: "AML_FRAMEWORK_FATF",
		4: "AML_FRAMEWORK_FINCEN",
		5: "AML_FRAMEWORK_OFAC",
	}
	AMLFramework_value = map[string]int32{
		"AML_FRAMEWORK_UNSPECIFIED": 0,
		"AML_FRAMEWORK_BSA":         1,
		"AML_FRAMEWORK_AMLD":        2,
		"AML_FRAMEWORK_FATF":        3,
		"AML_FRAMEWORK_FINCEN":      4,
		"AML_FRAMEWORK_OFAC":        5,
	}
)

func (x AMLFramework) Enum() *AMLFramework {
	p := new(AMLFramework)
	*p = x
	return p
}

func (x AMLFramework) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AMLFramework) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_aml_proto_enumTypes[0].Descriptor()
}

func (AMLFramework) Type() protoreflect.EnumType {
	return &file_proto_accounting_aml_proto_enumTypes[0]
}

func (x AMLFramework) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AMLFramework.Descriptor instead.
func (AMLFramework) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{0}
}

// AMLRiskLevel enum
type AMLRiskLevel int32

const (
	AMLRiskLevel_AML_RISK_LEVEL_UNSPECIFIED AMLRiskLevel = 0
	AMLRiskLevel_AML_RISK_LEVEL_LOW         AMLRiskLevel = 1
	AMLRiskLevel_AML_RISK_LEVEL_MEDIUM      AMLRiskLevel = 2
	AMLRiskLevel_AML_RISK_LEVEL_HIGH        AMLRiskLevel = 3
	AMLRiskLevel_AML_RISK_LEVEL_CRITICAL    AMLRiskLevel = 4
)

// Enum value maps for AMLRiskLevel.
var (
	AMLRiskLevel_name = map[int32]string{
		0: "AML_RISK_LEVEL_UNSPECIFIED",
		1: "AML_RISK_LEVEL_LOW",
		2: "AML_RISK_LEVEL_MEDIUM",
		3: "AML_RISK_LEVEL_HIGH",
		4: "AML_RISK_LEVEL_CRITICAL",
	}
	AMLRiskLevel_value = map[string]int32{
		"AML_RISK_LEVEL_UNSPECIFIED": 0,
		"AML_RISK_LEVEL_LOW":         1,
		"AML_RISK_LEVEL_MEDIUM":      2,
		"AML_RISK_LEVEL_HIGH":        3,
		"AML_RISK_LEVEL_CRITICAL":    4,
	}
)

func (x AMLRiskLevel) Enum() *AMLRiskLevel {
	p := new(AMLRiskLevel)
	*p = x
	return p
}

func (x AMLRiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AMLRiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_aml_proto_enumTypes[1].Descriptor()
}

func (AMLRiskLevel) Type() protoreflect.EnumType {
	return &file_proto_accounting_aml_proto_enumTypes[1]
}

func (x AMLRiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AMLRiskLevel.Descriptor instead.
func (AMLRiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{1}
}

// AMLRuleType enum
type AMLRuleType int32

const (
	AMLRuleType_AML_RULE_TYPE_UNSPECIFIED            AMLRuleType = 0
	AMLRuleType_AML_RULE_TYPE_CTR                    AMLRuleType = 1
	AMLRuleType_AML_RULE_TYPE_SAR                    AMLRuleType = 2
	AMLRuleType_AML_RULE_TYPE_STRUCTURING            AMLRuleType = 3
	AMLRuleType_AML_RULE_TYPE_SMURFING               AMLRuleType = 4
	AMLRuleType_AML_RULE_TYPE_LAYERING               AMLRuleType = 5
	AMLRuleType_AML_RULE_TYPE_RAPID_MOVEMENT         AMLRuleType = 6
	AMLRuleType_AML_RULE_TYPE_ROUND_AMOUNTS          AMLRuleType = 7
	AMLRuleType_AML_RULE_TYPE_KYC                    AMLRuleType = 8
	AMLRuleType_AML_RULE_TYPE_CDD                    AMLRuleType = 9
	AMLRuleType_AML_RULE_TYPE_EDD                    AMLRuleType = 10
	AMLRuleType_AML_RULE_TYPE_PEP                    AMLRuleType = 11
	AMLRuleType_AML_RULE_TYPE_SANCTIONS              AMLRuleType = 12
	AMLRuleType_AML_RULE_TYPE_HIGH_RISK_JURISDICTION AMLRuleType = 13
	AMLRuleType_AML_RULE_TYPE_NCCT                   AMLRuleType = 14
	AMLRuleType_AML_RULE_TYPE_VELOCITY               AMLRuleType = 15
	AMLRuleType_AML_RULE_TYPE_FREQUENCY              AMLRuleType = 16
	AMLRuleType_AML_RULE_TYPE_CONCENTRATION          AMLRuleType = 17
	AMLRuleType_AML_RULE_TYPE_UNUSUAL_TIMING         AMLRuleType = 18
	AMLRuleType_AML_RULE_TYPE_CIRCULAR_TRANSFERS     AMLRuleType = 19
	AMLRuleType_AML_RULE_TYPE_CASH_INTENSIVE         AMLRuleType = 20
	AMLRuleType_AML_RULE_TYPE_HIGH_RISK_PRODUCTS     AMLRuleType = 21
	AMLRuleType_AML_RULE_TYPE_ACCOUNT_DORMANCY       AMLRuleType = 22
	AMLRuleType_AML_RULE_TYPE_IDENTITY_VERIFICATION  AMLRuleType = 23
	AMLRuleType_AML_RULE_TYPE_SOURCE_OF_FUNDS        AMLRuleType = 24
	AMLRuleType_AML_RULE_TYPE_WIRE_STRIPPING         AMLRuleType = 25
	AMLRuleType_AML_RULE_TYPE_THIRD_PARTY_CHECK      AMLRuleType = 26
	AMLRuleType_AML_RULE_TYPE_NEGATIVE_MEDIA         AMLRuleType = 27
	AMLRuleType_AML_RULE_TYPE_ACCOUNT_TAKEOVER       AMLRuleType = 28
	AMLRuleType_AML_RULE_TYPE_TRADE_BASED_ML         AMLRuleType = 29
	AMLRuleType_AML_RULE_TYPE_SHELL_COMPANY          AMLRuleType = 30
	AMLRuleType_AML_RULE_TYPE_PREPAID_CARDS          AMLRuleType = 31
	AMLRuleType_AML_RULE_TYPE_CRYPTOCURRENCY         AMLRuleType = 32
	AMLRuleType_AML_RULE_TYPE_JUST_UNDER_THRESHOLD   AMLRuleType = 33
	AMLRuleType_AML_RULE_TYPE_UNEXPECTED_GEOGRAPHY   AMLRuleType = 34
)

// Enum value maps for AMLRuleType.
var (
	AMLRuleType_name = map[int32]string{
		0:  "AML_RULE_TYPE_UNSPECIFIED",
		1:  "AML_RULE_TYPE_CTR",
		2:  "AML_RULE_TYPE_SAR",
		3:  "AML_RULE_TYPE_STRUCTURING",
		4:  "AML_RULE_TYPE_SMURFING",
		5:  "AML_RULE_TYPE_LAYERING",
		6:  "AML_RULE_TYPE_RAPID_MOVEMENT",
		7:  "AML_RULE_TYPE_ROUND_AMOUNTS",
		8:  "AML_RULE_TYPE_KYC",
		9:  "AML_RULE_TYPE_CDD",
		10: "AML_RULE_TYPE_EDD",
		11: "AML_RULE_TYPE_PEP",
		12: "AML_RULE_TYPE_SANCTIONS",
		13: "AML_RULE_TYPE_HIGH_RISK_JURISDICTION",
		14: "AML_RULE_TYPE_NCCT",
		15: "AML_RULE_TYPE_VELOCITY",
		16: "AML_RULE_TYPE_FREQUENCY",
		17: "AML_RULE_TYPE_CONCENTRATION",
		18: "AML_RULE_TYPE_UNUSUAL_TIMING",
		19: "AML_RULE_TYPE_CIRCULAR_TRANSFERS",
		20: "AML_RULE_TYPE_CASH_INTENSIVE",
		21: "AML_RULE_TYPE_HIGH_RISK_PRODUCTS",
		22: "AML_RULE_TYPE_ACCOUNT_DORMANCY",
		23: "AML_RULE_TYPE_IDENTITY_VERIFICATION",
		24: "AML_RULE_TYPE_SOURCE_OF_FUNDS",
		25: "AML_RULE_TYPE_WIRE_STRIPPING",
		26: "AML_RULE_TYPE_THIRD_PARTY_CHECK",
		27: "AML_RULE_TYPE_NEGATIVE_MEDIA",
		28: "AML_RULE_TYPE_ACCOUNT_TAKEOVER",
		29: "AML_RULE_TYPE_TRADE_BASED_ML",
		30: "AML_RULE_TYPE_SHELL_COMPANY",
		31: "AML_RULE_TYPE_PREPAID_CARDS",
		32: "AML_RULE_TYPE_CRYPTOCURRENCY",
		33: "AML_RULE_TYPE_JUST_UNDER_THRESHOLD",
		34: "AML_RULE_TYPE_UNEXPECTED_GEOGRAPHY",
	}
	AMLRuleType_value = map[string]int32{
		"AML_RULE_TYPE_UNSPECIFIED":            0,
		"AML_RULE_TYPE_CTR":                    1,
		"AML_RULE_TYPE_SAR":                    2,
		"AML_RULE_TYPE_STRUCTURING":            3,
		"AML_RULE_TYPE_SMURFING":               4,
		"AML_RULE_TYPE_LAYERING":               5,
		"AML_RULE_TYPE_RAPID_MOVEMENT":         6,
		"AML_RULE_TYPE_ROUND_AMOUNTS":          7,
		"AML_RULE_TYPE_KYC":                    8,
		"AML_RULE_TYPE_CDD":                    9,
		"AML_RULE_TYPE_EDD":                    10,
		"AML_RULE_TYPE_PEP":                    11,
		"AML_RULE_TYPE_SANCTIONS":              12,
		"AML_RULE_TYPE_HIGH_RISK_JURISDICTION": 13,
		"AML_RULE_TYPE_NCCT":                   14,
		"AML_RULE_TYPE_VELOCITY":               15,
		"AML_RULE_TYPE_FREQUENCY":              16,
		"AML_RULE_TYPE_CONCENTRATION":          17,
		"AML_RULE_TYPE_UNUSUAL_TIMING":         18,
		"AML_RULE_TYPE_CIRCULAR_TRANSFERS":     19,
		"AML_RULE_TYPE_CASH_INTENSIVE":         20,
		"AML_RULE_TYPE_HIGH_RISK_PRODUCTS":     21,
		"AML_RULE_TYPE_ACCOUNT_DORMANCY":       22,
		"AML_RULE_TYPE_IDENTITY_VERIFICATION":  23,
		"AML_RULE_TYPE_SOURCE_OF_FUNDS":        24,
		"AML_RULE_TYPE_WIRE_STRIPPING":         25,
		"AML_RULE_TYPE_THIRD_PARTY_CHECK":      26,
		"AML_RULE_TYPE_NEGATIVE_MEDIA":         27,
		"AML_RULE_TYPE_ACCOUNT_TAKEOVER":       28,
		"AML_RULE_TYPE_TRADE_BASED_ML":         29,
		"AML_RULE_TYPE_SHELL_COMPANY":          30,
		"AML_RULE_TYPE_PREPAID_CARDS":          31,
		"AML_RULE_TYPE_CRYPTOCURRENCY":         32,
		"AML_RULE_TYPE_JUST_UNDER_THRESHOLD":   33,
		"AML_RULE_TYPE_UNEXPECTED_GEOGRAPHY":   34,
	}
)

func (x AMLRuleType) Enum() *AMLRuleType {
	p := new(AMLRuleType)
	*p = x
	return p
}

func (x AMLRuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AMLRuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_aml_proto_enumTypes[2].Descriptor()
}

func (AMLRuleType) Type() protoreflect.EnumType {
	return &file_proto_accounting_aml_proto_enumTypes[2]
}

func (x AMLRuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AMLRuleType.Descriptor instead.
func (AMLRuleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{2}
}

// InvestigationAction
type InvestigationAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TakenBy       string                 `protobuf:"bytes,4,opt,name=taken_by,json=takenBy,proto3" json:"taken_by,omitempty"`
	TakenAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvestigationAction) Reset() {
	*x = InvestigationAction{}
	mi := &file_proto_accounting_aml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestigationAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestigationAction) ProtoMessage() {}

func (x *InvestigationAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestigationAction.ProtoReflect.Descriptor instead.
func (*InvestigationAction) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{0}
}

func (x *InvestigationAction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvestigationAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InvestigationAction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InvestigationAction) GetTakenBy() string {
	if x != nil {
		return x.TakenBy
	}
	return ""
}

func (x *InvestigationAction) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *InvestigationAction) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// InvestigationNote
type InvestigationNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvestigationNote) Reset() {
	*x = InvestigationNote{}
	mi := &file_proto_accounting_aml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestigationNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestigationNote) ProtoMessage() {}

func (x *InvestigationNote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestigationNote.ProtoReflect.Descriptor instead.
func (*InvestigationNote) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{1}
}

func (x *InvestigationNote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvestigationNote) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InvestigationNote) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *InvestigationNote) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// AMLInvestigation
type AMLInvestigation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlertId       string                 `protobuf:"bytes,2,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Investigator  string                 `protobuf:"bytes,3,opt,name=investigator,proto3" json:"investigator,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Priority      string                 `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Findings      []string               `protobuf:"bytes,8,rep,name=findings,proto3" json:"findings,omitempty"`
	Actions       []*InvestigationAction `protobuf:"bytes,9,rep,name=actions,proto3" json:"actions,omitempty"`
	Notes         []*InvestigationNote   `protobuf:"bytes,10,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMLInvestigation) Reset() {
	*x = AMLInvestigation{}
	mi := &file_proto_accounting_aml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLInvestigation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLInvestigation) ProtoMessage() {}

func (x *AMLInvestigation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLInvestigation.ProtoReflect.Descriptor instead.
func (*AMLInvestigation) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{2}
}

func (x *AMLInvestigation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AMLInvestigation) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *AMLInvestigation) GetInvestigator() string {
	if x != nil {
		return x.Investigator
	}
	return ""
}

func (x *AMLInvestigation) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *AMLInvestigation) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *AMLInvestigation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AMLInvestigation) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *AMLInvestigation) GetFindings() []string {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *AMLInvestigation) GetActions() []*InvestigationAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AMLInvestigation) GetNotes() []*InvestigationNote {
	if x != nil {
		return x.Notes
	}
	return nil
}

// AMLEvidence
type AMLEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ValueJson     string                 `protobuf:"bytes,3,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"` // JSON-encoded value
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Confidence    float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMLEvidence) Reset() {
	*x = AMLEvidence{}
	mi := &file_proto_accounting_aml_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLEvidence) ProtoMessage() {}

func (x *AMLEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLEvidence.ProtoReflect.Descriptor instead.
func (*AMLEvidence) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{3}
}

func (x *AMLEvidence) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AMLEvidence) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AMLEvidence) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *AMLEvidence) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AMLEvidence) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AMLEvidence) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

// AMLDisposition
type AMLDisposition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DecidedBy     string                 `protobuf:"bytes,4,opt,name=decided_by,json=decidedBy,proto3" json:"decided_by,omitempty"`
	DecidedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	Rationale     string                 `protobuf:"bytes,6,opt,name=rationale,proto3" json:"rationale,omitempty"`
	SarNumber     string                 `protobuf:"bytes,7,opt,name=sar_number,json=sarNumber,proto3" json:"sar_number,omitempty"`
	ReportedTo    []string               `protobuf:"bytes,8,rep,name=reported_to,json=reportedTo,proto3" json:"reported_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMLDisposition) Reset() {
	*x = AMLDisposition{}
	mi := &file_proto_accounting_aml_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLDisposition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLDisposition) ProtoMessage() {}

func (x *AMLDisposition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLDisposition.ProtoReflect.Descriptor instead.
func (*AMLDisposition) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{4}
}

func (x *AMLDisposition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AMLDisposition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AMLDisposition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AMLDisposition) GetDecidedBy() string {
	if x != nil {
		return x.DecidedBy
	}
	return ""
}

func (x *AMLDisposition) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

func (x *AMLDisposition) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *AMLDisposition) GetSarNumber() string {
	if x != nil {
		return x.SarNumber
	}
	return ""
}

func (x *AMLDisposition) GetReportedTo() []string {
	if x != nil {
		return x.ReportedTo
	}
	return nil
}

// AMLAlert
type AMLAlert struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleType       AMLRuleType            `protobuf:"varint,2,opt,name=rule_type,json=ruleType,proto3,enum=accounting.AMLRuleType" json:"rule_type,omitempty"`
	Framework      AMLFramework           `protobuf:"varint,3,opt,name=framework,proto3,enum=accounting.AMLFramework" json:"framework,omitempty"`
	RiskLevel      AMLRiskLevel           `protobuf:"varint,4,opt,name=risk_level,json=riskLevel,proto3,enum=accounting.AMLRiskLevel" json:"risk_level,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	EntityId       string                 `protobuf:"bytes,7,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType     string                 `protobuf:"bytes,8,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	TransactionIds []string               `protobuf:"bytes,9,rep,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"`
	AccountIds     []string               `protobuf:"bytes,10,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	Amount         *Amount                `protobuf:"bytes,11,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,12,opt,name=currency,proto3" json:"currency,omitempty"`
	DetectedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	Status         string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	AssignedTo     string                 `protobuf:"bytes,15,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	Investigation  *AMLInvestigation      `protobuf:"bytes,16,opt,name=investigation,proto3" json:"investigation,omitempty"`
	Evidence       []*AMLEvidence         `protobuf:"bytes,17,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Dispositions   []*AMLDisposition      `protobuf:"bytes,18,rep,name=dispositions,proto3" json:"dispositions,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AMLAlert) Reset() {
	*x = AMLAlert{}
	mi := &file_proto_accounting_aml_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLAlert) ProtoMessage() {}

func (x *AMLAlert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLAlert.ProtoReflect.Descriptor instead.
func (*AMLAlert) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{5}
}

func (x *AMLAlert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AMLAlert) GetRuleType() AMLRuleType {
	if x != nil {
		return x.RuleType
	}
	return AMLRuleType_AML_RULE_TYPE_UNSPECIFIED
}

func (x *AMLAlert) GetFramework() AMLFramework {
	if x != nil {
		return x.Framework
	}
	return AMLFramework_AML_FRAMEWORK_UNSPECIFIED
}

func (x *AMLAlert) GetRiskLevel() AMLRiskLevel {
	if x != nil {
		return x.RiskLevel
	}
	return AMLRiskLevel_AML_RISK_LEVEL_UNSPECIFIED
}

func (x *AMLAlert) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AMLAlert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AMLAlert) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AMLAlert) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AMLAlert) GetTransactionIds() []string {
	if x != nil {
		return x.TransactionIds
	}
	return nil
}

func (x *AMLAlert) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

func (x *AMLAlert) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *AMLAlert) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AMLAlert) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *AMLAlert) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AMLAlert) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *AMLAlert) GetInvestigation() *AMLInvestigation {
	if x != nil {
		return x.Investigation
	}
	return nil
}

func (x *AMLAlert) GetEvidence() []*AMLEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *AMLAlert) GetDispositions() []*AMLDisposition {
	if x != nil {
		return x.Dispositions
	}
	return nil
}

func (x *AMLAlert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AMLAlert) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// AMLRule
type AMLRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          AMLRuleType            `protobuf:"varint,3,opt,name=type,proto3,enum=accounting.AMLRuleType" json:"type,omitempty"`
	Framework     AMLFramework           `protobuf:"varint,4,opt,name=framework,proto3,enum=accounting.AMLFramework" json:"framework,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Thresholds    map[string]string      `protobuf:"bytes,7,rep,name=thresholds,proto3" json:"thresholds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // JSON-encoded threshold values
	TimeWindows   map[string]int32       `protobuf:"bytes,8,rep,name=time_windows,json=timeWindows,proto3" json:"time_windows,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Currencies    []string               `protobuf:"bytes,9,rep,name=currencies,proto3" json:"currencies,omitempty"`
	Countries     []string               `protobuf:"bytes,10,rep,name=countries,proto3" json:"countries,omitempty"`
	BaseScore     int32                  `protobuf:"varint,11,opt,name=base_score,json=baseScore,proto3" json:"base_score,omitempty"`
	RiskMultiple  float64                `protobuf:"fixed64,12,opt,name=risk_multiple,json=riskMultiple,proto3" json:"risk_multiple,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMLRule) Reset() {
	*x = AMLRule{}
	mi := &file_proto_accounting_aml_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLRule) ProtoMessage() {}

func (x *AMLRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLRule.ProtoReflect.Descriptor instead.
func (*AMLRule) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{6}
}

func (x *AMLRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AMLRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AMLRule) GetType() AMLRuleType {
	if x != nil {
		return x.Type
	}
	return AMLRuleType_AML_RULE_TYPE_UNSPECIFIED
}

func (x *AMLRule) GetFramework() AMLFramework {
	if x != nil {
		return x.Framework
	}
	return AMLFramework_AML_FRAMEWORK_UNSPECIFIED
}

func (x *AMLRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AMLRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AMLRule) GetThresholds() map[string]string {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

func (x *AMLRule) GetTimeWindows() map[string]int32 {
	if x != nil {
		return x.TimeWindows
	}
	return nil
}

func (x *AMLRule) GetCurrencies() []string {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *AMLRule) GetCountries() []string {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *AMLRule) GetBaseScore() int32 {
	if x != nil {
		return x.BaseScore
	}
	return 0
}

func (x *AMLRule) GetRiskMultiple() float64 {
	if x != nil {
		return x.RiskMultiple
	}
	return 0
}

func (x *AMLRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AMLRule) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// AMLCustomer
type AMLCustomer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId       string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type             string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	RiskLevel        AMLRiskLevel           `protobuf:"varint,5,opt,name=risk_level,json=riskLevel,proto3,enum=accounting.AMLRiskLevel" json:"risk_level,omitempty"`
	Country          string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	IsPep            bool                   `protobuf:"varint,7,opt,name=is_pep,json=isPep,proto3" json:"is_pep,omitempty"`
	IsHighRisk       bool                   `protobuf:"varint,8,opt,name=is_high_risk,json=isHighRisk,proto3" json:"is_high_risk,omitempty"`
	SanctionsMatch   bool                   `protobuf:"varint,9,opt,name=sanctions_match,json=sanctionsMatch,proto3" json:"sanctions_match,omitempty"`
	LastKycDate      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_kyc_date,json=lastKycDate,proto3" json:"last_kyc_date,omitempty"`
	LastCddDate      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_cdd_date,json=lastCddDate,proto3" json:"last_cdd_date,omitempty"`
	NextReviewDate   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=next_review_date,json=nextReviewDate,proto3" json:"next_review_date,omitempty"`
	OnboardingDate   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=onboarding_date,json=onboardingDate,proto3" json:"onboarding_date,omitempty"`
	ExpectedActivity string                 `protobuf:"bytes,14,opt,name=expected_activity,json=expectedActivity,proto3" json:"expected_activity,omitempty"`
	BusinessPurpose  string                 `protobuf:"bytes,15,opt,name=business_purpose,json=businessPurpose,proto3" json:"business_purpose,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AMLCustomer) Reset() {
	*x = AMLCustomer{}
	mi := &file_proto_accounting_aml_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLCustomer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLCustomer) ProtoMessage() {}

func (x *AMLCustomer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLCustomer.ProtoReflect.Descriptor instead.
func (*AMLCustomer) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{7}
}

func (x *AMLCustomer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AMLCustomer) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AMLCustomer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AMLCustomer) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AMLCustomer) GetRiskLevel() AMLRiskLevel {
	if x != nil {
		return x.RiskLevel
	}
	return AMLRiskLevel_AML_RISK_LEVEL_UNSPECIFIED
}

func (x *AMLCustomer) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AMLCustomer) GetIsPep() bool {
	if x != nil {
		return x.IsPep
	}
	return false
}

func (x *AMLCustomer) GetIsHighRisk() bool {
	if x != nil {
		return x.IsHighRisk
	}
	return false
}

func (x *AMLCustomer) GetSanctionsMatch() bool {
	if x != nil {
		return x.SanctionsMatch
	}
	return false
}

func (x *AMLCustomer) GetLastKycDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastKycDate
	}
	return nil
}

func (x *AMLCustomer) GetLastCddDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCddDate
	}
	return nil
}

func (x *AMLCustomer) GetNextReviewDate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextReviewDate
	}
	return nil
}

func (x *AMLCustomer) GetOnboardingDate() *timestamppb.Timestamp {
	if x != nil {
		return x.OnboardingDate
	}
	return nil
}

func (x *AMLCustomer) GetExpectedActivity() string {
	if x != nil {
		return x.ExpectedActivity
	}
	return ""
}

func (x *AMLCustomer) GetBusinessPurpose() string {
	if x != nil {
		return x.BusinessPurpose
	}
	return ""
}

func (x *AMLCustomer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AMLCustomer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// AMLTransaction
type AMLTransaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransactionId  string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount         *Amount                `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Date           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	FromCustomerId string                 `protobuf:"bytes,5,opt,name=from_customer_id,json=fromCustomerId,proto3" json:"from_customer_id,omitempty"`
	ToCustomerId   string                 `protobuf:"bytes,6,opt,name=to_customer_id,json=toCustomerId,proto3" json:"to_customer_id,omitempty"`
	FromCountry    string                 `protobuf:"bytes,7,opt,name=from_country,json=fromCountry,proto3" json:"from_country,omitempty"`
	ToCountry      string                 `protobuf:"bytes,8,opt,name=to_country,json=toCountry,proto3" json:"to_country,omitempty"`
	Purpose        string                 `protobuf:"bytes,9,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Channel        string                 `protobuf:"bytes,10,opt,name=channel,proto3" json:"channel,omitempty"`
	RiskScore      int32                  `protobuf:"varint,11,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	IsStructured   bool                   `protobuf:"varint,12,opt,name=is_structured,json=isStructured,proto3" json:"is_structured,omitempty"`
	IsSuspicious   bool                   `protobuf:"varint,13,opt,name=is_suspicious,json=isSuspicious,proto3" json:"is_suspicious,omitempty"`
	Flags          []string               `protobuf:"bytes,14,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AMLTransaction) Reset() {
	*x = AMLTransaction{}
	mi := &file_proto_accounting_aml_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLTransaction) ProtoMessage() {}

func (x *AMLTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLTransaction.ProtoReflect.Descriptor instead.
func (*AMLTransaction) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{8}
}

func (x *AMLTransaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *AMLTransaction) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *AMLTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AMLTransaction) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *AMLTransaction) GetFromCustomerId() string {
	if x != nil {
		return x.FromCustomerId
	}
	return ""
}

func (x *AMLTransaction) GetToCustomerId() string {
	if x != nil {
		return x.ToCustomerId
	}
	return ""
}

func (x *AMLTransaction) GetFromCountry() string {
	if x != nil {
		return x.FromCountry
	}
	return ""
}

func (x *AMLTransaction) GetToCountry() string {
	if x != nil {
		return x.ToCountry
	}
	return ""
}

func (x *AMLTransaction) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *AMLTransaction) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *AMLTransaction) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AMLTransaction) GetIsStructured() bool {
	if x != nil {
		return x.IsStructured
	}
	return false
}

func (x *AMLTransaction) GetIsSuspicious() bool {
	if x != nil {
		return x.IsSuspicious
	}
	return false
}

func (x *AMLTransaction) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

// CustomerRiskSummary
type CustomerRiskSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,2,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	RiskScore     int32                  `protobuf:"varint,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	AlertCount    int32                  `protobuf:"varint,4,opt,name=alert_count,json=alertCount,proto3" json:"alert_count,omitempty"`
	TotalVolume   int64                  `protobuf:"varint,5,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	LastActivity  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	RiskFactors   []string               `protobuf:"bytes,7,rep,name=risk_factors,json=riskFactors,proto3" json:"risk_factors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerRiskSummary) Reset() {
	*x = CustomerRiskSummary{}
	mi := &file_proto_accounting_aml_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerRiskSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRiskSummary) ProtoMessage() {}

func (x *CustomerRiskSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRiskSummary.ProtoReflect.Descriptor instead.
func (*CustomerRiskSummary) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{9}
}

func (x *CustomerRiskSummary) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CustomerRiskSummary) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *CustomerRiskSummary) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *CustomerRiskSummary) GetAlertCount() int32 {
	if x != nil {
		return x.AlertCount
	}
	return 0
}

func (x *CustomerRiskSummary) GetTotalVolume() int64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

func (x *CustomerRiskSummary) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

func (x *CustomerRiskSummary) GetRiskFactors() []string {
	if x != nil {
		return x.RiskFactors
	}
	return nil
}

// AMLComplianceMetrics
type AMLComplianceMetrics struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CtrFilingRate          float64                `protobuf:"fixed64,1,opt,name=ctr_filing_rate,json=ctrFilingRate,proto3" json:"ctr_filing_rate,omitempty"`
	SarFilingRate          float64                `protobuf:"fixed64,2,opt,name=sar_filing_rate,json=sarFilingRate,proto3" json:"sar_filing_rate,omitempty"`
	FalsePositiveRate      float64                `protobuf:"fixed64,3,opt,name=false_positive_rate,json=falsePositiveRate,proto3" json:"false_positive_rate,omitempty"`
	AvgResolutionTimeHours int32                  `protobuf:"varint,4,opt,name=avg_resolution_time_hours,json=avgResolutionTimeHours,proto3" json:"avg_resolution_time_hours,omitempty"`
	ComplianceScore        int32                  `protobuf:"varint,5,opt,name=compliance_score,json=complianceScore,proto3" json:"compliance_score,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AMLComplianceMetrics) Reset() {
	*x = AMLComplianceMetrics{}
	mi := &file_proto_accounting_aml_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLComplianceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLComplianceMetrics) ProtoMessage() {}

func (x *AMLComplianceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLComplianceMetrics.ProtoReflect.Descriptor instead.
func (*AMLComplianceMetrics) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{10}
}

func (x *AMLComplianceMetrics) GetCtrFilingRate() float64 {
	if x != nil {
		return x.CtrFilingRate
	}
	return 0
}

func (x *AMLComplianceMetrics) GetSarFilingRate() float64 {
	if x != nil {
		return x.SarFilingRate
	}
	return 0
}

func (x *AMLComplianceMetrics) GetFalsePositiveRate() float64 {
	if x != nil {
		return x.FalsePositiveRate
	}
	return 0
}

func (x *AMLComplianceMetrics) GetAvgResolutionTimeHours() int32 {
	if x != nil {
		return x.AvgResolutionTimeHours
	}
	return 0
}

func (x *AMLComplianceMetrics) GetComplianceScore() int32 {
	if x != nil {
		return x.ComplianceScore
	}
	return 0
}

// AMLTrendAnalysis
type AMLTrendAnalysis struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AlertTrend_30Days  []int32                `protobuf:"varint,1,rep,packed,name=alert_trend_30_days,json=alertTrend30Days,proto3" json:"alert_trend_30_days,omitempty"`
	VolumeTrend_30Days []int64                `protobuf:"varint,2,rep,packed,name=volume_trend_30_days,json=volumeTrend30Days,proto3" json:"volume_trend_30_days,omitempty"`
	RiskScoreTrend     []float64              `protobuf:"fixed64,3,rep,packed,name=risk_score_trend,json=riskScoreTrend,proto3" json:"risk_score_trend,omitempty"`
	EmergingPatterns   []string               `protobuf:"bytes,4,rep,name=emerging_patterns,json=emergingPatterns,proto3" json:"emerging_patterns,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AMLTrendAnalysis) Reset() {
	*x = AMLTrendAnalysis{}
	mi := &file_proto_accounting_aml_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLTrendAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLTrendAnalysis) ProtoMessage() {}

func (x *AMLTrendAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLTrendAnalysis.ProtoReflect.Descriptor instead.
func (*AMLTrendAnalysis) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{11}
}

func (x *AMLTrendAnalysis) GetAlertTrend_30Days() []int32 {
	if x != nil {
		return x.AlertTrend_30Days
	}
	return nil
}

func (x *AMLTrendAnalysis) GetVolumeTrend_30Days() []int64 {
	if x != nil {
		return x.VolumeTrend_30Days
	}
	return nil
}

func (x *AMLTrendAnalysis) GetRiskScoreTrend() []float64 {
	if x != nil {
		return x.RiskScoreTrend
	}
	return nil
}

func (x *AMLTrendAnalysis) GetEmergingPatterns() []string {
	if x != nil {
		return x.EmergingPatterns
	}
	return nil
}

// AMLRecommendation
type AMLRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      string                 `protobuf:"bytes,1,opt,name=priority,proto3" json:"priority,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ActionItems   []string               `protobuf:"bytes,5,rep,name=action_items,json=actionItems,proto3" json:"action_items,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMLRecommendation) Reset() {
	*x = AMLRecommendation{}
	mi := &file_proto_accounting_aml_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLRecommendation) ProtoMessage() {}

func (x *AMLRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLRecommendation.ProtoReflect.Descriptor instead.
func (*AMLRecommendation) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{12}
}

func (x *AMLRecommendation) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *AMLRecommendation) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AMLRecommendation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AMLRecommendation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AMLRecommendation) GetActionItems() []string {
	if x != nil {
		return x.ActionItems
	}
	return nil
}

func (x *AMLRecommendation) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

// AMLDashboard
type AMLDashboard struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PeriodStart        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	TotalAlerts        int32                  `protobuf:"varint,3,opt,name=total_alerts,json=totalAlerts,proto3" json:"total_alerts,omitempty"`
	AlertsByRiskLevel  map[string]int32       `protobuf:"bytes,4,rep,name=alerts_by_risk_level,json=alertsByRiskLevel,proto3" json:"alerts_by_risk_level,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AlertsByType       map[string]int32       `protobuf:"bytes,5,rep,name=alerts_by_type,json=alertsByType,proto3" json:"alerts_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TopRiskyCustomers  []*CustomerRiskSummary `protobuf:"bytes,6,rep,name=top_risky_customers,json=topRiskyCustomers,proto3" json:"top_risky_customers,omitempty"`
	ComplianceMetrics  *AMLComplianceMetrics  `protobuf:"bytes,7,opt,name=compliance_metrics,json=complianceMetrics,proto3" json:"compliance_metrics,omitempty"`
	TrendAnalysis      *AMLTrendAnalysis      `protobuf:"bytes,8,opt,name=trend_analysis,json=trendAnalysis,proto3" json:"trend_analysis,omitempty"`
	RecommendedActions []*AMLRecommendation   `protobuf:"bytes,9,rep,name=recommended_actions,json=recommendedActions,proto3" json:"recommended_actions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AMLDashboard) Reset() {
	*x = AMLDashboard{}
	mi := &file_proto_accounting_aml_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLDashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLDashboard) ProtoMessage() {}

func (x *AMLDashboard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_aml_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLDashboard.ProtoReflect.Descriptor instead.
func (*AMLDashboard) Descriptor() ([]byte, []int) {
	return file_proto_accounting_aml_proto_rawDescGZIP(), []int{13}
}

func (x *AMLDashboard) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *AMLDashboard) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *AMLDashboard) GetTotalAlerts() int32 {
	if x != nil {
		return x.TotalAlerts
	}
	return 0
}

func (x *AMLDashboard) GetAlertsByRiskLevel() map[string]int32 {
	if x != nil {
		return x.AlertsByRiskLevel
	}
	return nil
}

func (x *AMLDashboard) GetAlertsByType() map[string]int32 {
	if x != nil {
		return x.AlertsByType
	}
	return nil
}

func (x *AMLDashboard) GetTopRiskyCustomers() []*CustomerRiskSummary {
	if x != nil {
		return x.TopRiskyCustomers
	}
	return nil
}

func (x *AMLDashboard) GetComplianceMetrics() *AMLComplianceMetrics {
	if x != nil {
		return x.ComplianceMetrics
	}
	return nil
}

func (x *AMLDashboard) GetTrendAnalysis() *AMLTrendAnalysis {
	if x != nil {
		return x.TrendAnalysis
	}
	return nil
}

func (x *AMLDashboard) GetRecommendedActions() []*AMLRecommendation {
	if x != nil {
		return x.RecommendedActions
	}
	return nil
}

var File_proto_accounting_aml_proto protoreflect.FileDescriptor

const file_proto_accounting_aml_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/accounting/aml.proto\x12\n" +
	"accounting\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!proto/accounting/accounting.proto\"\xc5\x01\n" +
	"\x13InvestigationAction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\btaken_by\x18\x04 \x01(\tR\atakenBy\x125\n" +
	"\btaken_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\"\x97\x01\n" +
	"\x11InvestigationNote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9b\x03\n" +
	"\x10AMLInvestigation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\balert_id\x18\x02 \x01(\tR\aalertId\x12\"\n" +
	"\finvestigator\x18\x03 \x01(\tR\finvestigator\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\a \x01(\tR\bpriority\x12\x1a\n" +
	"\bfindings\x18\b \x03(\tR\bfindings\x129\n" +
	"\aactions\x18\t \x03(\v2\x1f.accounting.InvestigationActionR\aactions\x123\n" +
	"\x05notes\x18\n" +
	" \x03(\v2\x1d.accounting.InvestigationNoteR\x05notes\"\xd9\x01\n" +
	"\vAMLEvidence\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"value_json\x18\x03 \x01(\tR\tvalueJson\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12=\n" +
	"\fcollected_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\"\x8e\x02\n" +
	"\x0eAMLDisposition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"decided_by\x18\x04 \x01(\tR\tdecidedBy\x129\n" +
	"\n" +
	"decided_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAt\x12\x1c\n" +
	"\trationale\x18\x06 \x01(\tR\trationale\x12\x1d\n" +
	"\n" +
	"sar_number\x18\a \x01(\tR\tsarNumber\x12\x1f\n" +
	"\vreported_to\x18\b \x03(\tR\n" +
	"reportedTo\"\xee\x06\n" +
	"\bAMLAlert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\trule_type\x18\x02 \x01(\x0e2\x17.accounting.AMLRuleTypeR\bruleType\x126\n" +
	"\tframework\x18\x03 \x01(\x0e2\x18.accounting.AMLFrameworkR\tframework\x127\n" +
	"\n" +
	"risk_level\x18\x04 \x01(\x0e2\x18.accounting.AMLRiskLevelR\triskLevel\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1b\n" +
	"\tentity_id\x18\a \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\b \x01(\tR\n" +
	"entityType\x12'\n" +
	"\x0ftransaction_ids\x18\t \x03(\tR\x0etransactionIds\x12\x1f\n" +
	"\vaccount_ids\x18\n" +
	" \x03(\tR\n" +
	"accountIds\x12*\n" +
	"\x06amount\x18\v \x01(\v2\x12.accounting.AmountR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\f \x01(\tR\bcurrency\x12;\n" +
	"\vdetected_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x1f\n" +
	"\vassigned_to\x18\x0f \x01(\tR\n" +
	"assignedTo\x12B\n" +
	"\rinvestigation\x18\x10 \x01(\v2\x1c.accounting.AMLInvestigationR\rinvestigation\x123\n" +
	"\bevidence\x18\x11 \x03(\v2\x17.accounting.AMLEvidenceR\bevidence\x12>\n" +
	"\fdispositions\x18\x12 \x03(\v2\x1a.accounting.AMLDispositionR\fdispositions\x129\n" +
	"\n" +
	"created_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd3\x05\n" +
	"\aAMLRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.accounting.AMLRuleTypeR\x04type\x126\n" +
	"\tframework\x18\x04 \x01(\x0e2\x18.accounting.AMLFrameworkR\tframework\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12C\n" +
	"\n" +
	"thresholds\x18\a \x03(\v2#.accounting.AMLRule.ThresholdsEntryR\n" +
	"thresholds\x12G\n" +
	"\ftime_windows\x18\b \x03(\v2$.accounting.AMLRule.TimeWindowsEntryR\vtimeWindows\x12\x1e\n" +
	"\n" +
	"currencies\x18\t \x03(\tR\n" +
	"currencies\x12\x1c\n" +
	"\tcountries\x18\n" +
	" \x03(\tR\tcountries\x12\x1d\n" +
	"\n" +
	"base_score\x18\v \x01(\x05R\tbaseScore\x12#\n" +
	"\rrisk_multiple\x18\f \x01(\x01R\friskMultiple\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a=\n" +
	"\x0fThresholdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10TimeWindowsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xf4\x05\n" +
	"\vAMLCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x127\n" +
	"\n" +
	"risk_level\x18\x05 \x01(\x0e2\x18.accounting.AMLRiskLevelR\triskLevel\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x15\n" +
	"\x06is_pep\x18\a \x01(\bR\x05isPep\x12 \n" +
	"\fis_high_risk\x18\b \x01(\bR\n" +
	"isHighRisk\x12'\n" +
	"\x0fsanctions_match\x18\t \x01(\bR\x0esanctionsMatch\x12>\n" +
	"\rlast_kyc_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vlastKycDate\x12>\n" +
	"\rlast_cdd_date\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlastCddDate\x12D\n" +
	"\x10next_review_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0enextReviewDate\x12C\n" +
	"\x0fonboarding_date\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x0eonboardingDate\x12+\n" +
	"\x11expected_activity\x18\x0e \x01(\tR\x10expectedActivity\x12)\n" +
	"\x10business_purpose\x18\x0f \x01(\tR\x0fbusinessPurpose\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf4\x03\n" +
	"\x0eAMLTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12*\n" +
	"\x06amount\x18\x02 \x01(\v2\x12.accounting.AmountR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12.\n" +
	"\x04date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12(\n" +
	"\x10from_customer_id\x18\x05 \x01(\tR\x0efromCustomerId\x12$\n" +
	"\x0eto_customer_id\x18\x06 \x01(\tR\ftoCustomerId\x12!\n" +
	"\ffrom_country\x18\a \x01(\tR\vfromCountry\x12\x1d\n" +
	"\n" +
	"to_country\x18\b \x01(\tR\ttoCountry\x12\x18\n" +
	"\apurpose\x18\t \x01(\tR\apurpose\x12\x18\n" +
	"\achannel\x18\n" +
	" \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"risk_score\x18\v \x01(\x05R\triskScore\x12#\n" +
	"\ris_structured\x18\f \x01(\bR\fisStructured\x12#\n" +
	"\ris_suspicious\x18\r \x01(\bR\fisSuspicious\x12\x14\n" +
	"\x05flags\x18\x0e \x03(\tR\x05flags\"\xa2\x02\n" +
	"\x13CustomerRiskSummary\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rcustomer_name\x18\x02 \x01(\tR\fcustomerName\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x05R\triskScore\x12\x1f\n" +
	"\valert_count\x18\x04 \x01(\x05R\n" +
	"alertCount\x12!\n" +
	"\ftotal_volume\x18\x05 \x01(\x03R\vtotalVolume\x12?\n" +
	"\rlast_activity\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\x12!\n" +
	"\frisk_factors\x18\a \x03(\tR\vriskFactors\"\xfc\x01\n" +
	"\x14AMLComplianceMetrics\x12&\n" +
	"\x0fctr_filing_rate\x18\x01 \x01(\x01R\rctrFilingRate\x12&\n" +
	"\x0fsar_filing_rate\x18\x02 \x01(\x01R\rsarFilingRate\x12.\n" +
	"\x13false_positive_rate\x18\x03 \x01(\x01R\x11falsePositiveRate\x129\n" +
	"\x19avg_resolution_time_hours\x18\x04 \x01(\x05R\x16avgResolutionTimeHours\x12)\n" +
	"\x10compliance_score\x18\x05 \x01(\x05R\x0fcomplianceScore\"\xc9\x01\n" +
	"\x10AMLTrendAnalysis\x12-\n" +
	"\x13alert_trend_30_days\x18\x01 \x03(\x05R\x10alertTrend30Days\x12/\n" +
	"\x14volume_trend_30_days\x18\x02 \x03(\x03R\x11volumeTrend30Days\x12(\n" +
	"\x10risk_score_trend\x18\x03 \x03(\x01R\x0eriskScoreTrend\x12+\n" +
	"\x11emerging_patterns\x18\x04 \x03(\tR\x10emergingPatterns\"\xdd\x01\n" +
	"\x11AMLRecommendation\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\tR\bpriority\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\faction_items\x18\x05 \x03(\tR\vactionItems\x125\n" +
	"\bdue_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\"\x9d\x06\n" +
	"\fAMLDashboard\x12=\n" +
	"\fperiod_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12!\n" +
	"\ftotal_alerts\x18\x03 \x01(\x05R\vtotalAlerts\x12`\n" +
	"\x14alerts_by_risk_level\x18\x04 \x03(\v2/.accounting.AMLDashboard.AlertsByRiskLevelEntryR\x11alertsByRiskLevel\x12P\n" +
	"\x0ealerts_by_type\x18\x05 \x03(\v2*.accounting.AMLDashboard.AlertsByTypeEntryR\falertsByType\x12O\n" +
	"\x13top_risky_customers\x18\x06 \x03(\v2\x1f.accounting.CustomerRiskSummaryR\x11topRiskyCustomers\x12O\n" +
	"\x12compliance_metrics\x18\a \x01(\v2 .accounting.AMLComplianceMetricsR\x11complianceMetrics\x12C\n" +
	"\x0etrend_analysis\x18\b \x01(\v2\x1c.accounting.AMLTrendAnalysisR\rtrendAnalysis\x12N\n" +
	"\x13recommended_actions\x18\t \x03(\v2\x1d.accounting.AMLRecommendationR\x12recommendedActions\x1aD\n" +
	"\x16AlertsByRiskLevelEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11AlertsByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01*\xa6\x01\n" +
	"\fAMLFramework\x12\x1d\n" +
	"\x19AML_FRAMEWORK_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AML_FRAMEWORK_BSA\x10\x01\x12\x16\n" +
	"\x12AML_FRAMEWORK_AMLD\x10\x02\x12\x16\n" +
	"\x12AML_FRAMEWORK_FATF\x10\x03\x12\x18\n" +
	"\x14AML_FRAMEWORK_FINCEN\x10\x04\x12\x16\n" +
	"\x12AML_FRAMEWORK_OFAC\x10\x05*\x97\x01\n" +
	"\fAMLRiskLevel\x12\x1e\n" +
	"\x1aAML_RISK_LEVEL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12AML_RISK_LEVEL_LOW\x10\x01\x12\x19\n" +
	"\x15AML_RISK_LEVEL_MEDIUM\x10\x02\x12\x17\n" +
	"\x13AML_RISK_LEVEL_HIGH\x10\x03\x12\x1b\n" +
	"\x17AML_RISK_LEVEL_CRITICAL\x10\x04*\xec\b\n" +
	"\vAMLRuleType\x12\x1d\n" +
	"\x19AML_RULE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AML_RULE_TYPE_CTR\x10\x01\x12\x15\n" +
	"\x11AML_RULE_TYPE_SAR\x10\x02\x12\x1d\n" +
	"\x19AML_RULE_TYPE_STRUCTURING\x10\x03\x12\x1a\n" +
	"\x16AML_RULE_TYPE_SMURFING\x10\x04\x12\x1a\n" +
	"\x16AML_RULE_TYPE_LAYERING\x10\x05\x12 \n" +
	"\x1cAML_RULE_TYPE_RAPID_MOVEMENT\x10\x06\x12\x1f\n" +
	"\x1bAML_RULE_TYPE_ROUND_AMOUNTS\x10\a\x12\x15\n" +
	"\x11AML_RULE_TYPE_KYC\x10\b\x12\x15\n" +
	"\x11AML_RULE_TYPE_CDD\x10\t\x12\x15\n" +
	"\x11AML_RULE_TYPE_EDD\x10\n" +
	"\x12\x15\n" +
	"\x11AML_RULE_TYPE_PEP\x10\v\x12\x1b\n" +
	"\x17AML_RULE_TYPE_SANCTIONS\x10\f\x12(\n" +
	"$AML_RULE_TYPE_HIGH_RISK_JURISDICTION\x10\r\x12\x16\n" +
	"\x12AML_RULE_TYPE_NCCT\x10\x0e\x12\x1a\n" +
	"\x16AML_RULE_TYPE_VELOCITY\x10\x0f\x12\x1b\n" +
	"\x17AML_RULE_TYPE_FREQUENCY\x10\x10\x12\x1f\n" +
	"\x1bAML_RULE_TYPE_CONCENTRATION\x10\x11\x12 \n" +
	"\x1cAML_RULE_TYPE_UNUSUAL_TIMING\x10\x12\x12$\n" +
	" AML_RULE_TYPE_CIRCULAR_TRANSFERS\x10\x13\x12 \n" +
	"\x1cAML_RULE_TYPE_CASH_INTENSIVE\x10\x14\x12$\n" +
	" AML_RULE_TYPE_HIGH_RISK_PRODUCTS\x10\x15\x12\"\n" +
	"\x1eAML_RULE_TYPE_ACCOUNT_DORMANCY\x10\x16\x12'\n" +
	"#AML_RULE_TYPE_IDENTITY_VERIFICATION\x10\x17\x12!\n" +
	"\x1dAML_RULE_TYPE_SOURCE_OF_FUNDS\x10\x18\x12 \n" +
	"\x1cAML_RULE_TYPE_WIRE_STRIPPING\x10\x19\x12#\n" +
	"\x1fAML_RULE_TYPE_THIRD_PARTY_CHECK\x10\x1a\x12 \n" +
	"\x1cAML_RULE_TYPE_NEGATIVE_MEDIA\x10\x1b\x12\"\n" +
	"\x1eAML_RULE_TYPE_ACCOUNT_TAKEOVER\x10\x1c\x12 \n" +
	"\x1cAML_RULE_TYPE_TRADE_BASED_ML\x10\x1d\x12\x1f\n" +
	"\x1bAML_RULE_TYPE_SHELL_COMPANY\x10\x1e\x12\x1f\n" +
	"\x1bAML_RULE_TYPE_PREPAID_CARDS\x10\x1f\x12 \n" +
	"\x1cAML_RULE_TYPE_CRYPTOCURRENCY\x10 \x12&\n" +
	"\"AML_RULE_TYPE_JUST_UNDER_THRESHOLD\x10!\x12&\n" +
	"\"AML_RULE_TYPE_UNEXPECTED_GEOGRAPHY\x10\"B\x1dZ\x1baccounting/proto/accountingb\x06proto3"

var (
	file_proto_accounting_aml_proto_rawDescOnce sync.Once
	file_proto_accounting_aml_proto_rawDescData []byte
)

func file_proto_accounting_aml_proto_rawDescGZIP() []byte {
	file_proto_accounting_aml_proto_rawDescOnce.Do(func() {
		file_proto_accounting_aml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accounting_aml_proto_rawDesc), len(file_proto_accounting_aml_proto_rawDesc)))
	})
	return file_proto_accounting_aml_proto_rawDescData
}

var file_proto_accounting_aml_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_accounting_aml_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_accounting_aml_proto_goTypes = []any{
	(AMLFramework)(0),             // 0: accounting.AMLFramework
	(AMLRiskLevel)(0),             // 1: accounting.AMLRiskLevel
	(AMLRuleType)(0),              // 2: accounting.AMLRuleType
	(*InvestigationAction)(nil),   // 3: accounting.InvestigationAction
	(*InvestigationNote)(nil),     // 4: accounting.InvestigationNote
	(*AMLInvestigation)(nil),      // 5: accounting.AMLInvestigation
	(*AMLEvidence)(nil),           // 6: accounting.AMLEvidence
	(*AMLDisposition)(nil),        // 7: accounting.AMLDisposition
	(*AMLAlert)(nil),              // 8: accounting.AMLAlert
	(*AMLRule)(nil),               // 9: accounting.AMLRule
	(*AMLCustomer)(nil),           // 10: accounting.AMLCustomer
	(*AMLTransaction)(nil),        // 11: accounting.AMLTransaction
	(*CustomerRiskSummary)(nil),   // 12: accounting.CustomerRiskSummary
	(*AMLComplianceMetrics)(nil),  // 13: accounting.AMLComplianceMetrics
	(*AMLTrendAnalysis)(nil),      // 14: accounting.AMLTrendAnalysis
	(*AMLRecommendation)(nil),     // 15: accounting.AMLRecommendation
	(*AMLDashboard)(nil),          // 16: accounting.AMLDashboard
	nil,                           // 17: accounting.AMLRule.ThresholdsEntry
	nil,                           // 18: accounting.AMLRule.TimeWindowsEntry
	nil,                           // 19: accounting.AMLDashboard.AlertsByRiskLevelEntry
	nil,                           // 20: accounting.AMLDashboard.AlertsByTypeEntry
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
	(*Amount)(nil),                // 22: accounting.Amount
}
var file_proto_accounting_aml_proto_depIdxs = []int32{
	21, // 0: accounting.InvestigationAction.taken_at:type_name -> google.protobuf.Timestamp
	21, // 1: accounting.InvestigationNote.created_at:type_name -> google.protobuf.Timestamp
	21, // 2: accounting.AMLInvestigation.started_at:type_name -> google.protobuf.Timestamp
	21, // 3: accounting.AMLInvestigation.completed_at:type_name -> google.protobuf.Timestamp
	3,  // 4: accounting.AMLInvestigation.actions:type_name -> accounting.InvestigationAction
	4,  // 5: accounting.AMLInvestigation.notes:type_name -> accounting.InvestigationNote
	21, // 6: accounting.AMLEvidence.collected_at:type_name -> google.protobuf.Timestamp
	21, // 7: accounting.AMLDisposition.decided_at:type_name -> google.protobuf.Timestamp
	2,  // 8: accounting.AMLAlert.rule_type:type_name -> accounting.AMLRuleType
	0,  // 9: accounting.AMLAlert.framework:type_name -> accounting.AMLFramework
	1,  // 10: accounting.AMLAlert.risk_level:type_name -> accounting.AMLRiskLevel
	22, // 11: accounting.AMLAlert.amount:type_name -> accounting.Amount
	21, // 12: accounting.AMLAlert.detected_at:type_name -> google.protobuf.Timestamp
	5,  // 13: accounting.AMLAlert.investigation:type_name -> accounting.AMLInvestigation
	6,  // 14: accounting.AMLAlert.evidence:type_name -> accounting.AMLEvidence
	7,  // 15: accounting.AMLAlert.dispositions:type_name -> accounting.AMLDisposition
	21, // 16: accounting.AMLAlert.created_at:type_name -> google.protobuf.Timestamp
	21, // 17: accounting.AMLAlert.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 18: accounting.AMLRule.type:type_name -> accounting.AMLRuleType
	0,  // 19: accounting.AMLRule.framework:type_name -> accounting.AMLFramework
	17, // 20: accounting.AMLRule.thresholds:type_name -> accounting.AMLRule.ThresholdsEntry
	18, // 21: accounting.AMLRule.time_windows:type_name -> accounting.AMLRule.TimeWindowsEntry
	21, // 22: accounting.AMLRule.created_at:type_name -> google.protobuf.Timestamp
	21, // 23: accounting.AMLRule.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 24: accounting.AMLCustomer.risk_level:type_name -> accounting.AMLRiskLevel
	21, // 25: accounting.AMLCustomer.last_kyc_date:type_name -> google.protobuf.Timestamp
	21, // 26: accounting.AMLCustomer.last_cdd_date:type_name -> google.protobuf.Timestamp
	21, // 27: accounting.AMLCustomer.next_review_date:type_name -> google.protobuf.Timestamp
	21, // 28: accounting.AMLCustomer.onboarding_date:type_name -> google.protobuf.Timestamp
	21, // 29: accounting.AMLCustomer.created_at:type_name -> google.protobuf.Timestamp
	21, // 30: accounting.AMLCustomer.updated_at:type_name -> google.protobuf.Timestamp
	22, // 31: accounting.AMLTransaction.amount:type_name -> accounting.Amount
	21, // 32: accounting.AMLTransaction.date:type_name -> google.protobuf.Timestamp
	21, // 33: accounting.CustomerRiskSummary.last_activity:type_name -> google.protobuf.Timestamp
	21, // 34: accounting.AMLRecommendation.due_date:type_name -> google.protobuf.Timestamp
	21, // 35: accounting.AMLDashboard.period_start:type_name -> google.protobuf.Timestamp
	21, // 36: accounting.AMLDashboard.period_end:type_name -> google.protobuf.Timestamp
	19, // 37: accounting.AMLDashboard.alerts_by_risk_level:type_name -> accounting.AMLDashboard.AlertsByRiskLevelEntry
	20, // 38: accounting.AMLDashboard.alerts_by_type:type_name -> accounting.AMLDashboard.AlertsByTypeEntry
	12, // 39: accounting.AMLDashboard.top_risky_customers:type_name -> accounting.CustomerRiskSummary
	13, // 40: accounting.AMLDashboard.compliance_metrics:type_name -> accounting.AMLComplianceMetrics
	14, // 41: accounting.AMLDashboard.trend_analysis:type_name -> accounting.AMLTrendAnalysis
	15, // 42: accounting.AMLDashboard.recommended_actions:type_name -> accounting.AMLRecommendation
	43, // [43:43] is the sub-list for method output_type
	43, // [43:43] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_proto_accounting_aml_proto_init() }
func file_proto_accounting_aml_proto_init() {
	if File_proto_accounting_aml_proto != nil {
		return
	}
	file_proto_accounting_accounting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accounting_aml_proto_rawDesc), len(file_proto_accounting_aml_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_accounting_aml_proto_goTypes,
		DependencyIndexes: file_proto_accounting_aml_proto_depIdxs,
		EnumInfos:         file_proto_accounting_aml_proto_enumTypes,
		MessageInfos:      file_proto_accounting_aml_proto_msgTypes,
	}.Build()
	File_proto_accounting_aml_proto = out.File
	file_proto_accounting_aml_proto_goTypes = nil
	file_proto_accounting_aml_proto_depIdxs = nil
}
