// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/accounting/compliance.proto

package accounting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ComplianceFramework enum
type ComplianceFramework int32

const (
	ComplianceFramework_COMPLIANCE_FRAMEWORK_UNSPECIFIED ComplianceFramework = 0
	ComplianceFramework_COMPLIANCE_FRAMEWORK_GAAP        ComplianceFramework = 1
	ComplianceFramework_COMPLIANCE_FRAMEWORK_IFRS        ComplianceFramework = 2
	ComplianceFramework_COMPLIANCE_FRAMEWORK_SOX         ComplianceFramework = 3
)

// Enum value maps for ComplianceFramework.
var (
	ComplianceFramework_name = map[int32]string{
		0: "COMPLIANCE_FRAMEWORK_UNSPECIFIED",
		1: "COMPLIANCE_FRAMEWORK_GAAP",
		2: "COMPLIANCE_FRAMEWORK_IFRS",
		3: "COMPLIANCE_FRAMEWORK_SOX",
	}
	ComplianceFramework_value = map[string]int32{
		"COMPLIANCE_FRAMEWORK_UNSPECIFIED": 0,
		"COMPLIANCE_FRAMEWORK_GAAP":        1,
		"COMPLIANCE_FRAMEWORK_IFRS":        2,
		"COMPLIANCE_FRAMEWORK_SOX":         3,
	}
)

func (x ComplianceFramework) Enum() *ComplianceFramework {
	p := new(ComplianceFramework)
	*p = x
	return p
}

func (x ComplianceFramework) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComplianceFramework) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_compliance_proto_enumTypes[0].Descriptor()
}

func (ComplianceFramework) Type() protoreflect.EnumType {
	return &file_proto_accounting_compliance_proto_enumTypes[0]
}

func (x ComplianceFramework) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComplianceFramework.Descriptor instead.
func (ComplianceFramework) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_compliance_proto_rawDescGZIP(), []int{0}
}

// TaxJurisdiction enum
type TaxJurisdiction int32

const (
	TaxJurisdiction_TAX_JURISDICTION_UNSPECIFIED TaxJurisdiction = 0
	TaxJurisdiction_TAX_JURISDICTION_US_FEDERAL  TaxJurisdiction = 1
	TaxJurisdiction_TAX_JURISDICTION_US_STATE    TaxJurisdiction = 2
	TaxJurisdiction_TAX_JURISDICTION_EU_VAT      TaxJurisdiction = 3
	TaxJurisdiction_TAX_JURISDICTION_UK_VAT      TaxJurisdiction = 4
	TaxJurisdiction_TAX_JURISDICTION_CANADA_GST  TaxJurisdiction = 5
	TaxJurisdiction_TAX_JURISDICTION_AUSTRALIA   TaxJurisdiction = 6
)

// Enum value maps for TaxJurisdiction.
var (
	TaxJurisdiction_name = map[int32]string{
		0: "TAX_JURISDICTION_UNSPECIFIED",
		1: "TAX_JURISDICTION_US_FEDERAL",
		2: "TAX_JURISDICTION_US_STATE",
		3: "TAX_JURISDICTION_EU_VAT",
		4: "TAX_JURISDICTION_UK_VAT",
		5: "TAX_JURISDICTION_CANADA_GST",
		6: "TAX_JURISDICTION_AUSTRALIA",
	}
	TaxJurisdiction_value = map[string]int32{
		"TAX_JURISDICTION_UNSPECIFIED": 0,
		"TAX_JURISDICTION_US_FEDERAL":  1,
		"TAX_JURISDICTION_US_STATE":    2,
		"TAX_JURISDICTION_EU_VAT":      3,
		"TAX_JURISDICTION_UK_VAT":      4,
		"TAX_JURISDICTION_CANADA_GST":  5,
		"TAX_JURISDICTION_AUSTRALIA":   6,
	}
)

func (x TaxJurisdiction) Enum() *TaxJurisdiction {
	p := new(TaxJurisdiction)
	*p = x
	return p
}

func (x TaxJurisdiction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaxJurisdiction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_compliance_proto_enumTypes[1].Descriptor()
}

func (TaxJurisdiction) Type() protoreflect.EnumType {
	return &file_proto_accounting_compliance_proto_enumTypes[1]
}

func (x TaxJurisdiction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaxJurisdiction.Descriptor instead.
func (TaxJurisdiction) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_compliance_proto_rawDescGZIP(), []int{1}
}

// TaxType enum
type TaxType int32

const (
	TaxType_TAX_TYPE_UNSPECIFIED  TaxType = 0
	TaxType_TAX_TYPE_INCOME_TAX   TaxType = 1
	TaxType_TAX_TYPE_SALES_TAX    TaxType = 2
	TaxType_TAX_TYPE_VAT          TaxType = 3
	TaxType_TAX_TYPE_GST          TaxType = 4
	TaxType_TAX_TYPE_PAYROLL_TAX  TaxType = 5
	TaxType_TAX_TYPE_PROPERTY_TAX TaxType = 6
	TaxType_TAX_TYPE_WITHHOLDING  TaxType = 7
)

// Enum value maps for TaxType.
var (
	TaxType_name = map[int32]string{
		0: "TAX_TYPE_UNSPECIFIED",
		1: "TAX_TYPE_INCOME_TAX",
		2: "TAX_TYPE_SALES_TAX",
		3: "TAX_TYPE_VAT",
		4: "TAX_TYPE_GST",
		5: "TAX_TYPE_PAYROLL_TAX",
		6: "TAX_TYPE_PROPERTY_TAX",
		7: "TAX_TYPE_WITHHOLDING",
	}
	TaxType_value = map[string]int32{
		"TAX_TYPE_UNSPECIFIED":  0,
		"TAX_TYPE_INCOME_TAX":   1,
		"TAX_TYPE_SALES_TAX":    2,
		"TAX_TYPE_VAT":          3,
		"TAX_TYPE_GST":          4,
		"TAX_TYPE_PAYROLL_TAX":  5,
		"TAX_TYPE_PROPERTY_TAX": 6,
		"TAX_TYPE_WITHHOLDING":  7,
	}
)

func (x TaxType) Enum() *TaxType {
	p := new(TaxType)
	*p = x
	return p
}

func (x TaxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaxType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_compliance_proto_enumTypes[2].Descriptor()
}

func (TaxType) Type() protoreflect.EnumType {
	return &file_proto_accounting_compliance_proto_enumTypes[2]
}

func (x TaxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaxType.Descriptor instead.
func (TaxType) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_compliance_proto_rawDescGZIP(), []int{2}
}

// ComplianceRule
type ComplianceRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Framework     ComplianceFramework    `protobuf:"varint,2,opt,name=framework,proto3,enum=accounting.ComplianceFramework" json:"framework,omitempty"`
	RuleType      string                 `protobuf:"bytes,3,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AccountType   AccountType            `protobuf:"varint,5,opt,name=account_type,json=accountType,proto3,enum=accounting.AccountType" json:"account_type,omitempty"`
	Conditions    []string               `protobuf:"bytes,6,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Actions       []string               `protobuf:"bytes,7,rep,name=actions,proto3" json:"actions,omitempty"`
	Severity      string                 `protobuf:"bytes,8,opt,name=severity,proto3" json:"severity,omitempty"`
	Active        bool                   `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplianceRule) Reset() {
	*x = ComplianceRule{}
	mi := &file_proto_accounting_compliance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceRule) ProtoMessage() {}

func (x *ComplianceRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_compliance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceRule.ProtoReflect.Descriptor instead.
func (*ComplianceRule) Descriptor() ([]byte, []int) {
	return file_proto_accounting_compliance_proto_rawDescGZIP(), []int{0}
}

func (x *ComplianceRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComplianceRule) GetFramework() ComplianceFramework {
	if x != nil {
		return x.Framework
	}
	return ComplianceFramework_COMPLIANCE_FRAMEWORK_UNSPECIFIED
}

func (x *ComplianceRule) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *ComplianceRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ComplianceRule) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *ComplianceRule) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *ComplianceRule) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ComplianceRule) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ComplianceRule) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ComplianceRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// TaxRule
type TaxRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Jurisdiction  TaxJurisdiction        `protobuf:"varint,2,opt,name=jurisdiction,proto3,enum=accounting.TaxJurisdiction" json:"jurisdiction,omitempty"`
	TaxType       TaxType                `protobuf:"varint,3,opt,name=tax_type,json=taxType,proto3,enum=accounting.TaxType" json:"tax_type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Rate          float64                `protobuf:"fixed64,5,opt,name=rate,proto3" json:"rate,omitempty"`
	MinAmount     float64                `protobuf:"fixed64,6,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount     float64                `protobuf:"fixed64,7,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	Exemptions    []string               `protobuf:"bytes,8,rep,name=exemptions,proto3" json:"exemptions,omitempty"`
	EffectiveFrom *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`
	EffectiveTo   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=effective_to,json=effectiveTo,proto3" json:"effective_to,omitempty"`
	Active        bool                   `protobuf:"varint,11,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaxRule) Reset() {
	*x = TaxRule{}
	mi := &file_proto_accounting_compliance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaxRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaxRule) ProtoMessage() {}

func (x *TaxRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_compliance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaxRule.ProtoReflect.Descriptor instead.
func (*TaxRule) Descriptor() ([]byte, []int) {
	return file_proto_accounting_compliance_proto_rawDescGZIP(), []int{1}
}

func (x *TaxRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaxRule) GetJurisdiction() TaxJurisdiction {
	if x != nil {
		return x.Jurisdiction
	}
	return TaxJurisdiction_TAX_JURISDICTION_UNSPECIFIED
}

func (x *TaxRule) GetTaxType() TaxType {
	if x != nil {
		return x.TaxType
	}
	return TaxType_TAX_TYPE_UNSPECIFIED
}

func (x *TaxRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaxRule) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *TaxRule) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *TaxRule) GetMaxAmount() float64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *TaxRule) GetExemptions() []string {
	if x != nil {
		return x.Exemptions
	}
	return nil
}

func (x *TaxRule) GetEffectiveFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveFrom
	}
	return nil
}

func (x *TaxRule) GetEffectiveTo() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveTo
	}
	return nil
}

func (x *TaxRule) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// TaxCalculation
type TaxCalculation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	BaseAmount    float64                `protobuf:"fixed64,2,opt,name=base_amount,json=baseAmount,proto3" json:"base_amount,omitempty"`
	TaxableAmount float64                `protobuf:"fixed64,3,opt,name=taxable_amount,json=taxableAmount,proto3" json:"taxable_amount,omitempty"`
	TaxRate       float64                `protobuf:"fixed64,4,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	TaxAmount     float64                `protobuf:"fixed64,5,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	Exemptions    []string               `protobuf:"bytes,6,rep,name=exemptions,proto3" json:"exemptions,omitempty"`
	CalculatedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=calculated_at,json=calculatedAt,proto3" json:"calculated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaxCalculation) Reset() {
	*x = TaxCalculation{}
	mi := &file_proto_accounting_compliance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaxCalculation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaxCalculation) ProtoMessage() {}

func (x *TaxCalculation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_compliance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaxCalculation.ProtoReflect.Descriptor instead.
func (*TaxCalculation) Descriptor() ([]byte, []int) {
	return file_proto_accounting_compliance_proto_rawDescGZIP(), []int{2}
}

func (x *TaxCalculation) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *TaxCalculation) GetBaseAmount() float64 {
	if x != nil {
		return x.BaseAmount
	}
	return 0
}

func (x *TaxCalculation) GetTaxableAmount() float64 {
	if x != nil {
		return x.TaxableAmount
	}
	return 0
}

func (x *TaxCalculation) GetTaxRate() float64 {
	if x != nil {
		return x.TaxRate
	}
	return 0
}

func (x *TaxCalculation) GetTaxAmount() float64 {
	if x != nil {
		return x.TaxAmount
	}
	return 0
}

func (x *TaxCalculation) GetExemptions() []string {
	if x != nil {
		return x.Exemptions
	}
	return nil
}

func (x *TaxCalculation) GetCalculatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CalculatedAt
	}
	return nil
}

// ComplianceViolation
type ComplianceViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Severity      string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	DetectedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	ResolvedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	Notes         string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplianceViolation) Reset() {
	*x = ComplianceViolation{}
	mi := &file_proto_accounting_compliance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceViolation) ProtoMessage() {}

func (x *ComplianceViolation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_compliance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceViolation.ProtoReflect.Descriptor instead.
func (*ComplianceViolation) Descriptor() ([]byte, []int) {
	return file_proto_accounting_compliance_proto_rawDescGZIP(), []int{3}
}

func (x *ComplianceViolation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComplianceViolation) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *ComplianceViolation) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ComplianceViolation) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ComplianceViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ComplianceViolation) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ComplianceViolation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComplianceViolation) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *ComplianceViolation) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

func (x *ComplianceViolation) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// TaxReturn
type TaxReturn struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Jurisdiction   TaxJurisdiction        `protobuf:"varint,2,opt,name=jurisdiction,proto3,enum=accounting.TaxJurisdiction" json:"jurisdiction,omitempty"`
	TaxType        TaxType                `protobuf:"varint,3,opt,name=tax_type,json=taxType,proto3,enum=accounting.TaxType" json:"tax_type,omitempty"`
	PeriodId       string                 `protobuf:"bytes,4,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	FilingDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=filing_date,json=filingDate,proto3" json:"filing_date,omitempty"`
	DueDate        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	TotalTax       float64                `protobuf:"fixed64,7,opt,name=total_tax,json=totalTax,proto3" json:"total_tax,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	FiledBy        string                 `protobuf:"bytes,9,opt,name=filed_by,json=filedBy,proto3" json:"filed_by,omitempty"`
	SupportingDocs []string               `protobuf:"bytes,10,rep,name=supporting_docs,json=supportingDocs,proto3" json:"supporting_docs,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaxReturn) Reset() {
	*x = TaxReturn{}
	mi := &file_proto_accounting_compliance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaxReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaxReturn) ProtoMessage() {}

func (x *TaxReturn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_compliance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaxReturn.ProtoReflect.Descriptor instead.
func (*TaxReturn) Descriptor() ([]byte, []int) {
	return file_proto_accounting_compliance_proto_rawDescGZIP(), []int{4}
}

func (x *TaxReturn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaxReturn) GetJurisdiction() TaxJurisdiction {
	if x != nil {
		return x.Jurisdiction
	}
	return TaxJurisdiction_TAX_JURISDICTION_UNSPECIFIED
}

func (x *TaxReturn) GetTaxType() TaxType {
	if x != nil {
		return x.TaxType
	}
	return TaxType_TAX_TYPE_UNSPECIFIED
}

func (x *TaxReturn) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *TaxReturn) GetFilingDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FilingDate
	}
	return nil
}

func (x *TaxReturn) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *TaxReturn) GetTotalTax() float64 {
	if x != nil {
		return x.TotalTax
	}
	return 0
}

func (x *TaxReturn) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaxReturn) GetFiledBy() string {
	if x != nil {
		return x.FiledBy
	}
	return ""
}

func (x *TaxReturn) GetSupportingDocs() []string {
	if x != nil {
		return x.SupportingDocs
	}
	return nil
}

func (x *TaxReturn) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaxReturn) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_accounting_compliance_proto protoreflect.FileDescriptor

const file_proto_accounting_compliance_proto_rawDesc = "" +
	"\n" +
	"!proto/accounting/compliance.proto\x12\n" +
	"accounting\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!proto/accounting/accounting.proto\"\x83\x03\n" +
	"\x0eComplianceRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\tframework\x18\x02 \x01(\x0e2\x1f.accounting.ComplianceFrameworkR\tframework\x12\x1b\n" +
	"\trule_type\x18\x03 \x01(\tR\bruleType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12:\n" +
	"\faccount_type\x18\x05 \x01(\x0e2\x17.accounting.AccountTypeR\vaccountType\x12\x1e\n" +
	"\n" +
	"conditions\x18\x06 \x03(\tR\n" +
	"conditions\x12\x18\n" +
	"\aactions\x18\a \x03(\tR\aactions\x12\x1a\n" +
	"\bseverity\x18\b \x01(\tR\bseverity\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06active\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xaa\x03\n" +
	"\aTaxRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\fjurisdiction\x18\x02 \x01(\x0e2\x1b.accounting.TaxJurisdictionR\fjurisdiction\x12.\n" +
	"\btax_type\x18\x03 \x01(\x0e2\x13.accounting.TaxTypeR\ataxType\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\x01R\x04rate\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x06 \x01(\x01R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\a \x01(\x01R\tmaxAmount\x12\x1e\n" +
	"\n" +
	"exemptions\x18\b \x03(\tR\n" +
	"exemptions\x12A\n" +
	"\x0eeffective_from\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\reffectiveFrom\x12=\n" +
	"\feffective_to\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\veffectiveTo\x12\x16\n" +
	"\x06active\x18\v \x01(\bR\x06active\"\x8c\x02\n" +
	"\x0eTaxCalculation\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1f\n" +
	"\vbase_amount\x18\x02 \x01(\x01R\n" +
	"baseAmount\x12%\n" +
	"\x0etaxable_amount\x18\x03 \x01(\x01R\rtaxableAmount\x12\x19\n" +
	"\btax_rate\x18\x04 \x01(\x01R\ataxRate\x12\x1d\n" +
	"\n" +
	"tax_amount\x18\x05 \x01(\x01R\ttaxAmount\x12\x1e\n" +
	"\n" +
	"exemptions\x18\x06 \x03(\tR\n" +
	"exemptions\x12?\n" +
	"\rcalculated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fcalculatedAt\"\xea\x02\n" +
	"\x13ComplianceViolation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12;\n" +
	"\vdetected_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\x12;\n" +
	"\vresolved_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\"\x8c\x04\n" +
	"\tTaxReturn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\fjurisdiction\x18\x02 \x01(\x0e2\x1b.accounting.TaxJurisdictionR\fjurisdiction\x12.\n" +
	"\btax_type\x18\x03 \x01(\x0e2\x13.accounting.TaxTypeR\ataxType\x12\x1b\n" +
	"\tperiod_id\x18\x04 \x01(\tR\bperiodId\x12;\n" +
	"\vfiling_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"filingDate\x125\n" +
	"\bdue_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12\x1b\n" +
	"\ttotal_tax\x18\a \x01(\x01R\btotalTax\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x19\n" +
	"\bfiled_by\x18\t \x01(\tR\afiledBy\x12'\n" +
	"\x0fsupporting_docs\x18\n" +
	" \x03(\tR\x0esupportingDocs\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\x97\x01\n" +
	"\x13ComplianceFramework\x12$\n" +
	" COMPLIANCE_FRAMEWORK_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMPLIANCE_FRAMEWORK_GAAP\x10\x01\x12\x1d\n" +
	"\x19COMPLIANCE_FRAMEWORK_IFRS\x10\x02\x12\x1c\n" +
	"\x18COMPLIANCE_FRAMEWORK_SOX\x10\x03*\xee\x01\n" +
	"\x0fTaxJurisdiction\x12 \n" +
	"\x1cTAX_JURISDICTION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTAX_JURISDICTION_US_FEDERAL\x10\x01\x12\x1d\n" +
	"\x19TAX_JURISDICTION_US_STATE\x10\x02\x12\x1b\n" +
	"\x17TAX_JURISDICTION_EU_VAT\x10\x03\x12\x1b\n" +
	"\x17TAX_JURISDICTION_UK_VAT\x10\x04\x12\x1f\n" +
	"\x1bTAX_JURISDICTION_CANADA_GST\x10\x05\x12\x1e\n" +
	"\x1aTAX_JURISDICTION_AUSTRALIA\x10\x06*\xc7\x01\n" +
	"\aTaxType\x12\x18\n" +
	"\x14TAX_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TAX_TYPE_INCOME_TAX\x10\x01\x12\x16\n" +
	"\x12TAX_TYPE_SALES_TAX\x10\x02\x12\x10\n" +
	"\fTAX_TYPE_VAT\x10\x03\x12\x10\n" +
	"\fTAX_TYPE_GST\x10\x04\x12\x18\n" +
	"\x14TAX_TYPE_PAYROLL_TAX\x10\x05\x12\x19\n" +
	"\x15TAX_TYPE_PROPERTY_TAX\x10\x06\x12\x18\n" +
	"\x14TAX_TYPE_WITHHOLDING\x10\aB\x1dZ\x1baccounting/proto/accountingb\x06proto3"

var (
	file_proto_accounting_compliance_proto_rawDescOnce sync.Once
	file_proto_accounting_compliance_proto_rawDescData []byte
)

func file_proto_accounting_compliance_proto_rawDescGZIP() []byte {
	file_proto_accounting_compliance_proto_rawDescOnce.Do(func() {
		file_proto_accounting_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accounting_compliance_proto_rawDesc), len(file_proto_accounting_compliance_proto_rawDesc)))
	})
	return file_proto_accounting_compliance_proto_rawDescData
}

var file_proto_accounting_compliance_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_accounting_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_accounting_compliance_proto_goTypes = []any{
	(ComplianceFramework)(0),      // 0: accounting.ComplianceFramework
	(TaxJurisdiction)(0),          // 1: accounting.TaxJurisdiction
	(TaxType)(0),                  // 2: accounting.TaxType
	(*ComplianceRule)(nil),        // 3: accounting.ComplianceRule
	(*TaxRule)(nil),               // 4: accounting.TaxRule
	(*TaxCalculation)(nil),        // 5: accounting.TaxCalculation
	(*ComplianceViolation)(nil),   // 6: accounting.ComplianceViolation
	(*TaxReturn)(nil),             // 7: accounting.TaxReturn
	(AccountType)(0),              // 8: accounting.AccountType
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_accounting_compliance_proto_depIdxs = []int32{
	0,  // 0: accounting.ComplianceRule.framework:type_name -> accounting.ComplianceFramework
	8,  // 1: accounting.ComplianceRule.account_type:type_name -> accounting.AccountType
	9,  // 2: accounting.ComplianceRule.created_at:type_name -> google.protobuf.Timestamp
	1,  // 3: accounting.TaxRule.jurisdiction:type_name -> accounting.TaxJurisdiction
	2,  // 4: accounting.TaxRule.tax_type:type_name -> accounting.TaxType
	9,  // 5: accounting.TaxRule.effective_from:type_name -> google.protobuf.Timestamp
	9,  // 6: accounting.TaxRule.effective_to:type_name -> google.protobuf.Timestamp
	9,  // 7: accounting.TaxCalculation.calculated_at:type_name -> google.protobuf.Timestamp
	9,  // 8: accounting.ComplianceViolation.detected_at:type_name -> google.protobuf.Timestamp
	9,  // 9: accounting.ComplianceViolation.resolved_at:type_name -> google.protobuf.Timestamp
	1,  // 10: accounting.TaxReturn.jurisdiction:type_name -> accounting.TaxJurisdiction
	2,  // 11: accounting.TaxReturn.tax_type:type_name -> accounting.TaxType
	9,  // 12: accounting.TaxReturn.filing_date:type_name -> google.protobuf.Timestamp
	9,  // 13: accounting.TaxReturn.due_date:type_name -> google.protobuf.Timestamp
	9,  // 14: accounting.TaxReturn.created_at:type_name -> google.protobuf.Timestamp
	9,  // 15: accounting.TaxReturn.updated_at:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_accounting_compliance_proto_init() }
func file_proto_accounting_compliance_proto_init() {
	if File_proto_accounting_compliance_proto != nil {
		return
	}
	file_proto_accounting_accounting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accounting_compliance_proto_rawDesc), len(file_proto_accounting_compliance_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_accounting_compliance_proto_goTypes,
		DependencyIndexes: file_proto_accounting_compliance_proto_depIdxs,
		EnumInfos:         file_proto_accounting_compliance_proto_enumTypes,
		MessageInfos:      file_proto_accounting_compliance_proto_msgTypes,
	}.Build()
	File_proto_accounting_compliance_proto = out.File
	file_proto_accounting_compliance_proto_goTypes = nil
	file_proto_accounting_compliance_proto_depIdxs = nil
}
