// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/accounting/forensic.proto

package accounting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FlagType enum
type FlagType int32

const (
	FlagType_FLAG_TYPE_UNSPECIFIED          FlagType = 0
	FlagType_FLAG_TYPE_ROUND_AMOUNTS        FlagType = 1
	FlagType_FLAG_TYPE_HIGH_FREQUENCY       FlagType = 2
	FlagType_FLAG_TYPE_UNUSUAL_TIMING       FlagType = 3
	FlagType_FLAG_TYPE_COMPLEX_ROUTING      FlagType = 4
	FlagType_FLAG_TYPE_LAYERING             FlagType = 5
	FlagType_FLAG_TYPE_RAPID_MOVEMENT       FlagType = 6
	FlagType_FLAG_TYPE_STRUCTURING          FlagType = 7
	FlagType_FLAG_TYPE_CIRCULAR_TRANSFERS   FlagType = 8
	FlagType_FLAG_TYPE_DORMANT_REACTIVATION FlagType = 9
	FlagType_FLAG_TYPE_KYC_EXPIRED          FlagType = 10
	FlagType_FLAG_TYPE_SANCTIONS_MATCH      FlagType = 11
	FlagType_FLAG_TYPE_PEP_INVOLVEMENT      FlagType = 12
	FlagType_FLAG_TYPE_HIGH_RISK_COUNTRY    FlagType = 13
	FlagType_FLAG_TYPE_CASH_INTENSIVE       FlagType = 14
	FlagType_FLAG_TYPE_VELOCITY_ANOMALY     FlagType = 15
	FlagType_FLAG_TYPE_AMOUNT_THRESHOLD     FlagType = 16
	FlagType_FLAG_TYPE_SMURFING_PATTERN     FlagType = 17
)

// Enum value maps for FlagType.
var (
	FlagType_name = map[int32]string{
		0:  "FLAG_TYPE_UNSPECIFIED",
		1:  "FLAG_TYPE_ROUND_AMOUNTS",
		2:  "FLAG_TYPE_HIGH_FREQUENCY",
		3:  "FLAG_TYPE_UNUSUAL_TIMING",
		4:  "FLAG_TYPE_COMPLEX_ROUTING",
		5:  "FLAG_TYPE_LAYERING",
		6:  "FLAG_TYPE_RAPID_MOVEMENT",
		7:  "FLAG_TYPE_STRUCTURING",
		8:  "FLAG_TYPE_CIRCULAR_TRANSFERS",
		9:  "FLAG_TYPE_DORMANT_REACTIVATION",
		10: "FLAG_TYPE_KYC_EXPIRED",
		11: "FLAG_TYPE_SANCTIONS_MATCH",
		12: "FLAG_TYPE_PEP_INVOLVEMENT",
		13: "FLAG_TYPE_HIGH_RISK_COUNTRY",
		14: "FLAG_TYPE_CASH_INTENSIVE",
		15: "FLAG_TYPE_VELOCITY_ANOMALY",
		16: "FLAG_TYPE_AMOUNT_THRESHOLD",
		17: "FLAG_TYPE_SMURFING_PATTERN",
	}
	FlagType_value = map[string]int32{
		"FLAG_TYPE_UNSPECIFIED":          0,
		"FLAG_TYPE_ROUND_AMOUNTS":        1,
		"FLAG_TYPE_HIGH_FREQUENCY":       2,
		"FLAG_TYPE_UNUSUAL_TIMING":       3,
		"FLAG_TYPE_COMPLEX_ROUTING":      4,
		"FLAG_TYPE_LAYERING":             5,
		"FLAG_TYPE_RAPID_MOVEMENT":       6,
		"FLAG_TYPE_STRUCTURING":          7,
		"FLAG_TYPE_CIRCULAR_TRANSFERS":   8,
		"FLAG_TYPE_DORMANT_REACTIVATION": 9,
		"FLAG_TYPE_KYC_EXPIRED":          10,
		"FLAG_TYPE_SANCTIONS_MATCH":      11,
		"FLAG_TYPE_PEP_INVOLVEMENT":      12,
		"FLAG_TYPE_HIGH_RISK_COUNTRY":    13,
		"FLAG_TYPE_CASH_INTENSIVE":       14,
		"FLAG_TYPE_VELOCITY_ANOMALY":     15,
		"FLAG_TYPE_AMOUNT_THRESHOLD":     16,
		"FLAG_TYPE_SMURFING_PATTERN":     17,
	}
)

func (x FlagType) Enum() *FlagType {
	p := new(FlagType)
	*p = x
	return p
}

func (x FlagType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlagType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_forensic_proto_enumTypes[0].Descriptor()
}

func (FlagType) Type() protoreflect.EnumType {
	return &file_proto_accounting_forensic_proto_enumTypes[0]
}

func (x FlagType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlagType.Descriptor instead.
func (FlagType) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_forensic_proto_rawDescGZIP(), []int{0}
}

// Severity enum
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_LOW         Severity = 1
	Severity_SEVERITY_MEDIUM      Severity = 2
	Severity_SEVERITY_HIGH        Severity = 3
	Severity_SEVERITY_CRITICAL    Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_LOW",
		2: "SEVERITY_MEDIUM",
		3: "SEVERITY_HIGH",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_LOW":         1,
		"SEVERITY_MEDIUM":      2,
		"SEVERITY_HIGH":        3,
		"SEVERITY_CRITICAL":    4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_forensic_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_proto_accounting_forensic_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_forensic_proto_rawDescGZIP(), []int{1}
}

// DiscrepancyType enum
type DiscrepancyType int32

const (
	DiscrepancyType_DISCREPANCY_TYPE_UNSPECIFIED      DiscrepancyType = 0
	DiscrepancyType_DISCREPANCY_TYPE_AMOUNT_MISMATCH  DiscrepancyType = 1
	DiscrepancyType_DISCREPANCY_TYPE_MISSING_ENTRY    DiscrepancyType = 2
	DiscrepancyType_DISCREPANCY_TYPE_DUPLICATE_ENTRY  DiscrepancyType = 3
	DiscrepancyType_DISCREPANCY_TYPE_DATE_MISMATCH    DiscrepancyType = 4
	DiscrepancyType_DISCREPANCY_TYPE_ACCOUNT_MISMATCH DiscrepancyType = 5
	DiscrepancyType_DISCREPANCY_TYPE_IMBALANCE        DiscrepancyType = 6
)

// Enum value maps for DiscrepancyType.
var (
	DiscrepancyType_name = map[int32]string{
		0: "DISCREPANCY_TYPE_UNSPECIFIED",
		1: "DISCREPANCY_TYPE_AMOUNT_MISMATCH",
		2: "DISCREPANCY_TYPE_MISSING_ENTRY",
		3: "DISCREPANCY_TYPE_DUPLICATE_ENTRY",
		4: "DISCREPANCY_TYPE_DATE_MISMATCH",
		5: "DISCREPANCY_TYPE_ACCOUNT_MISMATCH",
		6: "DISCREPANCY_TYPE_IMBALANCE",
	}
	DiscrepancyType_value = map[string]int32{
		"DISCREPANCY_TYPE_UNSPECIFIED":      0,
		"DISCREPANCY_TYPE_AMOUNT_MISMATCH":  1,
		"DISCREPANCY_TYPE_MISSING_ENTRY":    2,
		"DISCREPANCY_TYPE_DUPLICATE_ENTRY":  3,
		"DISCREPANCY_TYPE_DATE_MISMATCH":    4,
		"DISCREPANCY_TYPE_ACCOUNT_MISMATCH": 5,
		"DISCREPANCY_TYPE_IMBALANCE":        6,
	}
)

func (x DiscrepancyType) Enum() *DiscrepancyType {
	p := new(DiscrepancyType)
	*p = x
	return p
}

func (x DiscrepancyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscrepancyType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_forensic_proto_enumTypes[2].Descriptor()
}

func (DiscrepancyType) Type() protoreflect.EnumType {
	return &file_proto_accounting_forensic_proto_enumTypes[2]
}

func (x DiscrepancyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscrepancyType.Descriptor instead.
func (DiscrepancyType) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_forensic_proto_rawDescGZIP(), []int{2}
}

// ForensicFlag
type ForensicFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FlagType               `protobuf:"varint,1,opt,name=type,proto3,enum=accounting.FlagType" json:"type,omitempty"`
	Severity      Severity               `protobuf:"varint,2,opt,name=severity,proto3,enum=accounting.Severity" json:"severity,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Evidence      []string               `protobuf:"bytes,4,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Triggered     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=triggered,proto3" json:"triggered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForensicFlag) Reset() {
	*x = ForensicFlag{}
	mi := &file_proto_accounting_forensic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForensicFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForensicFlag) ProtoMessage() {}

func (x *ForensicFlag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_forensic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForensicFlag.ProtoReflect.Descriptor instead.
func (*ForensicFlag) Descriptor() ([]byte, []int) {
	return file_proto_accounting_forensic_proto_rawDescGZIP(), []int{0}
}

func (x *ForensicFlag) GetType() FlagType {
	if x != nil {
		return x.Type
	}
	return FlagType_FLAG_TYPE_UNSPECIFIED
}

func (x *ForensicFlag) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *ForensicFlag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ForensicFlag) GetEvidence() []string {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *ForensicFlag) GetTriggered() *timestamppb.Timestamp {
	if x != nil {
		return x.Triggered
	}
	return nil
}

// MoneyTrailStep
type MoneyTrailStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FromAccount   string                 `protobuf:"bytes,2,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     string                 `protobuf:"bytes,3,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	Amount        *Amount                `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneyTrailStep) Reset() {
	*x = MoneyTrailStep{}
	mi := &file_proto_accounting_forensic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneyTrailStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyTrailStep) ProtoMessage() {}

func (x *MoneyTrailStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_forensic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyTrailStep.ProtoReflect.Descriptor instead.
func (*MoneyTrailStep) Descriptor() ([]byte, []int) {
	return file_proto_accounting_forensic_proto_rawDescGZIP(), []int{1}
}

func (x *MoneyTrailStep) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *MoneyTrailStep) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *MoneyTrailStep) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *MoneyTrailStep) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *MoneyTrailStep) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *MoneyTrailStep) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MoneyTrailStep) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// MoneyTrail
type MoneyTrail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartAmount   *Amount                `protobuf:"bytes,2,opt,name=start_amount,json=startAmount,proto3" json:"start_amount,omitempty"`
	EndAmount     *Amount                `protobuf:"bytes,3,opt,name=end_amount,json=endAmount,proto3" json:"end_amount,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Path          []*MoneyTrailStep      `protobuf:"bytes,6,rep,name=path,proto3" json:"path,omitempty"`
	TotalSteps    int32                  `protobuf:"varint,7,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	Suspicious    bool                   `protobuf:"varint,8,opt,name=suspicious,proto3" json:"suspicious,omitempty"`
	Flags         []*ForensicFlag        `protobuf:"bytes,9,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneyTrail) Reset() {
	*x = MoneyTrail{}
	mi := &file_proto_accounting_forensic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneyTrail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyTrail) ProtoMessage() {}

func (x *MoneyTrail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_forensic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyTrail.ProtoReflect.Descriptor instead.
func (*MoneyTrail) Descriptor() ([]byte, []int) {
	return file_proto_accounting_forensic_proto_rawDescGZIP(), []int{2}
}

func (x *MoneyTrail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MoneyTrail) GetStartAmount() *Amount {
	if x != nil {
		return x.StartAmount
	}
	return nil
}

func (x *MoneyTrail) GetEndAmount() *Amount {
	if x != nil {
		return x.EndAmount
	}
	return nil
}

func (x *MoneyTrail) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *MoneyTrail) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *MoneyTrail) GetPath() []*MoneyTrailStep {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *MoneyTrail) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *MoneyTrail) GetSuspicious() bool {
	if x != nil {
		return x.Suspicious
	}
	return false
}

func (x *MoneyTrail) GetFlags() []*ForensicFlag {
	if x != nil {
		return x.Flags
	}
	return nil
}

// QueryOptions
type QueryOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	SortBy        string                 `protobuf:"bytes,2,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOptions) Reset() {
	*x = QueryOptions{}
	mi := &file_proto_accounting_forensic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOptions) ProtoMessage() {}

func (x *QueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_forensic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOptions.ProtoReflect.Descriptor instead.
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return file_proto_accounting_forensic_proto_rawDescGZIP(), []int{3}
}

func (x *QueryOptions) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *QueryOptions) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *QueryOptions) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *QueryOptions) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Filter
type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	ValueJson     string                 `protobuf:"bytes,3,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"` // JSON-encoded value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_accounting_forensic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_forensic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_accounting_forensic_proto_rawDescGZIP(), []int{4}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Filter) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

// Discrepancy
type Discrepancy struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                DiscrepancyType        `protobuf:"varint,2,opt,name=type,proto3,enum=accounting.DiscrepancyType" json:"type,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ExpectedAmount      *Amount                `protobuf:"bytes,4,opt,name=expected_amount,json=expectedAmount,proto3" json:"expected_amount,omitempty"`
	ActualAmount        *Amount                `protobuf:"bytes,5,opt,name=actual_amount,json=actualAmount,proto3" json:"actual_amount,omitempty"`
	Difference          *Amount                `protobuf:"bytes,6,opt,name=difference,proto3" json:"difference,omitempty"`
	RelatedTransactions []string               `protobuf:"bytes,7,rep,name=related_transactions,json=relatedTransactions,proto3" json:"related_transactions,omitempty"`
	RelatedAccounts     []string               `protobuf:"bytes,8,rep,name=related_accounts,json=relatedAccounts,proto3" json:"related_accounts,omitempty"`
	Severity            Severity               `protobuf:"varint,9,opt,name=severity,proto3,enum=accounting.Severity" json:"severity,omitempty"`
	DetectedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Discrepancy) Reset() {
	*x = Discrepancy{}
	mi := &file_proto_accounting_forensic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discrepancy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discrepancy) ProtoMessage() {}

func (x *Discrepancy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_forensic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discrepancy.ProtoReflect.Descriptor instead.
func (*Discrepancy) Descriptor() ([]byte, []int) {
	return file_proto_accounting_forensic_proto_rawDescGZIP(), []int{5}
}

func (x *Discrepancy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Discrepancy) GetType() DiscrepancyType {
	if x != nil {
		return x.Type
	}
	return DiscrepancyType_DISCREPANCY_TYPE_UNSPECIFIED
}

func (x *Discrepancy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Discrepancy) GetExpectedAmount() *Amount {
	if x != nil {
		return x.ExpectedAmount
	}
	return nil
}

func (x *Discrepancy) GetActualAmount() *Amount {
	if x != nil {
		return x.ActualAmount
	}
	return nil
}

func (x *Discrepancy) GetDifference() *Amount {
	if x != nil {
		return x.Difference
	}
	return nil
}

func (x *Discrepancy) GetRelatedTransactions() []string {
	if x != nil {
		return x.RelatedTransactions
	}
	return nil
}

func (x *Discrepancy) GetRelatedAccounts() []string {
	if x != nil {
		return x.RelatedAccounts
	}
	return nil
}

func (x *Discrepancy) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Discrepancy) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

// AuditTrailEntry
type AuditTrailEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Before        []byte                 `protobuf:"bytes,6,opt,name=before,proto3" json:"before,omitempty"` // JSON or proto bytes
	After         []byte                 `protobuf:"bytes,7,opt,name=after,proto3" json:"after,omitempty"`   // JSON or proto bytes
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IpAddress     string                 `protobuf:"bytes,9,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditTrailEntry) Reset() {
	*x = AuditTrailEntry{}
	mi := &file_proto_accounting_forensic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditTrailEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditTrailEntry) ProtoMessage() {}

func (x *AuditTrailEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_forensic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditTrailEntry.ProtoReflect.Descriptor instead.
func (*AuditTrailEntry) Descriptor() ([]byte, []int) {
	return file_proto_accounting_forensic_proto_rawDescGZIP(), []int{6}
}

func (x *AuditTrailEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditTrailEntry) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AuditTrailEntry) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AuditTrailEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditTrailEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditTrailEntry) GetBefore() []byte {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *AuditTrailEntry) GetAfter() []byte {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *AuditTrailEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditTrailEntry) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditTrailEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_accounting_forensic_proto protoreflect.FileDescriptor

const file_proto_accounting_forensic_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/accounting/forensic.proto\x12\n" +
	"accounting\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!proto/accounting/accounting.proto\"\xe2\x01\n" +
	"\fForensicFlag\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.accounting.FlagTypeR\x04type\x120\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x14.accounting.SeverityR\bseverity\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bevidence\x18\x04 \x03(\tR\bevidence\x128\n" +
	"\ttriggered\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttriggered\"\x90\x02\n" +
	"\x0eMoneyTrailStep\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12!\n" +
	"\ffrom_account\x18\x02 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x03 \x01(\tR\ttoAccount\x12*\n" +
	"\x06amount\x18\x04 \x01(\v2\x12.accounting.AmountR\x06amount\x12.\n" +
	"\x04date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\"\x99\x03\n" +
	"\n" +
	"MoneyTrail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\fstart_amount\x18\x02 \x01(\v2\x12.accounting.AmountR\vstartAmount\x121\n" +
	"\n" +
	"end_amount\x18\x03 \x01(\v2\x12.accounting.AmountR\tendAmount\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12.\n" +
	"\x04path\x18\x06 \x03(\v2\x1a.accounting.MoneyTrailStepR\x04path\x12\x1f\n" +
	"\vtotal_steps\x18\a \x01(\x05R\n" +
	"totalSteps\x12\x1e\n" +
	"\n" +
	"suspicious\x18\b \x01(\bR\n" +
	"suspicious\x12.\n" +
	"\x05flags\x18\t \x03(\v2\x18.accounting.ForensicFlagR\x05flags\"\x8a\x01\n" +
	"\fQueryOptions\x12,\n" +
	"\afilters\x18\x01 \x03(\v2\x12.accounting.FilterR\afilters\x12\x17\n" +
	"\asort_by\x18\x02 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\tR\tsortOrder\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"Y\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x1d\n" +
	"\n" +
	"value_json\x18\x03 \x01(\tR\tvalueJson\"\xe7\x03\n" +
	"\vDiscrepancy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.accounting.DiscrepancyTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12;\n" +
	"\x0fexpected_amount\x18\x04 \x01(\v2\x12.accounting.AmountR\x0eexpectedAmount\x127\n" +
	"\ractual_amount\x18\x05 \x01(\v2\x12.accounting.AmountR\factualAmount\x122\n" +
	"\n" +
	"difference\x18\x06 \x01(\v2\x12.accounting.AmountR\n" +
	"difference\x121\n" +
	"\x14related_transactions\x18\a \x03(\tR\x13relatedTransactions\x12)\n" +
	"\x10related_accounts\x18\b \x03(\tR\x0frelatedAccounts\x120\n" +
	"\bseverity\x18\t \x01(\x0e2\x14.accounting.SeverityR\bseverity\x12;\n" +
	"\vdetected_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\"\x9b\x03\n" +
	"\x0fAuditTrailEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x16\n" +
	"\x06before\x18\x06 \x01(\fR\x06before\x12\x14\n" +
	"\x05after\x18\a \x01(\fR\x05after\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"ip_address\x18\t \x01(\tR\tipAddress\x12E\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2).accounting.AuditTrailEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xac\x04\n" +
	"\bFlagType\x12\x19\n" +
	"\x15FLAG_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FLAG_TYPE_ROUND_AMOUNTS\x10\x01\x12\x1c\n" +
	"\x18FLAG_TYPE_HIGH_FREQUENCY\x10\x02\x12\x1c\n" +
	"\x18FLAG_TYPE_UNUSUAL_TIMING\x10\x03\x12\x1d\n" +
	"\x19FLAG_TYPE_COMPLEX_ROUTING\x10\x04\x12\x16\n" +
	"\x12FLAG_TYPE_LAYERING\x10\x05\x12\x1c\n" +
	"\x18FLAG_TYPE_RAPID_MOVEMENT\x10\x06\x12\x19\n" +
	"\x15FLAG_TYPE_STRUCTURING\x10\a\x12 \n" +
	"\x1cFLAG_TYPE_CIRCULAR_TRANSFERS\x10\b\x12\"\n" +
	"\x1eFLAG_TYPE_DORMANT_REACTIVATION\x10\t\x12\x19\n" +
	"\x15FLAG_TYPE_KYC_EXPIRED\x10\n" +
	"\x12\x1d\n" +
	"\x19FLAG_TYPE_SANCTIONS_MATCH\x10\v\x12\x1d\n" +
	"\x19FLAG_TYPE_PEP_INVOLVEMENT\x10\f\x12\x1f\n" +
	"\x1bFLAG_TYPE_HIGH_RISK_COUNTRY\x10\r\x12\x1c\n" +
	"\x18FLAG_TYPE_CASH_INTENSIVE\x10\x0e\x12\x1e\n" +
	"\x1aFLAG_TYPE_VELOCITY_ANOMALY\x10\x0f\x12\x1e\n" +
	"\x1aFLAG_TYPE_AMOUNT_THRESHOLD\x10\x10\x12\x1e\n" +
	"\x1aFLAG_TYPE_SMURFING_PATTERN\x10\x11*u\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x04*\x8e\x02\n" +
	"\x0fDiscrepancyType\x12 \n" +
	"\x1cDISCREPANCY_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" DISCREPANCY_TYPE_AMOUNT_MISMATCH\x10\x01\x12\"\n" +
	"\x1eDISCREPANCY_TYPE_MISSING_ENTRY\x10\x02\x12$\n" +
	" DISCREPANCY_TYPE_DUPLICATE_ENTRY\x10\x03\x12\"\n" +
	"\x1eDISCREPANCY_TYPE_DATE_MISMATCH\x10\x04\x12%\n" +
	"!DISCREPANCY_TYPE_ACCOUNT_MISMATCH\x10\x05\x12\x1e\n" +
	"\x1aDISCREPANCY_TYPE_IMBALANCE\x10\x06B\x1dZ\x1baccounting/proto/accountingb\x06proto3"

var (
	file_proto_accounting_forensic_proto_rawDescOnce sync.Once
	file_proto_accounting_forensic_proto_rawDescData []byte
)

func file_proto_accounting_forensic_proto_rawDescGZIP() []byte {
	file_proto_accounting_forensic_proto_rawDescOnce.Do(func() {
		file_proto_accounting_forensic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accounting_forensic_proto_rawDesc), len(file_proto_accounting_forensic_proto_rawDesc)))
	})
	return file_proto_accounting_forensic_proto_rawDescData
}

var file_proto_accounting_forensic_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_accounting_forensic_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_accounting_forensic_proto_goTypes = []any{
	(FlagType)(0),                 // 0: accounting.FlagType
	(Severity)(0),                 // 1: accounting.Severity
	(DiscrepancyType)(0),          // 2: accounting.DiscrepancyType
	(*ForensicFlag)(nil),          // 3: accounting.ForensicFlag
	(*MoneyTrailStep)(nil),        // 4: accounting.MoneyTrailStep
	(*MoneyTrail)(nil),            // 5: accounting.MoneyTrail
	(*QueryOptions)(nil),          // 6: accounting.QueryOptions
	(*Filter)(nil),                // 7: accounting.Filter
	(*Discrepancy)(nil),           // 8: accounting.Discrepancy
	(*AuditTrailEntry)(nil),       // 9: accounting.AuditTrailEntry
	nil,                           // 10: accounting.AuditTrailEntry.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*Amount)(nil),                // 12: accounting.Amount
}
var file_proto_accounting_forensic_proto_depIdxs = []int32{
	0,  // 0: accounting.ForensicFlag.type:type_name -> accounting.FlagType
	1,  // 1: accounting.ForensicFlag.severity:type_name -> accounting.Severity
	11, // 2: accounting.ForensicFlag.triggered:type_name -> google.protobuf.Timestamp
	12, // 3: accounting.MoneyTrailStep.amount:type_name -> accounting.Amount
	11, // 4: accounting.MoneyTrailStep.date:type_name -> google.protobuf.Timestamp
	12, // 5: accounting.MoneyTrail.start_amount:type_name -> accounting.Amount
	12, // 6: accounting.MoneyTrail.end_amount:type_name -> accounting.Amount
	11, // 7: accounting.MoneyTrail.start_date:type_name -> google.protobuf.Timestamp
	11, // 8: accounting.MoneyTrail.end_date:type_name -> google.protobuf.Timestamp
	4,  // 9: accounting.MoneyTrail.path:type_name -> accounting.MoneyTrailStep
	3,  // 10: accounting.MoneyTrail.flags:type_name -> accounting.ForensicFlag
	7,  // 11: accounting.QueryOptions.filters:type_name -> accounting.Filter
	2,  // 12: accounting.Discrepancy.type:type_name -> accounting.DiscrepancyType
	12, // 13: accounting.Discrepancy.expected_amount:type_name -> accounting.Amount
	12, // 14: accounting.Discrepancy.actual_amount:type_name -> accounting.Amount
	12, // 15: accounting.Discrepancy.difference:type_name -> accounting.Amount
	1,  // 16: accounting.Discrepancy.severity:type_name -> accounting.Severity
	11, // 17: accounting.Discrepancy.detected_at:type_name -> google.protobuf.Timestamp
	11, // 18: accounting.AuditTrailEntry.timestamp:type_name -> google.protobuf.Timestamp
	10, // 19: accounting.AuditTrailEntry.metadata:type_name -> accounting.AuditTrailEntry.MetadataEntry
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_accounting_forensic_proto_init() }
func file_proto_accounting_forensic_proto_init() {
	if File_proto_accounting_forensic_proto != nil {
		return
	}
	file_proto_accounting_accounting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accounting_forensic_proto_rawDesc), len(file_proto_accounting_forensic_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_accounting_forensic_proto_goTypes,
		DependencyIndexes: file_proto_accounting_forensic_proto_depIdxs,
		EnumInfos:         file_proto_accounting_forensic_proto_enumTypes,
		MessageInfos:      file_proto_accounting_forensic_proto_msgTypes,
	}.Build()
	File_proto_accounting_forensic_proto = out.File
	file_proto_accounting_forensic_proto_goTypes = nil
	file_proto_accounting_forensic_proto_depIdxs = nil
}
