// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/accounting/multi_company.proto

package accounting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompanyStatus enum
type CompanyStatus int32

const (
	CompanyStatus_COMPANY_STATUS_UNSPECIFIED CompanyStatus = 0
	CompanyStatus_COMPANY_STATUS_ACTIVE      CompanyStatus = 1
	CompanyStatus_COMPANY_STATUS_INACTIVE    CompanyStatus = 2
	CompanyStatus_COMPANY_STATUS_SUSPENDED   CompanyStatus = 3
	CompanyStatus_COMPANY_STATUS_MERGED      CompanyStatus = 4
)

// Enum value maps for CompanyStatus.
var (
	CompanyStatus_name = map[int32]string{
		0: "COMPANY_STATUS_UNSPECIFIED",
		1: "COMPANY_STATUS_ACTIVE",
		2: "COMPANY_STATUS_INACTIVE",
		3: "COMPANY_STATUS_SUSPENDED",
		4: "COMPANY_STATUS_MERGED",
	}
	CompanyStatus_value = map[string]int32{
		"COMPANY_STATUS_UNSPECIFIED": 0,
		"COMPANY_STATUS_ACTIVE":      1,
		"COMPANY_STATUS_INACTIVE":    2,
		"COMPANY_STATUS_SUSPENDED":   3,
		"COMPANY_STATUS_MERGED":      4,
	}
)

func (x CompanyStatus) Enum() *CompanyStatus {
	p := new(CompanyStatus)
	*p = x
	return p
}

func (x CompanyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompanyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_multi_company_proto_enumTypes[0].Descriptor()
}

func (CompanyStatus) Type() protoreflect.EnumType {
	return &file_proto_accounting_multi_company_proto_enumTypes[0]
}

func (x CompanyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompanyStatus.Descriptor instead.
func (CompanyStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_multi_company_proto_rawDescGZIP(), []int{0}
}

// IntercompanyStatus enum
type IntercompanyStatus int32

const (
	IntercompanyStatus_INTERCOMPANY_STATUS_UNSPECIFIED IntercompanyStatus = 0
	IntercompanyStatus_INTERCOMPANY_STATUS_PENDING     IntercompanyStatus = 1
	IntercompanyStatus_INTERCOMPANY_STATUS_MATCHED     IntercompanyStatus = 2
	IntercompanyStatus_INTERCOMPANY_STATUS_RECONCILED  IntercompanyStatus = 3
	IntercompanyStatus_INTERCOMPANY_STATUS_DISPUTE     IntercompanyStatus = 4
)

// Enum value maps for IntercompanyStatus.
var (
	IntercompanyStatus_name = map[int32]string{
		0: "INTERCOMPANY_STATUS_UNSPECIFIED",
		1: "INTERCOMPANY_STATUS_PENDING",
		2: "INTERCOMPANY_STATUS_MATCHED",
		3: "INTERCOMPANY_STATUS_RECONCILED",
		4: "INTERCOMPANY_STATUS_DISPUTE",
	}
	IntercompanyStatus_value = map[string]int32{
		"INTERCOMPANY_STATUS_UNSPECIFIED": 0,
		"INTERCOMPANY_STATUS_PENDING":     1,
		"INTERCOMPANY_STATUS_MATCHED":     2,
		"INTERCOMPANY_STATUS_RECONCILED":  3,
		"INTERCOMPANY_STATUS_DISPUTE":     4,
	}
)

func (x IntercompanyStatus) Enum() *IntercompanyStatus {
	p := new(IntercompanyStatus)
	*p = x
	return p
}

func (x IntercompanyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntercompanyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_multi_company_proto_enumTypes[1].Descriptor()
}

func (IntercompanyStatus) Type() protoreflect.EnumType {
	return &file_proto_accounting_multi_company_proto_enumTypes[1]
}

func (x IntercompanyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntercompanyStatus.Descriptor instead.
func (IntercompanyStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_multi_company_proto_rawDescGZIP(), []int{1}
}

// Address
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street1       string                 `protobuf:"bytes,1,opt,name=street1,proto3" json:"street1,omitempty"`
	Street2       string                 `protobuf:"bytes,2,opt,name=street2,proto3" json:"street2,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_accounting_multi_company_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_multi_company_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_accounting_multi_company_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet1() string {
	if x != nil {
		return x.Street1
	}
	return ""
}

func (x *Address) GetStreet2() string {
	if x != nil {
		return x.Street2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// PostingAction
type PostingAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostingAction) Reset() {
	*x = PostingAction{}
	mi := &file_proto_accounting_multi_company_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostingAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostingAction) ProtoMessage() {}

func (x *PostingAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_multi_company_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostingAction.ProtoReflect.Descriptor instead.
func (*PostingAction) Descriptor() ([]byte, []int) {
	return file_proto_accounting_multi_company_proto_rawDescGZIP(), []int{1}
}

func (x *PostingAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PostingAction) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// AutoPostingRule
type AutoPostingRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Condition     string                 `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
	Actions       []*PostingAction       `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoPostingRule) Reset() {
	*x = AutoPostingRule{}
	mi := &file_proto_accounting_multi_company_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoPostingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoPostingRule) ProtoMessage() {}

func (x *AutoPostingRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_multi_company_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoPostingRule.ProtoReflect.Descriptor instead.
func (*AutoPostingRule) Descriptor() ([]byte, []int) {
	return file_proto_accounting_multi_company_proto_rawDescGZIP(), []int{2}
}

func (x *AutoPostingRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AutoPostingRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AutoPostingRule) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *AutoPostingRule) GetActions() []*PostingAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AutoPostingRule) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *AutoPostingRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CompanySettings
type CompanySettings struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	DefaultChartOfAccounts        string                 `protobuf:"bytes,1,opt,name=default_chart_of_accounts,json=defaultChartOfAccounts,proto3" json:"default_chart_of_accounts,omitempty"`
	AllowIntercompanyTransactions bool                   `protobuf:"varint,2,opt,name=allow_intercompany_transactions,json=allowIntercompanyTransactions,proto3" json:"allow_intercompany_transactions,omitempty"`
	RequireApprovalOver           *Amount                `protobuf:"bytes,3,opt,name=require_approval_over,json=requireApprovalOver,proto3" json:"require_approval_over,omitempty"`
	AutoPostingRules              []*AutoPostingRule     `protobuf:"bytes,4,rep,name=auto_posting_rules,json=autoPostingRules,proto3" json:"auto_posting_rules,omitempty"`
	PeriodLockingPolicy           string                 `protobuf:"bytes,5,opt,name=period_locking_policy,json=periodLockingPolicy,proto3" json:"period_locking_policy,omitempty"`
	ReportingCurrency             string                 `protobuf:"bytes,6,opt,name=reporting_currency,json=reportingCurrency,proto3" json:"reporting_currency,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *CompanySettings) Reset() {
	*x = CompanySettings{}
	mi := &file_proto_accounting_multi_company_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanySettings) ProtoMessage() {}

func (x *CompanySettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_multi_company_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanySettings.ProtoReflect.Descriptor instead.
func (*CompanySettings) Descriptor() ([]byte, []int) {
	return file_proto_accounting_multi_company_proto_rawDescGZIP(), []int{3}
}

func (x *CompanySettings) GetDefaultChartOfAccounts() string {
	if x != nil {
		return x.DefaultChartOfAccounts
	}
	return ""
}

func (x *CompanySettings) GetAllowIntercompanyTransactions() bool {
	if x != nil {
		return x.AllowIntercompanyTransactions
	}
	return false
}

func (x *CompanySettings) GetRequireApprovalOver() *Amount {
	if x != nil {
		return x.RequireApprovalOver
	}
	return nil
}

func (x *CompanySettings) GetAutoPostingRules() []*AutoPostingRule {
	if x != nil {
		return x.AutoPostingRules
	}
	return nil
}

func (x *CompanySettings) GetPeriodLockingPolicy() string {
	if x != nil {
		return x.PeriodLockingPolicy
	}
	return ""
}

func (x *CompanySettings) GetReportingCurrency() string {
	if x != nil {
		return x.ReportingCurrency
	}
	return ""
}

// Company
type Company struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LegalName       string                 `protobuf:"bytes,3,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	TaxId           string                 `protobuf:"bytes,4,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	BaseCurrency    string                 `protobuf:"bytes,5,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	FiscalYearEnd   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=fiscal_year_end,json=fiscalYearEnd,proto3" json:"fiscal_year_end,omitempty"`
	Address         *Address               `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Settings        *CompanySettings       `protobuf:"bytes,8,opt,name=settings,proto3" json:"settings,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy       string                 `protobuf:"bytes,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Status          CompanyStatus          `protobuf:"varint,11,opt,name=status,proto3,enum=accounting.CompanyStatus" json:"status,omitempty"`
	ParentCompanyId string                 `protobuf:"bytes,12,opt,name=parent_company_id,json=parentCompanyId,proto3" json:"parent_company_id,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_proto_accounting_multi_company_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_multi_company_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_proto_accounting_multi_company_proto_rawDescGZIP(), []int{4}
}

func (x *Company) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *Company) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *Company) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *Company) GetFiscalYearEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.FiscalYearEnd
	}
	return nil
}

func (x *Company) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Company) GetSettings() *CompanySettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Company) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Company) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Company) GetStatus() CompanyStatus {
	if x != nil {
		return x.Status
	}
	return CompanyStatus_COMPANY_STATUS_UNSPECIFIED
}

func (x *Company) GetParentCompanyId() string {
	if x != nil {
		return x.ParentCompanyId
	}
	return ""
}

func (x *Company) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// IntercompanyTransaction
type IntercompanyTransaction struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description         string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	SourceCompanyId     string                 `protobuf:"bytes,3,opt,name=source_company_id,json=sourceCompanyId,proto3" json:"source_company_id,omitempty"`
	TargetCompanyId     string                 `protobuf:"bytes,4,opt,name=target_company_id,json=targetCompanyId,proto3" json:"target_company_id,omitempty"`
	SourceTransactionId string                 `protobuf:"bytes,5,opt,name=source_transaction_id,json=sourceTransactionId,proto3" json:"source_transaction_id,omitempty"`
	TargetTransactionId string                 `protobuf:"bytes,6,opt,name=target_transaction_id,json=targetTransactionId,proto3" json:"target_transaction_id,omitempty"`
	Amount              *Amount                `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	ExchangeRate        float64                `protobuf:"fixed64,8,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	MatchingStatus      IntercompanyStatus     `protobuf:"varint,9,opt,name=matching_status,json=matchingStatus,proto3,enum=accounting.IntercompanyStatus" json:"matching_status,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy           string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ReconciledAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=reconciled_at,json=reconciledAt,proto3" json:"reconciled_at,omitempty"`
	ReconciledBy        string                 `protobuf:"bytes,13,opt,name=reconciled_by,json=reconciledBy,proto3" json:"reconciled_by,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IntercompanyTransaction) Reset() {
	*x = IntercompanyTransaction{}
	mi := &file_proto_accounting_multi_company_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntercompanyTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntercompanyTransaction) ProtoMessage() {}

func (x *IntercompanyTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_multi_company_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntercompanyTransaction.ProtoReflect.Descriptor instead.
func (*IntercompanyTransaction) Descriptor() ([]byte, []int) {
	return file_proto_accounting_multi_company_proto_rawDescGZIP(), []int{5}
}

func (x *IntercompanyTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IntercompanyTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IntercompanyTransaction) GetSourceCompanyId() string {
	if x != nil {
		return x.SourceCompanyId
	}
	return ""
}

func (x *IntercompanyTransaction) GetTargetCompanyId() string {
	if x != nil {
		return x.TargetCompanyId
	}
	return ""
}

func (x *IntercompanyTransaction) GetSourceTransactionId() string {
	if x != nil {
		return x.SourceTransactionId
	}
	return ""
}

func (x *IntercompanyTransaction) GetTargetTransactionId() string {
	if x != nil {
		return x.TargetTransactionId
	}
	return ""
}

func (x *IntercompanyTransaction) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *IntercompanyTransaction) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *IntercompanyTransaction) GetMatchingStatus() IntercompanyStatus {
	if x != nil {
		return x.MatchingStatus
	}
	return IntercompanyStatus_INTERCOMPANY_STATUS_UNSPECIFIED
}

func (x *IntercompanyTransaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *IntercompanyTransaction) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *IntercompanyTransaction) GetReconciledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReconciledAt
	}
	return nil
}

func (x *IntercompanyTransaction) GetReconciledBy() string {
	if x != nil {
		return x.ReconciledBy
	}
	return ""
}

// ConsolidationRule
type ConsolidationRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RuleType      string                 `protobuf:"bytes,4,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	Parameters    []string               `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsolidationRule) Reset() {
	*x = ConsolidationRule{}
	mi := &file_proto_accounting_multi_company_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidationRule) ProtoMessage() {}

func (x *ConsolidationRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_multi_company_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidationRule.ProtoReflect.Descriptor instead.
func (*ConsolidationRule) Descriptor() ([]byte, []int) {
	return file_proto_accounting_multi_company_proto_rawDescGZIP(), []int{6}
}

func (x *ConsolidationRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsolidationRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConsolidationRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConsolidationRule) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *ConsolidationRule) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ConsolidationRule) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ConsolidationRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ConsolidationGroup
type ConsolidationGroup struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentCompanyId       string                 `protobuf:"bytes,3,opt,name=parent_company_id,json=parentCompanyId,proto3" json:"parent_company_id,omitempty"`
	SubsidiaryIds         []string               `protobuf:"bytes,4,rep,name=subsidiary_ids,json=subsidiaryIds,proto3" json:"subsidiary_ids,omitempty"`
	ConsolidationCurrency string                 `protobuf:"bytes,5,opt,name=consolidation_currency,json=consolidationCurrency,proto3" json:"consolidation_currency,omitempty"`
	Rules                 []*ConsolidationRule   `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy             string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConsolidationGroup) Reset() {
	*x = ConsolidationGroup{}
	mi := &file_proto_accounting_multi_company_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidationGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidationGroup) ProtoMessage() {}

func (x *ConsolidationGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_multi_company_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidationGroup.ProtoReflect.Descriptor instead.
func (*ConsolidationGroup) Descriptor() ([]byte, []int) {
	return file_proto_accounting_multi_company_proto_rawDescGZIP(), []int{7}
}

func (x *ConsolidationGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsolidationGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConsolidationGroup) GetParentCompanyId() string {
	if x != nil {
		return x.ParentCompanyId
	}
	return ""
}

func (x *ConsolidationGroup) GetSubsidiaryIds() []string {
	if x != nil {
		return x.SubsidiaryIds
	}
	return nil
}

func (x *ConsolidationGroup) GetConsolidationCurrency() string {
	if x != nil {
		return x.ConsolidationCurrency
	}
	return ""
}

func (x *ConsolidationGroup) GetRules() []*ConsolidationRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ConsolidationGroup) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConsolidationGroup) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

// EliminationEntry
type EliminationEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConsolidationId string                 `protobuf:"bytes,2,opt,name=consolidation_id,json=consolidationId,proto3" json:"consolidation_id,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Amount          *Amount                `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	SourceCompanyId string                 `protobuf:"bytes,5,opt,name=source_company_id,json=sourceCompanyId,proto3" json:"source_company_id,omitempty"`
	TargetCompanyId string                 `protobuf:"bytes,6,opt,name=target_company_id,json=targetCompanyId,proto3" json:"target_company_id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EliminationEntry) Reset() {
	*x = EliminationEntry{}
	mi := &file_proto_accounting_multi_company_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminationEntry) ProtoMessage() {}

func (x *EliminationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_multi_company_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminationEntry.ProtoReflect.Descriptor instead.
func (*EliminationEntry) Descriptor() ([]byte, []int) {
	return file_proto_accounting_multi_company_proto_rawDescGZIP(), []int{8}
}

func (x *EliminationEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EliminationEntry) GetConsolidationId() string {
	if x != nil {
		return x.ConsolidationId
	}
	return ""
}

func (x *EliminationEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EliminationEntry) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *EliminationEntry) GetSourceCompanyId() string {
	if x != nil {
		return x.SourceCompanyId
	}
	return ""
}

func (x *EliminationEntry) GetTargetCompanyId() string {
	if x != nil {
		return x.TargetCompanyId
	}
	return ""
}

func (x *EliminationEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ConsolidatedStatement
type ConsolidatedStatement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PeriodId      string                 `protobuf:"bytes,3,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	StatementType string                 `protobuf:"bytes,4,opt,name=statement_type,json=statementType,proto3" json:"statement_type,omitempty"`
	CompanyIds    []string               `protobuf:"bytes,5,rep,name=company_ids,json=companyIds,proto3" json:"company_ids,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Data          []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"` // JSON or other format
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	GeneratedBy   string                 `protobuf:"bytes,9,opt,name=generated_by,json=generatedBy,proto3" json:"generated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsolidatedStatement) Reset() {
	*x = ConsolidatedStatement{}
	mi := &file_proto_accounting_multi_company_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidatedStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidatedStatement) ProtoMessage() {}

func (x *ConsolidatedStatement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_multi_company_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidatedStatement.ProtoReflect.Descriptor instead.
func (*ConsolidatedStatement) Descriptor() ([]byte, []int) {
	return file_proto_accounting_multi_company_proto_rawDescGZIP(), []int{9}
}

func (x *ConsolidatedStatement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsolidatedStatement) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ConsolidatedStatement) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *ConsolidatedStatement) GetStatementType() string {
	if x != nil {
		return x.StatementType
	}
	return ""
}

func (x *ConsolidatedStatement) GetCompanyIds() []string {
	if x != nil {
		return x.CompanyIds
	}
	return nil
}

func (x *ConsolidatedStatement) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ConsolidatedStatement) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ConsolidatedStatement) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *ConsolidatedStatement) GetGeneratedBy() string {
	if x != nil {
		return x.GeneratedBy
	}
	return ""
}

var File_proto_accounting_multi_company_proto protoreflect.FileDescriptor

const file_proto_accounting_multi_company_proto_rawDesc = "" +
	"\n" +
	"$proto/accounting/multi_company.proto\x12\n" +
	"accounting\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!proto/accounting/accounting.proto\"\xa2\x01\n" +
	"\aAddress\x12\x18\n" +
	"\astreet1\x18\x01 \x01(\tR\astreet1\x12\x18\n" +
	"\astreet2\x18\x02 \x01(\tR\astreet2\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x05 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\"\xad\x01\n" +
	"\rPostingAction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12I\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2).accounting.PostingAction.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x01\n" +
	"\x0fAutoPostingRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tcondition\x18\x03 \x01(\tR\tcondition\x123\n" +
	"\aactions\x18\x04 \x03(\v2\x19.accounting.PostingActionR\aactions\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8a\x03\n" +
	"\x0fCompanySettings\x129\n" +
	"\x19default_chart_of_accounts\x18\x01 \x01(\tR\x16defaultChartOfAccounts\x12F\n" +
	"\x1fallow_intercompany_transactions\x18\x02 \x01(\bR\x1dallowIntercompanyTransactions\x12F\n" +
	"\x15require_approval_over\x18\x03 \x01(\v2\x12.accounting.AmountR\x13requireApprovalOver\x12I\n" +
	"\x12auto_posting_rules\x18\x04 \x03(\v2\x1b.accounting.AutoPostingRuleR\x10autoPostingRules\x122\n" +
	"\x15period_locking_policy\x18\x05 \x01(\tR\x13periodLockingPolicy\x12-\n" +
	"\x12reporting_currency\x18\x06 \x01(\tR\x11reportingCurrency\"\xe9\x04\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x03 \x01(\tR\tlegalName\x12\x15\n" +
	"\x06tax_id\x18\x04 \x01(\tR\x05taxId\x12#\n" +
	"\rbase_currency\x18\x05 \x01(\tR\fbaseCurrency\x12B\n" +
	"\x0ffiscal_year_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rfiscalYearEnd\x12-\n" +
	"\aaddress\x18\a \x01(\v2\x13.accounting.AddressR\aaddress\x127\n" +
	"\bsettings\x18\b \x01(\v2\x1b.accounting.CompanySettingsR\bsettings\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\n" +
	" \x01(\tR\tcreatedBy\x121\n" +
	"\x06status\x18\v \x01(\x0e2\x19.accounting.CompanyStatusR\x06status\x12*\n" +
	"\x11parent_company_id\x18\f \x01(\tR\x0fparentCompanyId\x12=\n" +
	"\bmetadata\x18\r \x03(\v2!.accounting.Company.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe5\x04\n" +
	"\x17IntercompanyTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11source_company_id\x18\x03 \x01(\tR\x0fsourceCompanyId\x12*\n" +
	"\x11target_company_id\x18\x04 \x01(\tR\x0ftargetCompanyId\x122\n" +
	"\x15source_transaction_id\x18\x05 \x01(\tR\x13sourceTransactionId\x122\n" +
	"\x15target_transaction_id\x18\x06 \x01(\tR\x13targetTransactionId\x12*\n" +
	"\x06amount\x18\a \x01(\v2\x12.accounting.AmountR\x06amount\x12#\n" +
	"\rexchange_rate\x18\b \x01(\x01R\fexchangeRate\x12G\n" +
	"\x0fmatching_status\x18\t \x01(\x0e2\x1e.accounting.IntercompanyStatusR\x0ematchingStatus\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\v \x01(\tR\tcreatedBy\x12?\n" +
	"\rreconciled_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\freconciledAt\x12#\n" +
	"\rreconciled_by\x18\r \x01(\tR\freconciledBy\"\xee\x01\n" +
	"\x11ConsolidationRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\trule_type\x18\x04 \x01(\tR\bruleType\x12\x1e\n" +
	"\n" +
	"parameters\x18\x05 \x03(\tR\n" +
	"parameters\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd1\x02\n" +
	"\x12ConsolidationGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x11parent_company_id\x18\x03 \x01(\tR\x0fparentCompanyId\x12%\n" +
	"\x0esubsidiary_ids\x18\x04 \x03(\tR\rsubsidiaryIds\x125\n" +
	"\x16consolidation_currency\x18\x05 \x01(\tR\x15consolidationCurrency\x123\n" +
	"\x05rules\x18\x06 \x03(\v2\x1d.accounting.ConsolidationRuleR\x05rules\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\"\xae\x02\n" +
	"\x10EliminationEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10consolidation_id\x18\x02 \x01(\tR\x0fconsolidationId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x06amount\x18\x04 \x01(\v2\x12.accounting.AmountR\x06amount\x12*\n" +
	"\x11source_company_id\x18\x05 \x01(\tR\x0fsourceCompanyId\x12*\n" +
	"\x11target_company_id\x18\x06 \x01(\tR\x0ftargetCompanyId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb9\x02\n" +
	"\x15ConsolidatedStatement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1b\n" +
	"\tperiod_id\x18\x03 \x01(\tR\bperiodId\x12%\n" +
	"\x0estatement_type\x18\x04 \x01(\tR\rstatementType\x12\x1f\n" +
	"\vcompany_ids\x18\x05 \x03(\tR\n" +
	"companyIds\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\x12=\n" +
	"\fgenerated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12!\n" +
	"\fgenerated_by\x18\t \x01(\tR\vgeneratedBy*\xa0\x01\n" +
	"\rCompanyStatus\x12\x1e\n" +
	"\x1aCOMPANY_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COMPANY_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17COMPANY_STATUS_INACTIVE\x10\x02\x12\x1c\n" +
	"\x18COMPANY_STATUS_SUSPENDED\x10\x03\x12\x19\n" +
	"\x15COMPANY_STATUS_MERGED\x10\x04*\xc0\x01\n" +
	"\x12IntercompanyStatus\x12#\n" +
	"\x1fINTERCOMPANY_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bINTERCOMPANY_STATUS_PENDING\x10\x01\x12\x1f\n" +
	"\x1bINTERCOMPANY_STATUS_MATCHED\x10\x02\x12\"\n" +
	"\x1eINTERCOMPANY_STATUS_RECONCILED\x10\x03\x12\x1f\n" +
	"\x1bINTERCOMPANY_STATUS_DISPUTE\x10\x04B\x1dZ\x1baccounting/proto/accountingb\x06proto3"

var (
	file_proto_accounting_multi_company_proto_rawDescOnce sync.Once
	file_proto_accounting_multi_company_proto_rawDescData []byte
)

func file_proto_accounting_multi_company_proto_rawDescGZIP() []byte {
	file_proto_accounting_multi_company_proto_rawDescOnce.Do(func() {
		file_proto_accounting_multi_company_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accounting_multi_company_proto_rawDesc), len(file_proto_accounting_multi_company_proto_rawDesc)))
	})
	return file_proto_accounting_multi_company_proto_rawDescData
}

var file_proto_accounting_multi_company_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_accounting_multi_company_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_accounting_multi_company_proto_goTypes = []any{
	(CompanyStatus)(0),              // 0: accounting.CompanyStatus
	(IntercompanyStatus)(0),         // 1: accounting.IntercompanyStatus
	(*Address)(nil),                 // 2: accounting.Address
	(*PostingAction)(nil),           // 3: accounting.PostingAction
	(*AutoPostingRule)(nil),         // 4: accounting.AutoPostingRule
	(*CompanySettings)(nil),         // 5: accounting.CompanySettings
	(*Company)(nil),                 // 6: accounting.Company
	(*IntercompanyTransaction)(nil), // 7: accounting.IntercompanyTransaction
	(*ConsolidationRule)(nil),       // 8: accounting.ConsolidationRule
	(*ConsolidationGroup)(nil),      // 9: accounting.ConsolidationGroup
	(*EliminationEntry)(nil),        // 10: accounting.EliminationEntry
	(*ConsolidatedStatement)(nil),   // 11: accounting.ConsolidatedStatement
	nil,                             // 12: accounting.PostingAction.ParametersEntry
	nil,                             // 13: accounting.Company.MetadataEntry
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
	(*Amount)(nil),                  // 15: accounting.Amount
}
var file_proto_accounting_multi_company_proto_depIdxs = []int32{
	12, // 0: accounting.PostingAction.parameters:type_name -> accounting.PostingAction.ParametersEntry
	3,  // 1: accounting.AutoPostingRule.actions:type_name -> accounting.PostingAction
	14, // 2: accounting.AutoPostingRule.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: accounting.CompanySettings.require_approval_over:type_name -> accounting.Amount
	4,  // 4: accounting.CompanySettings.auto_posting_rules:type_name -> accounting.AutoPostingRule
	14, // 5: accounting.Company.fiscal_year_end:type_name -> google.protobuf.Timestamp
	2,  // 6: accounting.Company.address:type_name -> accounting.Address
	5,  // 7: accounting.Company.settings:type_name -> accounting.CompanySettings
	14, // 8: accounting.Company.created_at:type_name -> google.protobuf.Timestamp
	0,  // 9: accounting.Company.status:type_name -> accounting.CompanyStatus
	13, // 10: accounting.Company.metadata:type_name -> accounting.Company.MetadataEntry
	15, // 11: accounting.IntercompanyTransaction.amount:type_name -> accounting.Amount
	1,  // 12: accounting.IntercompanyTransaction.matching_status:type_name -> accounting.IntercompanyStatus
	14, // 13: accounting.IntercompanyTransaction.created_at:type_name -> google.protobuf.Timestamp
	14, // 14: accounting.IntercompanyTransaction.reconciled_at:type_name -> google.protobuf.Timestamp
	14, // 15: accounting.ConsolidationRule.created_at:type_name -> google.protobuf.Timestamp
	8,  // 16: accounting.ConsolidationGroup.rules:type_name -> accounting.ConsolidationRule
	14, // 17: accounting.ConsolidationGroup.created_at:type_name -> google.protobuf.Timestamp
	15, // 18: accounting.EliminationEntry.amount:type_name -> accounting.Amount
	14, // 19: accounting.EliminationEntry.created_at:type_name -> google.protobuf.Timestamp
	14, // 20: accounting.ConsolidatedStatement.generated_at:type_name -> google.protobuf.Timestamp
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_accounting_multi_company_proto_init() }
func file_proto_accounting_multi_company_proto_init() {
	if File_proto_accounting_multi_company_proto != nil {
		return
	}
	file_proto_accounting_accounting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accounting_multi_company_proto_rawDesc), len(file_proto_accounting_multi_company_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_accounting_multi_company_proto_goTypes,
		DependencyIndexes: file_proto_accounting_multi_company_proto_depIdxs,
		EnumInfos:         file_proto_accounting_multi_company_proto_enumTypes,
		MessageInfos:      file_proto_accounting_multi_company_proto_msgTypes,
	}.Build()
	File_proto_accounting_multi_company_proto = out.File
	file_proto_accounting_multi_company_proto_goTypes = nil
	file_proto_accounting_multi_company_proto_depIdxs = nil
}
