// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/accounting/reconciliation.proto

package accounting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExternalStatement
type ExternalStatement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Amount        *Amount                `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Reference     string                 `protobuf:"bytes,5,opt,name=reference,proto3" json:"reference,omitempty"`
	BankAccount   string                 `protobuf:"bytes,6,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalStatement) Reset() {
	*x = ExternalStatement{}
	mi := &file_proto_accounting_reconciliation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalStatement) ProtoMessage() {}

func (x *ExternalStatement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_reconciliation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalStatement.ProtoReflect.Descriptor instead.
func (*ExternalStatement) Descriptor() ([]byte, []int) {
	return file_proto_accounting_reconciliation_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalStatement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalStatement) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *ExternalStatement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExternalStatement) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *ExternalStatement) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ExternalStatement) GetBankAccount() string {
	if x != nil {
		return x.BankAccount
	}
	return ""
}

// ReconciliationMatch
type ReconciliationMatch struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExternalStatement *ExternalStatement     `protobuf:"bytes,1,opt,name=external_statement,json=externalStatement,proto3" json:"external_statement,omitempty"`
	InternalEntries   []*Entry               `protobuf:"bytes,2,rep,name=internal_entries,json=internalEntries,proto3" json:"internal_entries,omitempty"`
	MatchScore        float64                `protobuf:"fixed64,3,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	MatchType         string                 `protobuf:"bytes,4,opt,name=match_type,json=matchType,proto3" json:"match_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReconciliationMatch) Reset() {
	*x = ReconciliationMatch{}
	mi := &file_proto_accounting_reconciliation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationMatch) ProtoMessage() {}

func (x *ReconciliationMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_reconciliation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationMatch.ProtoReflect.Descriptor instead.
func (*ReconciliationMatch) Descriptor() ([]byte, []int) {
	return file_proto_accounting_reconciliation_proto_rawDescGZIP(), []int{1}
}

func (x *ReconciliationMatch) GetExternalStatement() *ExternalStatement {
	if x != nil {
		return x.ExternalStatement
	}
	return nil
}

func (x *ReconciliationMatch) GetInternalEntries() []*Entry {
	if x != nil {
		return x.InternalEntries
	}
	return nil
}

func (x *ReconciliationMatch) GetMatchScore() float64 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *ReconciliationMatch) GetMatchType() string {
	if x != nil {
		return x.MatchType
	}
	return ""
}

// ReconciliationSummary
type ReconciliationSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccountId          string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	StatementBalance   *Amount                `protobuf:"bytes,2,opt,name=statement_balance,json=statementBalance,proto3" json:"statement_balance,omitempty"`
	BookBalance        *Amount                `protobuf:"bytes,3,opt,name=book_balance,json=bookBalance,proto3" json:"book_balance,omitempty"`
	Difference         *Amount                `protobuf:"bytes,4,opt,name=difference,proto3" json:"difference,omitempty"`
	ReconciledCount    int32                  `protobuf:"varint,5,opt,name=reconciled_count,json=reconciledCount,proto3" json:"reconciled_count,omitempty"`
	UnreconciledCount  int32                  `protobuf:"varint,6,opt,name=unreconciled_count,json=unreconciledCount,proto3" json:"unreconciled_count,omitempty"`
	ReconciliationRate float64                `protobuf:"fixed64,7,opt,name=reconciliation_rate,json=reconciliationRate,proto3" json:"reconciliation_rate,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReconciliationSummary) Reset() {
	*x = ReconciliationSummary{}
	mi := &file_proto_accounting_reconciliation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationSummary) ProtoMessage() {}

func (x *ReconciliationSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_reconciliation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationSummary.ProtoReflect.Descriptor instead.
func (*ReconciliationSummary) Descriptor() ([]byte, []int) {
	return file_proto_accounting_reconciliation_proto_rawDescGZIP(), []int{2}
}

func (x *ReconciliationSummary) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ReconciliationSummary) GetStatementBalance() *Amount {
	if x != nil {
		return x.StatementBalance
	}
	return nil
}

func (x *ReconciliationSummary) GetBookBalance() *Amount {
	if x != nil {
		return x.BookBalance
	}
	return nil
}

func (x *ReconciliationSummary) GetDifference() *Amount {
	if x != nil {
		return x.Difference
	}
	return nil
}

func (x *ReconciliationSummary) GetReconciledCount() int32 {
	if x != nil {
		return x.ReconciledCount
	}
	return 0
}

func (x *ReconciliationSummary) GetUnreconciledCount() int32 {
	if x != nil {
		return x.UnreconciledCount
	}
	return 0
}

func (x *ReconciliationSummary) GetReconciliationRate() float64 {
	if x != nil {
		return x.ReconciliationRate
	}
	return 0
}

var File_proto_accounting_reconciliation_proto protoreflect.FileDescriptor

const file_proto_accounting_reconciliation_proto_rawDesc = "" +
	"\n" +
	"%proto/accounting/reconciliation.proto\x12\n" +
	"accounting\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!proto/accounting/accounting.proto\"\xe2\x01\n" +
	"\x11ExternalStatement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x06amount\x18\x04 \x01(\v2\x12.accounting.AmountR\x06amount\x12\x1c\n" +
	"\treference\x18\x05 \x01(\tR\treference\x12!\n" +
	"\fbank_account\x18\x06 \x01(\tR\vbankAccount\"\xe1\x01\n" +
	"\x13ReconciliationMatch\x12L\n" +
	"\x12external_statement\x18\x01 \x01(\v2\x1d.accounting.ExternalStatementR\x11externalStatement\x12<\n" +
	"\x10internal_entries\x18\x02 \x03(\v2\x11.accounting.EntryR\x0finternalEntries\x12\x1f\n" +
	"\vmatch_score\x18\x03 \x01(\x01R\n" +
	"matchScore\x12\x1d\n" +
	"\n" +
	"match_type\x18\x04 \x01(\tR\tmatchType\"\xed\x02\n" +
	"\x15ReconciliationSummary\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12?\n" +
	"\x11statement_balance\x18\x02 \x01(\v2\x12.accounting.AmountR\x10statementBalance\x125\n" +
	"\fbook_balance\x18\x03 \x01(\v2\x12.accounting.AmountR\vbookBalance\x122\n" +
	"\n" +
	"difference\x18\x04 \x01(\v2\x12.accounting.AmountR\n" +
	"difference\x12)\n" +
	"\x10reconciled_count\x18\x05 \x01(\x05R\x0freconciledCount\x12-\n" +
	"\x12unreconciled_count\x18\x06 \x01(\x05R\x11unreconciledCount\x12/\n" +
	"\x13reconciliation_rate\x18\a \x01(\x01R\x12reconciliationRateB\x1dZ\x1baccounting/proto/accountingb\x06proto3"

var (
	file_proto_accounting_reconciliation_proto_rawDescOnce sync.Once
	file_proto_accounting_reconciliation_proto_rawDescData []byte
)

func file_proto_accounting_reconciliation_proto_rawDescGZIP() []byte {
	file_proto_accounting_reconciliation_proto_rawDescOnce.Do(func() {
		file_proto_accounting_reconciliation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accounting_reconciliation_proto_rawDesc), len(file_proto_accounting_reconciliation_proto_rawDesc)))
	})
	return file_proto_accounting_reconciliation_proto_rawDescData
}

var file_proto_accounting_reconciliation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_accounting_reconciliation_proto_goTypes = []any{
	(*ExternalStatement)(nil),     // 0: accounting.ExternalStatement
	(*ReconciliationMatch)(nil),   // 1: accounting.ReconciliationMatch
	(*ReconciliationSummary)(nil), // 2: accounting.ReconciliationSummary
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*Amount)(nil),                // 4: accounting.Amount
	(*Entry)(nil),                 // 5: accounting.Entry
}
var file_proto_accounting_reconciliation_proto_depIdxs = []int32{
	3, // 0: accounting.ExternalStatement.date:type_name -> google.protobuf.Timestamp
	4, // 1: accounting.ExternalStatement.amount:type_name -> accounting.Amount
	0, // 2: accounting.ReconciliationMatch.external_statement:type_name -> accounting.ExternalStatement
	5, // 3: accounting.ReconciliationMatch.internal_entries:type_name -> accounting.Entry
	4, // 4: accounting.ReconciliationSummary.statement_balance:type_name -> accounting.Amount
	4, // 5: accounting.ReconciliationSummary.book_balance:type_name -> accounting.Amount
	4, // 6: accounting.ReconciliationSummary.difference:type_name -> accounting.Amount
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_accounting_reconciliation_proto_init() }
func file_proto_accounting_reconciliation_proto_init() {
	if File_proto_accounting_reconciliation_proto != nil {
		return
	}
	file_proto_accounting_accounting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accounting_reconciliation_proto_rawDesc), len(file_proto_accounting_reconciliation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_accounting_reconciliation_proto_goTypes,
		DependencyIndexes: file_proto_accounting_reconciliation_proto_depIdxs,
		MessageInfos:      file_proto_accounting_reconciliation_proto_msgTypes,
	}.Build()
	File_proto_accounting_reconciliation_proto = out.File
	file_proto_accounting_reconciliation_proto_goTypes = nil
	file_proto_accounting_reconciliation_proto_depIdxs = nil
}
