// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/accounting/reporting.proto

package accounting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CashFlowCategory enum
type CashFlowCategory int32

const (
	CashFlowCategory_CASH_FLOW_CATEGORY_UNSPECIFIED CashFlowCategory = 0
	CashFlowCategory_CASH_FLOW_CATEGORY_OPERATING   CashFlowCategory = 1
	CashFlowCategory_CASH_FLOW_CATEGORY_INVESTING   CashFlowCategory = 2
	CashFlowCategory_CASH_FLOW_CATEGORY_FINANCING   CashFlowCategory = 3
)

// Enum value maps for CashFlowCategory.
var (
	CashFlowCategory_name = map[int32]string{
		0: "CASH_FLOW_CATEGORY_UNSPECIFIED",
		1: "CASH_FLOW_CATEGORY_OPERATING",
		2: "CASH_FLOW_CATEGORY_INVESTING",
		3: "CASH_FLOW_CATEGORY_FINANCING",
	}
	CashFlowCategory_value = map[string]int32{
		"CASH_FLOW_CATEGORY_UNSPECIFIED": 0,
		"CASH_FLOW_CATEGORY_OPERATING":   1,
		"CASH_FLOW_CATEGORY_INVESTING":   2,
		"CASH_FLOW_CATEGORY_FINANCING":   3,
	}
)

func (x CashFlowCategory) Enum() *CashFlowCategory {
	p := new(CashFlowCategory)
	*p = x
	return p
}

func (x CashFlowCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CashFlowCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_reporting_proto_enumTypes[0].Descriptor()
}

func (CashFlowCategory) Type() protoreflect.EnumType {
	return &file_proto_accounting_reporting_proto_enumTypes[0]
}

func (x CashFlowCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CashFlowCategory.Descriptor instead.
func (CashFlowCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_reporting_proto_rawDescGZIP(), []int{0}
}

// FinancialLineItem
type FinancialLineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName   string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountType   AccountType            `protobuf:"varint,3,opt,name=account_type,json=accountType,proto3,enum=accounting.AccountType" json:"account_type,omitempty"`
	Amount        *Amount                `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	IsSubtotal    bool                   `protobuf:"varint,6,opt,name=is_subtotal,json=isSubtotal,proto3" json:"is_subtotal,omitempty"`
	Children      []*FinancialLineItem   `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinancialLineItem) Reset() {
	*x = FinancialLineItem{}
	mi := &file_proto_accounting_reporting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialLineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialLineItem) ProtoMessage() {}

func (x *FinancialLineItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_reporting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialLineItem.ProtoReflect.Descriptor instead.
func (*FinancialLineItem) Descriptor() ([]byte, []int) {
	return file_proto_accounting_reporting_proto_rawDescGZIP(), []int{0}
}

func (x *FinancialLineItem) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *FinancialLineItem) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *FinancialLineItem) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *FinancialLineItem) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *FinancialLineItem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *FinancialLineItem) GetIsSubtotal() bool {
	if x != nil {
		return x.IsSubtotal
	}
	return false
}

func (x *FinancialLineItem) GetChildren() []*FinancialLineItem {
	if x != nil {
		return x.Children
	}
	return nil
}

// FinancialStatement
type FinancialStatement struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AsOfDate         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=as_of_date,json=asOfDate,proto3" json:"as_of_date,omitempty"`
	FromDate         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	LineItems        []*FinancialLineItem   `protobuf:"bytes,5,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	TotalAssets      *Amount                `protobuf:"bytes,6,opt,name=total_assets,json=totalAssets,proto3" json:"total_assets,omitempty"`
	TotalLiabilities *Amount                `protobuf:"bytes,7,opt,name=total_liabilities,json=totalLiabilities,proto3" json:"total_liabilities,omitempty"`
	TotalEquity      *Amount                `protobuf:"bytes,8,opt,name=total_equity,json=totalEquity,proto3" json:"total_equity,omitempty"`
	NetIncome        *Amount                `protobuf:"bytes,9,opt,name=net_income,json=netIncome,proto3" json:"net_income,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FinancialStatement) Reset() {
	*x = FinancialStatement{}
	mi := &file_proto_accounting_reporting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialStatement) ProtoMessage() {}

func (x *FinancialStatement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_reporting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialStatement.ProtoReflect.Descriptor instead.
func (*FinancialStatement) Descriptor() ([]byte, []int) {
	return file_proto_accounting_reporting_proto_rawDescGZIP(), []int{1}
}

func (x *FinancialStatement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FinancialStatement) GetAsOfDate() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOfDate
	}
	return nil
}

func (x *FinancialStatement) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *FinancialStatement) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FinancialStatement) GetLineItems() []*FinancialLineItem {
	if x != nil {
		return x.LineItems
	}
	return nil
}

func (x *FinancialStatement) GetTotalAssets() *Amount {
	if x != nil {
		return x.TotalAssets
	}
	return nil
}

func (x *FinancialStatement) GetTotalLiabilities() *Amount {
	if x != nil {
		return x.TotalLiabilities
	}
	return nil
}

func (x *FinancialStatement) GetTotalEquity() *Amount {
	if x != nil {
		return x.TotalEquity
	}
	return nil
}

func (x *FinancialStatement) GetNetIncome() *Amount {
	if x != nil {
		return x.NetIncome
	}
	return nil
}

// CashFlowItem
type CashFlowItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Amount        *Amount                `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      CashFlowCategory       `protobuf:"varint,3,opt,name=category,proto3,enum=accounting.CashFlowCategory" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFlowItem) Reset() {
	*x = CashFlowItem{}
	mi := &file_proto_accounting_reporting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFlowItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFlowItem) ProtoMessage() {}

func (x *CashFlowItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_reporting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFlowItem.ProtoReflect.Descriptor instead.
func (*CashFlowItem) Descriptor() ([]byte, []int) {
	return file_proto_accounting_reporting_proto_rawDescGZIP(), []int{2}
}

func (x *CashFlowItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CashFlowItem) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CashFlowItem) GetCategory() CashFlowCategory {
	if x != nil {
		return x.Category
	}
	return CashFlowCategory_CASH_FLOW_CATEGORY_UNSPECIFIED
}

// CashFlowStatement
type CashFlowStatement struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FromDate            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate              *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	Currency            string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	OperatingActivities []*CashFlowItem        `protobuf:"bytes,5,rep,name=operating_activities,json=operatingActivities,proto3" json:"operating_activities,omitempty"`
	InvestingActivities []*CashFlowItem        `protobuf:"bytes,6,rep,name=investing_activities,json=investingActivities,proto3" json:"investing_activities,omitempty"`
	FinancingActivities []*CashFlowItem        `protobuf:"bytes,7,rep,name=financing_activities,json=financingActivities,proto3" json:"financing_activities,omitempty"`
	NetCashFlow         *Amount                `protobuf:"bytes,8,opt,name=net_cash_flow,json=netCashFlow,proto3" json:"net_cash_flow,omitempty"`
	BeginningCash       *Amount                `protobuf:"bytes,9,opt,name=beginning_cash,json=beginningCash,proto3" json:"beginning_cash,omitempty"`
	EndingCash          *Amount                `protobuf:"bytes,10,opt,name=ending_cash,json=endingCash,proto3" json:"ending_cash,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CashFlowStatement) Reset() {
	*x = CashFlowStatement{}
	mi := &file_proto_accounting_reporting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFlowStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFlowStatement) ProtoMessage() {}

func (x *CashFlowStatement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_reporting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFlowStatement.ProtoReflect.Descriptor instead.
func (*CashFlowStatement) Descriptor() ([]byte, []int) {
	return file_proto_accounting_reporting_proto_rawDescGZIP(), []int{3}
}

func (x *CashFlowStatement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CashFlowStatement) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *CashFlowStatement) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

func (x *CashFlowStatement) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CashFlowStatement) GetOperatingActivities() []*CashFlowItem {
	if x != nil {
		return x.OperatingActivities
	}
	return nil
}

func (x *CashFlowStatement) GetInvestingActivities() []*CashFlowItem {
	if x != nil {
		return x.InvestingActivities
	}
	return nil
}

func (x *CashFlowStatement) GetFinancingActivities() []*CashFlowItem {
	if x != nil {
		return x.FinancingActivities
	}
	return nil
}

func (x *CashFlowStatement) GetNetCashFlow() *Amount {
	if x != nil {
		return x.NetCashFlow
	}
	return nil
}

func (x *CashFlowStatement) GetBeginningCash() *Amount {
	if x != nil {
		return x.BeginningCash
	}
	return nil
}

func (x *CashFlowStatement) GetEndingCash() *Amount {
	if x != nil {
		return x.EndingCash
	}
	return nil
}

var File_proto_accounting_reporting_proto protoreflect.FileDescriptor

const file_proto_accounting_reporting_proto_rawDesc = "" +
	"\n" +
	" proto/accounting/reporting.proto\x12\n" +
	"accounting\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!proto/accounting/accounting.proto\"\xaf\x02\n" +
	"\x11FinancialLineItem\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12:\n" +
	"\faccount_type\x18\x03 \x01(\x0e2\x17.accounting.AccountTypeR\vaccountType\x12*\n" +
	"\x06amount\x18\x04 \x01(\v2\x12.accounting.AmountR\x06amount\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x1f\n" +
	"\vis_subtotal\x18\x06 \x01(\bR\n" +
	"isSubtotal\x129\n" +
	"\bchildren\x18\a \x03(\v2\x1d.accounting.FinancialLineItemR\bchildren\"\xd7\x03\n" +
	"\x12FinancialStatement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\n" +
	"as_of_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\basOfDate\x127\n" +
	"\tfrom_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12<\n" +
	"\n" +
	"line_items\x18\x05 \x03(\v2\x1d.accounting.FinancialLineItemR\tlineItems\x125\n" +
	"\ftotal_assets\x18\x06 \x01(\v2\x12.accounting.AmountR\vtotalAssets\x12?\n" +
	"\x11total_liabilities\x18\a \x01(\v2\x12.accounting.AmountR\x10totalLiabilities\x125\n" +
	"\ftotal_equity\x18\b \x01(\v2\x12.accounting.AmountR\vtotalEquity\x121\n" +
	"\n" +
	"net_income\x18\t \x01(\v2\x12.accounting.AmountR\tnetIncome\"\x96\x01\n" +
	"\fCashFlowItem\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12*\n" +
	"\x06amount\x18\x02 \x01(\v2\x12.accounting.AmountR\x06amount\x128\n" +
	"\bcategory\x18\x03 \x01(\x0e2\x1c.accounting.CashFlowCategoryR\bcategory\"\xc0\x04\n" +
	"\x11CashFlowStatement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tfrom_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12K\n" +
	"\x14operating_activities\x18\x05 \x03(\v2\x18.accounting.CashFlowItemR\x13operatingActivities\x12K\n" +
	"\x14investing_activities\x18\x06 \x03(\v2\x18.accounting.CashFlowItemR\x13investingActivities\x12K\n" +
	"\x14financing_activities\x18\a \x03(\v2\x18.accounting.CashFlowItemR\x13financingActivities\x126\n" +
	"\rnet_cash_flow\x18\b \x01(\v2\x12.accounting.AmountR\vnetCashFlow\x129\n" +
	"\x0ebeginning_cash\x18\t \x01(\v2\x12.accounting.AmountR\rbeginningCash\x123\n" +
	"\vending_cash\x18\n" +
	" \x01(\v2\x12.accounting.AmountR\n" +
	"endingCash*\x9c\x01\n" +
	"\x10CashFlowCategory\x12\"\n" +
	"\x1eCASH_FLOW_CATEGORY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCASH_FLOW_CATEGORY_OPERATING\x10\x01\x12 \n" +
	"\x1cCASH_FLOW_CATEGORY_INVESTING\x10\x02\x12 \n" +
	"\x1cCASH_FLOW_CATEGORY_FINANCING\x10\x03B\x1dZ\x1baccounting/proto/accountingb\x06proto3"

var (
	file_proto_accounting_reporting_proto_rawDescOnce sync.Once
	file_proto_accounting_reporting_proto_rawDescData []byte
)

func file_proto_accounting_reporting_proto_rawDescGZIP() []byte {
	file_proto_accounting_reporting_proto_rawDescOnce.Do(func() {
		file_proto_accounting_reporting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accounting_reporting_proto_rawDesc), len(file_proto_accounting_reporting_proto_rawDesc)))
	})
	return file_proto_accounting_reporting_proto_rawDescData
}

var file_proto_accounting_reporting_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_accounting_reporting_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_accounting_reporting_proto_goTypes = []any{
	(CashFlowCategory)(0),         // 0: accounting.CashFlowCategory
	(*FinancialLineItem)(nil),     // 1: accounting.FinancialLineItem
	(*FinancialStatement)(nil),    // 2: accounting.FinancialStatement
	(*CashFlowItem)(nil),          // 3: accounting.CashFlowItem
	(*CashFlowStatement)(nil),     // 4: accounting.CashFlowStatement
	(AccountType)(0),              // 5: accounting.AccountType
	(*Amount)(nil),                // 6: accounting.Amount
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_accounting_reporting_proto_depIdxs = []int32{
	5,  // 0: accounting.FinancialLineItem.account_type:type_name -> accounting.AccountType
	6,  // 1: accounting.FinancialLineItem.amount:type_name -> accounting.Amount
	1,  // 2: accounting.FinancialLineItem.children:type_name -> accounting.FinancialLineItem
	7,  // 3: accounting.FinancialStatement.as_of_date:type_name -> google.protobuf.Timestamp
	7,  // 4: accounting.FinancialStatement.from_date:type_name -> google.protobuf.Timestamp
	1,  // 5: accounting.FinancialStatement.line_items:type_name -> accounting.FinancialLineItem
	6,  // 6: accounting.FinancialStatement.total_assets:type_name -> accounting.Amount
	6,  // 7: accounting.FinancialStatement.total_liabilities:type_name -> accounting.Amount
	6,  // 8: accounting.FinancialStatement.total_equity:type_name -> accounting.Amount
	6,  // 9: accounting.FinancialStatement.net_income:type_name -> accounting.Amount
	6,  // 10: accounting.CashFlowItem.amount:type_name -> accounting.Amount
	0,  // 11: accounting.CashFlowItem.category:type_name -> accounting.CashFlowCategory
	7,  // 12: accounting.CashFlowStatement.from_date:type_name -> google.protobuf.Timestamp
	7,  // 13: accounting.CashFlowStatement.to_date:type_name -> google.protobuf.Timestamp
	3,  // 14: accounting.CashFlowStatement.operating_activities:type_name -> accounting.CashFlowItem
	3,  // 15: accounting.CashFlowStatement.investing_activities:type_name -> accounting.CashFlowItem
	3,  // 16: accounting.CashFlowStatement.financing_activities:type_name -> accounting.CashFlowItem
	6,  // 17: accounting.CashFlowStatement.net_cash_flow:type_name -> accounting.Amount
	6,  // 18: accounting.CashFlowStatement.beginning_cash:type_name -> accounting.Amount
	6,  // 19: accounting.CashFlowStatement.ending_cash:type_name -> accounting.Amount
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_accounting_reporting_proto_init() }
func file_proto_accounting_reporting_proto_init() {
	if File_proto_accounting_reporting_proto != nil {
		return
	}
	file_proto_accounting_accounting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accounting_reporting_proto_rawDesc), len(file_proto_accounting_reporting_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_accounting_reporting_proto_goTypes,
		DependencyIndexes: file_proto_accounting_reporting_proto_depIdxs,
		EnumInfos:         file_proto_accounting_reporting_proto_enumTypes,
		MessageInfos:      file_proto_accounting_reporting_proto_msgTypes,
	}.Build()
	File_proto_accounting_reporting_proto = out.File
	file_proto_accounting_reporting_proto_goTypes = nil
	file_proto_accounting_reporting_proto_depIdxs = nil
}
