// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/accounting/zbb.proto

package accounting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BudgetPeriodStatus enum
type BudgetPeriodStatus int32

const (
	BudgetPeriodStatus_BUDGET_PERIOD_STATUS_UNSPECIFIED BudgetPeriodStatus = 0
	BudgetPeriodStatus_BUDGET_PERIOD_STATUS_DRAFT       BudgetPeriodStatus = 1
	BudgetPeriodStatus_BUDGET_PERIOD_STATUS_OPEN        BudgetPeriodStatus = 2
	BudgetPeriodStatus_BUDGET_PERIOD_STATUS_SUBMITTED   BudgetPeriodStatus = 3
	BudgetPeriodStatus_BUDGET_PERIOD_STATUS_APPROVED    BudgetPeriodStatus = 4
	BudgetPeriodStatus_BUDGET_PERIOD_STATUS_LOCKED      BudgetPeriodStatus = 5
)

// Enum value maps for BudgetPeriodStatus.
var (
	BudgetPeriodStatus_name = map[int32]string{
		0: "BUDGET_PERIOD_STATUS_UNSPECIFIED",
		1: "BUDGET_PERIOD_STATUS_DRAFT",
		2: "BUDGET_PERIOD_STATUS_OPEN",
		3: "BUDGET_PERIOD_STATUS_SUBMITTED",
		4: "BUDGET_PERIOD_STATUS_APPROVED",
		5: "BUDGET_PERIOD_STATUS_LOCKED",
	}
	BudgetPeriodStatus_value = map[string]int32{
		"BUDGET_PERIOD_STATUS_UNSPECIFIED": 0,
		"BUDGET_PERIOD_STATUS_DRAFT":       1,
		"BUDGET_PERIOD_STATUS_OPEN":        2,
		"BUDGET_PERIOD_STATUS_SUBMITTED":   3,
		"BUDGET_PERIOD_STATUS_APPROVED":    4,
		"BUDGET_PERIOD_STATUS_LOCKED":      5,
	}
)

func (x BudgetPeriodStatus) Enum() *BudgetPeriodStatus {
	p := new(BudgetPeriodStatus)
	*p = x
	return p
}

func (x BudgetPeriodStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BudgetPeriodStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_zbb_proto_enumTypes[0].Descriptor()
}

func (BudgetPeriodStatus) Type() protoreflect.EnumType {
	return &file_proto_accounting_zbb_proto_enumTypes[0]
}

func (x BudgetPeriodStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BudgetPeriodStatus.Descriptor instead.
func (BudgetPeriodStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{0}
}

// BudgetRequestStatus enum
type BudgetRequestStatus int32

const (
	BudgetRequestStatus_BUDGET_REQUEST_STATUS_UNSPECIFIED       BudgetRequestStatus = 0
	BudgetRequestStatus_BUDGET_REQUEST_STATUS_DRAFT             BudgetRequestStatus = 1
	BudgetRequestStatus_BUDGET_REQUEST_STATUS_SUBMITTED         BudgetRequestStatus = 2
	BudgetRequestStatus_BUDGET_REQUEST_STATUS_UNDER_REVIEW      BudgetRequestStatus = 3
	BudgetRequestStatus_BUDGET_REQUEST_STATUS_APPROVED          BudgetRequestStatus = 4
	BudgetRequestStatus_BUDGET_REQUEST_STATUS_REJECTED          BudgetRequestStatus = 5
	BudgetRequestStatus_BUDGET_REQUEST_STATUS_REVISION_REQUIRED BudgetRequestStatus = 6
)

// Enum value maps for BudgetRequestStatus.
var (
	BudgetRequestStatus_name = map[int32]string{
		0: "BUDGET_REQUEST_STATUS_UNSPECIFIED",
		1: "BUDGET_REQUEST_STATUS_DRAFT",
		2: "BUDGET_REQUEST_STATUS_SUBMITTED",
		3: "BUDGET_REQUEST_STATUS_UNDER_REVIEW",
		4: "BUDGET_REQUEST_STATUS_APPROVED",
		5: "BUDGET_REQUEST_STATUS_REJECTED",
		6: "BUDGET_REQUEST_STATUS_REVISION_REQUIRED",
	}
	BudgetRequestStatus_value = map[string]int32{
		"BUDGET_REQUEST_STATUS_UNSPECIFIED":       0,
		"BUDGET_REQUEST_STATUS_DRAFT":             1,
		"BUDGET_REQUEST_STATUS_SUBMITTED":         2,
		"BUDGET_REQUEST_STATUS_UNDER_REVIEW":      3,
		"BUDGET_REQUEST_STATUS_APPROVED":          4,
		"BUDGET_REQUEST_STATUS_REJECTED":          5,
		"BUDGET_REQUEST_STATUS_REVISION_REQUIRED": 6,
	}
)

func (x BudgetRequestStatus) Enum() *BudgetRequestStatus {
	p := new(BudgetRequestStatus)
	*p = x
	return p
}

func (x BudgetRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BudgetRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_zbb_proto_enumTypes[1].Descriptor()
}

func (BudgetRequestStatus) Type() protoreflect.EnumType {
	return &file_proto_accounting_zbb_proto_enumTypes[1]
}

func (x BudgetRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BudgetRequestStatus.Descriptor instead.
func (BudgetRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{1}
}

// Priority enum
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_CRITICAL    Priority = 1
	Priority_PRIORITY_HIGH        Priority = 2
	Priority_PRIORITY_MEDIUM      Priority = 3
	Priority_PRIORITY_LOW         Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_CRITICAL",
		2: "PRIORITY_HIGH",
		3: "PRIORITY_MEDIUM",
		4: "PRIORITY_LOW",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_CRITICAL":    1,
		"PRIORITY_HIGH":        2,
		"PRIORITY_MEDIUM":      3,
		"PRIORITY_LOW":         4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_zbb_proto_enumTypes[2].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_proto_accounting_zbb_proto_enumTypes[2]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{2}
}

// JustificationCategory enum
type JustificationCategory int32

const (
	JustificationCategory_JUSTIFICATION_CATEGORY_UNSPECIFIED JustificationCategory = 0
	JustificationCategory_JUSTIFICATION_CATEGORY_OPERATIONAL JustificationCategory = 1
	JustificationCategory_JUSTIFICATION_CATEGORY_STRATEGIC   JustificationCategory = 2
	JustificationCategory_JUSTIFICATION_CATEGORY_COMPLIANCE  JustificationCategory = 3
	JustificationCategory_JUSTIFICATION_CATEGORY_GROWTH      JustificationCategory = 4
	JustificationCategory_JUSTIFICATION_CATEGORY_MAINTENANCE JustificationCategory = 5
)

// Enum value maps for JustificationCategory.
var (
	JustificationCategory_name = map[int32]string{
		0: "JUSTIFICATION_CATEGORY_UNSPECIFIED",
		1: "JUSTIFICATION_CATEGORY_OPERATIONAL",
		2: "JUSTIFICATION_CATEGORY_STRATEGIC",
		3: "JUSTIFICATION_CATEGORY_COMPLIANCE",
		4: "JUSTIFICATION_CATEGORY_GROWTH",
		5: "JUSTIFICATION_CATEGORY_MAINTENANCE",
	}
	JustificationCategory_value = map[string]int32{
		"JUSTIFICATION_CATEGORY_UNSPECIFIED": 0,
		"JUSTIFICATION_CATEGORY_OPERATIONAL": 1,
		"JUSTIFICATION_CATEGORY_STRATEGIC":   2,
		"JUSTIFICATION_CATEGORY_COMPLIANCE":  3,
		"JUSTIFICATION_CATEGORY_GROWTH":      4,
		"JUSTIFICATION_CATEGORY_MAINTENANCE": 5,
	}
)

func (x JustificationCategory) Enum() *JustificationCategory {
	p := new(JustificationCategory)
	*p = x
	return p
}

func (x JustificationCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JustificationCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_zbb_proto_enumTypes[3].Descriptor()
}

func (JustificationCategory) Type() protoreflect.EnumType {
	return &file_proto_accounting_zbb_proto_enumTypes[3]
}

func (x JustificationCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JustificationCategory.Descriptor instead.
func (JustificationCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{3}
}

// ApprovalStatus enum
type ApprovalStatus int32

const (
	ApprovalStatus_APPROVAL_STATUS_UNSPECIFIED ApprovalStatus = 0
	ApprovalStatus_APPROVAL_STATUS_PENDING     ApprovalStatus = 1
	ApprovalStatus_APPROVAL_STATUS_APPROVED    ApprovalStatus = 2
	ApprovalStatus_APPROVAL_STATUS_REJECTED    ApprovalStatus = 3
	ApprovalStatus_APPROVAL_STATUS_SKIPPED     ApprovalStatus = 4
)

// Enum value maps for ApprovalStatus.
var (
	ApprovalStatus_name = map[int32]string{
		0: "APPROVAL_STATUS_UNSPECIFIED",
		1: "APPROVAL_STATUS_PENDING",
		2: "APPROVAL_STATUS_APPROVED",
		3: "APPROVAL_STATUS_REJECTED",
		4: "APPROVAL_STATUS_SKIPPED",
	}
	ApprovalStatus_value = map[string]int32{
		"APPROVAL_STATUS_UNSPECIFIED": 0,
		"APPROVAL_STATUS_PENDING":     1,
		"APPROVAL_STATUS_APPROVED":    2,
		"APPROVAL_STATUS_REJECTED":    3,
		"APPROVAL_STATUS_SKIPPED":     4,
	}
)

func (x ApprovalStatus) Enum() *ApprovalStatus {
	p := new(ApprovalStatus)
	*p = x
	return p
}

func (x ApprovalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounting_zbb_proto_enumTypes[4].Descriptor()
}

func (ApprovalStatus) Type() protoreflect.EnumType {
	return &file_proto_accounting_zbb_proto_enumTypes[4]
}

func (x ApprovalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalStatus.Descriptor instead.
func (ApprovalStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{4}
}

// BudgetPeriod
type BudgetPeriod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status        BudgetPeriodStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=accounting.BudgetPeriodStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetPeriod) Reset() {
	*x = BudgetPeriod{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetPeriod) ProtoMessage() {}

func (x *BudgetPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetPeriod.ProtoReflect.Descriptor instead.
func (*BudgetPeriod) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{0}
}

func (x *BudgetPeriod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BudgetPeriod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BudgetPeriod) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *BudgetPeriod) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *BudgetPeriod) GetStatus() BudgetPeriodStatus {
	if x != nil {
		return x.Status
	}
	return BudgetPeriodStatus_BUDGET_PERIOD_STATUS_UNSPECIFIED
}

func (x *BudgetPeriod) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BudgetPeriod) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

// BudgetLineItem
type BudgetLineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName   string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Amount        *Amount                `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Priority      Priority               `protobuf:"varint,6,opt,name=priority,proto3,enum=accounting.Priority" json:"priority,omitempty"`
	Recurring     bool                   `protobuf:"varint,7,opt,name=recurring,proto3" json:"recurring,omitempty"`
	Frequency     string                 `protobuf:"bytes,8,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Vendor        string                 `protobuf:"bytes,9,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Dimensions    []*Dimension           `protobuf:"bytes,10,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	Justification string                 `protobuf:"bytes,11,opt,name=justification,proto3" json:"justification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetLineItem) Reset() {
	*x = BudgetLineItem{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetLineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetLineItem) ProtoMessage() {}

func (x *BudgetLineItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetLineItem.ProtoReflect.Descriptor instead.
func (*BudgetLineItem) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{1}
}

func (x *BudgetLineItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BudgetLineItem) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BudgetLineItem) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *BudgetLineItem) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *BudgetLineItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BudgetLineItem) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *BudgetLineItem) GetRecurring() bool {
	if x != nil {
		return x.Recurring
	}
	return false
}

func (x *BudgetLineItem) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *BudgetLineItem) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *BudgetLineItem) GetDimensions() []*Dimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *BudgetLineItem) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

// Alternative
type Alternative struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Cost          *Amount                `protobuf:"bytes,2,opt,name=cost,proto3" json:"cost,omitempty"`
	Pros          []string               `protobuf:"bytes,3,rep,name=pros,proto3" json:"pros,omitempty"`
	Cons          []string               `protobuf:"bytes,4,rep,name=cons,proto3" json:"cons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alternative) Reset() {
	*x = Alternative{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alternative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alternative) ProtoMessage() {}

func (x *Alternative) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alternative.ProtoReflect.Descriptor instead.
func (*Alternative) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{2}
}

func (x *Alternative) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alternative) GetCost() *Amount {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Alternative) GetPros() []string {
	if x != nil {
		return x.Pros
	}
	return nil
}

func (x *Alternative) GetCons() []string {
	if x != nil {
		return x.Cons
	}
	return nil
}

// JustificationMetric
type JustificationMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Timeframe     string                 `protobuf:"bytes,4,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Measurement   string                 `protobuf:"bytes,5,opt,name=measurement,proto3" json:"measurement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JustificationMetric) Reset() {
	*x = JustificationMetric{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JustificationMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JustificationMetric) ProtoMessage() {}

func (x *JustificationMetric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JustificationMetric.ProtoReflect.Descriptor instead.
func (*JustificationMetric) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{3}
}

func (x *JustificationMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JustificationMetric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *JustificationMetric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *JustificationMetric) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *JustificationMetric) GetMeasurement() string {
	if x != nil {
		return x.Measurement
	}
	return ""
}

// Justification
type Justification struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category         JustificationCategory  `protobuf:"varint,2,opt,name=category,proto3,enum=accounting.JustificationCategory" json:"category,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	BusinessCase     string                 `protobuf:"bytes,5,opt,name=business_case,json=businessCase,proto3" json:"business_case,omitempty"`
	ExpectedOutcome  string                 `protobuf:"bytes,6,opt,name=expected_outcome,json=expectedOutcome,proto3" json:"expected_outcome,omitempty"`
	RiskOfNotFunding string                 `protobuf:"bytes,7,opt,name=risk_of_not_funding,json=riskOfNotFunding,proto3" json:"risk_of_not_funding,omitempty"`
	Alternatives     []*Alternative         `protobuf:"bytes,8,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	Metrics          []*JustificationMetric `protobuf:"bytes,9,rep,name=metrics,proto3" json:"metrics,omitempty"`
	SupportingDocs   []string               `protobuf:"bytes,10,rep,name=supporting_docs,json=supportingDocs,proto3" json:"supporting_docs,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy        string                 `protobuf:"bytes,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Justification) Reset() {
	*x = Justification{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Justification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Justification) ProtoMessage() {}

func (x *Justification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Justification.ProtoReflect.Descriptor instead.
func (*Justification) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{4}
}

func (x *Justification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Justification) GetCategory() JustificationCategory {
	if x != nil {
		return x.Category
	}
	return JustificationCategory_JUSTIFICATION_CATEGORY_UNSPECIFIED
}

func (x *Justification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Justification) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Justification) GetBusinessCase() string {
	if x != nil {
		return x.BusinessCase
	}
	return ""
}

func (x *Justification) GetExpectedOutcome() string {
	if x != nil {
		return x.ExpectedOutcome
	}
	return ""
}

func (x *Justification) GetRiskOfNotFunding() string {
	if x != nil {
		return x.RiskOfNotFunding
	}
	return ""
}

func (x *Justification) GetAlternatives() []*Alternative {
	if x != nil {
		return x.Alternatives
	}
	return nil
}

func (x *Justification) GetMetrics() []*JustificationMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Justification) GetSupportingDocs() []string {
	if x != nil {
		return x.SupportingDocs
	}
	return nil
}

func (x *Justification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Justification) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

// BudgetRequest
type BudgetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PeriodId       string                 `protobuf:"bytes,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	RequestorId    string                 `protobuf:"bytes,3,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"`
	DepartmentId   string                 `protobuf:"bytes,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	TotalAmount    *Amount                `protobuf:"bytes,7,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status         BudgetRequestStatus    `protobuf:"varint,8,opt,name=status,proto3,enum=accounting.BudgetRequestStatus" json:"status,omitempty"`
	LineItems      []*BudgetLineItem      `protobuf:"bytes,9,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	Justifications []*Justification       `protobuf:"bytes,10,rep,name=justifications,proto3" json:"justifications,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SubmittedAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	ApprovedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	ApprovedBy     string                 `protobuf:"bytes,15,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BudgetRequest) Reset() {
	*x = BudgetRequest{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetRequest) ProtoMessage() {}

func (x *BudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetRequest.ProtoReflect.Descriptor instead.
func (*BudgetRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{5}
}

func (x *BudgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BudgetRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *BudgetRequest) GetRequestorId() string {
	if x != nil {
		return x.RequestorId
	}
	return ""
}

func (x *BudgetRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *BudgetRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BudgetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BudgetRequest) GetTotalAmount() *Amount {
	if x != nil {
		return x.TotalAmount
	}
	return nil
}

func (x *BudgetRequest) GetStatus() BudgetRequestStatus {
	if x != nil {
		return x.Status
	}
	return BudgetRequestStatus_BUDGET_REQUEST_STATUS_UNSPECIFIED
}

func (x *BudgetRequest) GetLineItems() []*BudgetLineItem {
	if x != nil {
		return x.LineItems
	}
	return nil
}

func (x *BudgetRequest) GetJustifications() []*Justification {
	if x != nil {
		return x.Justifications
	}
	return nil
}

func (x *BudgetRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BudgetRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BudgetRequest) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *BudgetRequest) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *BudgetRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

// BudgetApproval
type BudgetApproval struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId      string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApproverId     string                 `protobuf:"bytes,3,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	ApproverLevel  int32                  `protobuf:"varint,4,opt,name=approver_level,json=approverLevel,proto3" json:"approver_level,omitempty"`
	Status         ApprovalStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=accounting.ApprovalStatus" json:"status,omitempty"`
	ApprovedAmount *Amount                `protobuf:"bytes,6,opt,name=approved_amount,json=approvedAmount,proto3" json:"approved_amount,omitempty"`
	Comments       string                 `protobuf:"bytes,7,opt,name=comments,proto3" json:"comments,omitempty"`
	ApprovedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BudgetApproval) Reset() {
	*x = BudgetApproval{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetApproval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetApproval) ProtoMessage() {}

func (x *BudgetApproval) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetApproval.ProtoReflect.Descriptor instead.
func (*BudgetApproval) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{6}
}

func (x *BudgetApproval) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BudgetApproval) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BudgetApproval) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *BudgetApproval) GetApproverLevel() int32 {
	if x != nil {
		return x.ApproverLevel
	}
	return 0
}

func (x *BudgetApproval) GetStatus() ApprovalStatus {
	if x != nil {
		return x.Status
	}
	return ApprovalStatus_APPROVAL_STATUS_UNSPECIFIED
}

func (x *BudgetApproval) GetApprovedAmount() *Amount {
	if x != nil {
		return x.ApprovedAmount
	}
	return nil
}

func (x *BudgetApproval) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *BudgetApproval) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *BudgetApproval) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// BudgetAllocation
type BudgetAllocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PeriodId      string                 `protobuf:"bytes,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        *Amount                `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	SpentAmount   *Amount                `protobuf:"bytes,7,opt,name=spent_amount,json=spentAmount,proto3" json:"spent_amount,omitempty"`
	Remaining     *Amount                `protobuf:"bytes,8,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Dimensions    []*Dimension           `protobuf:"bytes,10,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetAllocation) Reset() {
	*x = BudgetAllocation{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetAllocation) ProtoMessage() {}

func (x *BudgetAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetAllocation.ProtoReflect.Descriptor instead.
func (*BudgetAllocation) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{7}
}

func (x *BudgetAllocation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BudgetAllocation) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *BudgetAllocation) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BudgetAllocation) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *BudgetAllocation) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BudgetAllocation) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *BudgetAllocation) GetSpentAmount() *Amount {
	if x != nil {
		return x.SpentAmount
	}
	return nil
}

func (x *BudgetAllocation) GetRemaining() *Amount {
	if x != nil {
		return x.Remaining
	}
	return nil
}

func (x *BudgetAllocation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BudgetAllocation) GetDimensions() []*Dimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *BudgetAllocation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BudgetAllocation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// BudgetTracking
type BudgetTracking struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AllocationId    string                 `protobuf:"bytes,1,opt,name=allocation_id,json=allocationId,proto3" json:"allocation_id,omitempty"`
	TransactionId   string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount          *Amount                `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TrackedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=tracked_at,json=trackedAt,proto3" json:"tracked_at,omitempty"`
	RemainingBudget *Amount                `protobuf:"bytes,6,opt,name=remaining_budget,json=remainingBudget,proto3" json:"remaining_budget,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BudgetTracking) Reset() {
	*x = BudgetTracking{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetTracking) ProtoMessage() {}

func (x *BudgetTracking) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetTracking.ProtoReflect.Descriptor instead.
func (*BudgetTracking) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{8}
}

func (x *BudgetTracking) GetAllocationId() string {
	if x != nil {
		return x.AllocationId
	}
	return ""
}

func (x *BudgetTracking) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BudgetTracking) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *BudgetTracking) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BudgetTracking) GetTrackedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TrackedAt
	}
	return nil
}

func (x *BudgetTracking) GetRemainingBudget() *Amount {
	if x != nil {
		return x.RemainingBudget
	}
	return nil
}

// BudgetVarianceItem
type BudgetVarianceItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	BudgetAmount    *Amount                `protobuf:"bytes,3,opt,name=budget_amount,json=budgetAmount,proto3" json:"budget_amount,omitempty"`
	SpentAmount     *Amount                `protobuf:"bytes,4,opt,name=spent_amount,json=spentAmount,proto3" json:"spent_amount,omitempty"`
	Variance        *Amount                `protobuf:"bytes,5,opt,name=variance,proto3" json:"variance,omitempty"`
	VariancePercent float64                `protobuf:"fixed64,6,opt,name=variance_percent,json=variancePercent,proto3" json:"variance_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BudgetVarianceItem) Reset() {
	*x = BudgetVarianceItem{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetVarianceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetVarianceItem) ProtoMessage() {}

func (x *BudgetVarianceItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetVarianceItem.ProtoReflect.Descriptor instead.
func (*BudgetVarianceItem) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{9}
}

func (x *BudgetVarianceItem) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BudgetVarianceItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BudgetVarianceItem) GetBudgetAmount() *Amount {
	if x != nil {
		return x.BudgetAmount
	}
	return nil
}

func (x *BudgetVarianceItem) GetSpentAmount() *Amount {
	if x != nil {
		return x.SpentAmount
	}
	return nil
}

func (x *BudgetVarianceItem) GetVariance() *Amount {
	if x != nil {
		return x.Variance
	}
	return nil
}

func (x *BudgetVarianceItem) GetVariancePercent() float64 {
	if x != nil {
		return x.VariancePercent
	}
	return 0
}

// BudgetVarianceReport
type BudgetVarianceReport struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PeriodId             string                 `protobuf:"bytes,1,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	DepartmentId         string                 `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	TotalBudget          *Amount                `protobuf:"bytes,3,opt,name=total_budget,json=totalBudget,proto3" json:"total_budget,omitempty"`
	TotalSpent           *Amount                `protobuf:"bytes,4,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
	TotalVariance        *Amount                `protobuf:"bytes,5,opt,name=total_variance,json=totalVariance,proto3" json:"total_variance,omitempty"`
	TotalVariancePercent float64                `protobuf:"fixed64,6,opt,name=total_variance_percent,json=totalVariancePercent,proto3" json:"total_variance_percent,omitempty"`
	Items                []*BudgetVarianceItem  `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	GeneratedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BudgetVarianceReport) Reset() {
	*x = BudgetVarianceReport{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetVarianceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetVarianceReport) ProtoMessage() {}

func (x *BudgetVarianceReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetVarianceReport.ProtoReflect.Descriptor instead.
func (*BudgetVarianceReport) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{10}
}

func (x *BudgetVarianceReport) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *BudgetVarianceReport) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *BudgetVarianceReport) GetTotalBudget() *Amount {
	if x != nil {
		return x.TotalBudget
	}
	return nil
}

func (x *BudgetVarianceReport) GetTotalSpent() *Amount {
	if x != nil {
		return x.TotalSpent
	}
	return nil
}

func (x *BudgetVarianceReport) GetTotalVariance() *Amount {
	if x != nil {
		return x.TotalVariance
	}
	return nil
}

func (x *BudgetVarianceReport) GetTotalVariancePercent() float64 {
	if x != nil {
		return x.TotalVariancePercent
	}
	return 0
}

func (x *BudgetVarianceReport) GetItems() []*BudgetVarianceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BudgetVarianceReport) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

// BudgetRequestSummary
type BudgetRequestSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title              string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status             BudgetRequestStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=accounting.BudgetRequestStatus" json:"status,omitempty"`
	RequestedAmount    *Amount                `protobuf:"bytes,4,opt,name=requested_amount,json=requestedAmount,proto3" json:"requested_amount,omitempty"`
	ApprovedAmount     *Amount                `protobuf:"bytes,5,opt,name=approved_amount,json=approvedAmount,proto3" json:"approved_amount,omitempty"`
	LineItemCount      int32                  `protobuf:"varint,6,opt,name=line_item_count,json=lineItemCount,proto3" json:"line_item_count,omitempty"`
	JustificationCount int32                  `protobuf:"varint,7,opt,name=justification_count,json=justificationCount,proto3" json:"justification_count,omitempty"`
	SubmittedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	ApprovedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BudgetRequestSummary) Reset() {
	*x = BudgetRequestSummary{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetRequestSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetRequestSummary) ProtoMessage() {}

func (x *BudgetRequestSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetRequestSummary.ProtoReflect.Descriptor instead.
func (*BudgetRequestSummary) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{11}
}

func (x *BudgetRequestSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BudgetRequestSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BudgetRequestSummary) GetStatus() BudgetRequestStatus {
	if x != nil {
		return x.Status
	}
	return BudgetRequestStatus_BUDGET_REQUEST_STATUS_UNSPECIFIED
}

func (x *BudgetRequestSummary) GetRequestedAmount() *Amount {
	if x != nil {
		return x.RequestedAmount
	}
	return nil
}

func (x *BudgetRequestSummary) GetApprovedAmount() *Amount {
	if x != nil {
		return x.ApprovedAmount
	}
	return nil
}

func (x *BudgetRequestSummary) GetLineItemCount() int32 {
	if x != nil {
		return x.LineItemCount
	}
	return 0
}

func (x *BudgetRequestSummary) GetJustificationCount() int32 {
	if x != nil {
		return x.JustificationCount
	}
	return 0
}

func (x *BudgetRequestSummary) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *BudgetRequestSummary) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

// DepartmentBudgetSummary
type DepartmentBudgetSummary struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	PeriodId       string                  `protobuf:"bytes,1,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	DepartmentId   string                  `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	TotalRequested *Amount                 `protobuf:"bytes,3,opt,name=total_requested,json=totalRequested,proto3" json:"total_requested,omitempty"`
	TotalApproved  *Amount                 `protobuf:"bytes,4,opt,name=total_approved,json=totalApproved,proto3" json:"total_approved,omitempty"`
	StatusCounts   map[string]int32        `protobuf:"bytes,5,rep,name=status_counts,json=statusCounts,proto3" json:"status_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Requests       []*BudgetRequestSummary `protobuf:"bytes,6,rep,name=requests,proto3" json:"requests,omitempty"`
	GeneratedAt    *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DepartmentBudgetSummary) Reset() {
	*x = DepartmentBudgetSummary{}
	mi := &file_proto_accounting_zbb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentBudgetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentBudgetSummary) ProtoMessage() {}

func (x *DepartmentBudgetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounting_zbb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentBudgetSummary.ProtoReflect.Descriptor instead.
func (*DepartmentBudgetSummary) Descriptor() ([]byte, []int) {
	return file_proto_accounting_zbb_proto_rawDescGZIP(), []int{12}
}

func (x *DepartmentBudgetSummary) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *DepartmentBudgetSummary) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *DepartmentBudgetSummary) GetTotalRequested() *Amount {
	if x != nil {
		return x.TotalRequested
	}
	return nil
}

func (x *DepartmentBudgetSummary) GetTotalApproved() *Amount {
	if x != nil {
		return x.TotalApproved
	}
	return nil
}

func (x *DepartmentBudgetSummary) GetStatusCounts() map[string]int32 {
	if x != nil {
		return x.StatusCounts
	}
	return nil
}

func (x *DepartmentBudgetSummary) GetRequests() []*BudgetRequestSummary {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *DepartmentBudgetSummary) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

var File_proto_accounting_zbb_proto protoreflect.FileDescriptor

const file_proto_accounting_zbb_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/accounting/zbb.proto\x12\n" +
	"accounting\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!proto/accounting/accounting.proto\"\xb6\x02\n" +
	"\fBudgetPeriod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x126\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1e.accounting.BudgetPeriodStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\"\x93\x03\n" +
	"\x0eBudgetLineItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12*\n" +
	"\x06amount\x18\x04 \x01(\v2\x12.accounting.AmountR\x06amount\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x120\n" +
	"\bpriority\x18\x06 \x01(\x0e2\x14.accounting.PriorityR\bpriority\x12\x1c\n" +
	"\trecurring\x18\a \x01(\bR\trecurring\x12\x1c\n" +
	"\tfrequency\x18\b \x01(\tR\tfrequency\x12\x16\n" +
	"\x06vendor\x18\t \x01(\tR\x06vendor\x125\n" +
	"\n" +
	"dimensions\x18\n" +
	" \x03(\v2\x15.accounting.DimensionR\n" +
	"dimensions\x12$\n" +
	"\rjustification\x18\v \x01(\tR\rjustification\"\x7f\n" +
	"\vAlternative\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12&\n" +
	"\x04cost\x18\x02 \x01(\v2\x12.accounting.AmountR\x04cost\x12\x12\n" +
	"\x04pros\x18\x03 \x03(\tR\x04pros\x12\x12\n" +
	"\x04cons\x18\x04 \x03(\tR\x04cons\"\x93\x01\n" +
	"\x13JustificationMetric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x1c\n" +
	"\ttimeframe\x18\x04 \x01(\tR\ttimeframe\x12 \n" +
	"\vmeasurement\x18\x05 \x01(\tR\vmeasurement\"\x90\x04\n" +
	"\rJustification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\bcategory\x18\x02 \x01(\x0e2!.accounting.JustificationCategoryR\bcategory\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rbusiness_case\x18\x05 \x01(\tR\fbusinessCase\x12)\n" +
	"\x10expected_outcome\x18\x06 \x01(\tR\x0fexpectedOutcome\x12-\n" +
	"\x13risk_of_not_funding\x18\a \x01(\tR\x10riskOfNotFunding\x12;\n" +
	"\falternatives\x18\b \x03(\v2\x17.accounting.AlternativeR\falternatives\x129\n" +
	"\ametrics\x18\t \x03(\v2\x1f.accounting.JustificationMetricR\ametrics\x12'\n" +
	"\x0fsupporting_docs\x18\n" +
	" \x03(\tR\x0esupportingDocs\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\f \x01(\tR\tcreatedBy\"\xbd\x05\n" +
	"\rBudgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tperiod_id\x18\x02 \x01(\tR\bperiodId\x12!\n" +
	"\frequestor_id\x18\x03 \x01(\tR\vrequestorId\x12#\n" +
	"\rdepartment_id\x18\x04 \x01(\tR\fdepartmentId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x125\n" +
	"\ftotal_amount\x18\a \x01(\v2\x12.accounting.AmountR\vtotalAmount\x127\n" +
	"\x06status\x18\b \x01(\x0e2\x1f.accounting.BudgetRequestStatusR\x06status\x129\n" +
	"\n" +
	"line_items\x18\t \x03(\v2\x1a.accounting.BudgetLineItemR\tlineItems\x12A\n" +
	"\x0ejustifications\x18\n" +
	" \x03(\v2\x19.accounting.JustificationR\x0ejustifications\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fsubmitted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x12;\n" +
	"\vapproved_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"approvedAt\x12\x1f\n" +
	"\vapproved_by\x18\x0f \x01(\tR\n" +
	"approvedBy\"\x8c\x03\n" +
	"\x0eBudgetApproval\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1f\n" +
	"\vapprover_id\x18\x03 \x01(\tR\n" +
	"approverId\x12%\n" +
	"\x0eapprover_level\x18\x04 \x01(\x05R\rapproverLevel\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.accounting.ApprovalStatusR\x06status\x12;\n" +
	"\x0fapproved_amount\x18\x06 \x01(\v2\x12.accounting.AmountR\x0eapprovedAmount\x12\x1a\n" +
	"\bcomments\x18\a \x01(\tR\bcomments\x12;\n" +
	"\vapproved_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"approvedAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x86\x04\n" +
	"\x10BudgetAllocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tperiod_id\x18\x02 \x01(\tR\bperiodId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12#\n" +
	"\rdepartment_id\x18\x04 \x01(\tR\fdepartmentId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x05 \x01(\tR\taccountId\x12*\n" +
	"\x06amount\x18\x06 \x01(\v2\x12.accounting.AmountR\x06amount\x125\n" +
	"\fspent_amount\x18\a \x01(\v2\x12.accounting.AmountR\vspentAmount\x120\n" +
	"\tremaining\x18\b \x01(\v2\x12.accounting.AmountR\tremaining\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x125\n" +
	"\n" +
	"dimensions\x18\n" +
	" \x03(\v2\x15.accounting.DimensionR\n" +
	"dimensions\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa4\x02\n" +
	"\x0eBudgetTracking\x12#\n" +
	"\rallocation_id\x18\x01 \x01(\tR\fallocationId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12*\n" +
	"\x06amount\x18\x03 \x01(\v2\x12.accounting.AmountR\x06amount\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"tracked_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttrackedAt\x12=\n" +
	"\x10remaining_budget\x18\x06 \x01(\v2\x12.accounting.AmountR\x0fremainingBudget\"\xa0\x02\n" +
	"\x12BudgetVarianceItem\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\rbudget_amount\x18\x03 \x01(\v2\x12.accounting.AmountR\fbudgetAmount\x125\n" +
	"\fspent_amount\x18\x04 \x01(\v2\x12.accounting.AmountR\vspentAmount\x12.\n" +
	"\bvariance\x18\x05 \x01(\v2\x12.accounting.AmountR\bvariance\x12)\n" +
	"\x10variance_percent\x18\x06 \x01(\x01R\x0fvariancePercent\"\xaa\x03\n" +
	"\x14BudgetVarianceReport\x12\x1b\n" +
	"\tperiod_id\x18\x01 \x01(\tR\bperiodId\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\tR\fdepartmentId\x125\n" +
	"\ftotal_budget\x18\x03 \x01(\v2\x12.accounting.AmountR\vtotalBudget\x123\n" +
	"\vtotal_spent\x18\x04 \x01(\v2\x12.accounting.AmountR\n" +
	"totalSpent\x129\n" +
	"\x0etotal_variance\x18\x05 \x01(\v2\x12.accounting.AmountR\rtotalVariance\x124\n" +
	"\x16total_variance_percent\x18\x06 \x01(\x01R\x14totalVariancePercent\x124\n" +
	"\x05items\x18\a \x03(\v2\x1e.accounting.BudgetVarianceItemR\x05items\x12=\n" +
	"\fgenerated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"\xc6\x03\n" +
	"\x14BudgetRequestSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1f.accounting.BudgetRequestStatusR\x06status\x12=\n" +
	"\x10requested_amount\x18\x04 \x01(\v2\x12.accounting.AmountR\x0frequestedAmount\x12;\n" +
	"\x0fapproved_amount\x18\x05 \x01(\v2\x12.accounting.AmountR\x0eapprovedAmount\x12&\n" +
	"\x0fline_item_count\x18\x06 \x01(\x05R\rlineItemCount\x12/\n" +
	"\x13justification_count\x18\a \x01(\x05R\x12justificationCount\x12=\n" +
	"\fsubmitted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x12;\n" +
	"\vapproved_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"approvedAt\"\xed\x03\n" +
	"\x17DepartmentBudgetSummary\x12\x1b\n" +
	"\tperiod_id\x18\x01 \x01(\tR\bperiodId\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\tR\fdepartmentId\x12;\n" +
	"\x0ftotal_requested\x18\x03 \x01(\v2\x12.accounting.AmountR\x0etotalRequested\x129\n" +
	"\x0etotal_approved\x18\x04 \x01(\v2\x12.accounting.AmountR\rtotalApproved\x12Z\n" +
	"\rstatus_counts\x18\x05 \x03(\v25.accounting.DepartmentBudgetSummary.StatusCountsEntryR\fstatusCounts\x12<\n" +
	"\brequests\x18\x06 \x03(\v2 .accounting.BudgetRequestSummaryR\brequests\x12=\n" +
	"\fgenerated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x1a?\n" +
	"\x11StatusCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01*\xe1\x01\n" +
	"\x12BudgetPeriodStatus\x12$\n" +
	" BUDGET_PERIOD_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aBUDGET_PERIOD_STATUS_DRAFT\x10\x01\x12\x1d\n" +
	"\x19BUDGET_PERIOD_STATUS_OPEN\x10\x02\x12\"\n" +
	"\x1eBUDGET_PERIOD_STATUS_SUBMITTED\x10\x03\x12!\n" +
	"\x1dBUDGET_PERIOD_STATUS_APPROVED\x10\x04\x12\x1f\n" +
	"\x1bBUDGET_PERIOD_STATUS_LOCKED\x10\x05*\x9f\x02\n" +
	"\x13BudgetRequestStatus\x12%\n" +
	"!BUDGET_REQUEST_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bBUDGET_REQUEST_STATUS_DRAFT\x10\x01\x12#\n" +
	"\x1fBUDGET_REQUEST_STATUS_SUBMITTED\x10\x02\x12&\n" +
	"\"BUDGET_REQUEST_STATUS_UNDER_REVIEW\x10\x03\x12\"\n" +
	"\x1eBUDGET_REQUEST_STATUS_APPROVED\x10\x04\x12\"\n" +
	"\x1eBUDGET_REQUEST_STATUS_REJECTED\x10\x05\x12+\n" +
	"'BUDGET_REQUEST_STATUS_REVISION_REQUIRED\x10\x06*u\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x01\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x02\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x03\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x04*\xff\x01\n" +
	"\x15JustificationCategory\x12&\n" +
	"\"JUSTIFICATION_CATEGORY_UNSPECIFIED\x10\x00\x12&\n" +
	"\"JUSTIFICATION_CATEGORY_OPERATIONAL\x10\x01\x12$\n" +
	" JUSTIFICATION_CATEGORY_STRATEGIC\x10\x02\x12%\n" +
	"!JUSTIFICATION_CATEGORY_COMPLIANCE\x10\x03\x12!\n" +
	"\x1dJUSTIFICATION_CATEGORY_GROWTH\x10\x04\x12&\n" +
	"\"JUSTIFICATION_CATEGORY_MAINTENANCE\x10\x05*\xa7\x01\n" +
	"\x0eApprovalStatus\x12\x1f\n" +
	"\x1bAPPROVAL_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17APPROVAL_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18APPROVAL_STATUS_APPROVED\x10\x02\x12\x1c\n" +
	"\x18APPROVAL_STATUS_REJECTED\x10\x03\x12\x1b\n" +
	"\x17APPROVAL_STATUS_SKIPPED\x10\x04B\x1dZ\x1baccounting/proto/accountingb\x06proto3"

var (
	file_proto_accounting_zbb_proto_rawDescOnce sync.Once
	file_proto_accounting_zbb_proto_rawDescData []byte
)

func file_proto_accounting_zbb_proto_rawDescGZIP() []byte {
	file_proto_accounting_zbb_proto_rawDescOnce.Do(func() {
		file_proto_accounting_zbb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accounting_zbb_proto_rawDesc), len(file_proto_accounting_zbb_proto_rawDesc)))
	})
	return file_proto_accounting_zbb_proto_rawDescData
}

var file_proto_accounting_zbb_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_accounting_zbb_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_accounting_zbb_proto_goTypes = []any{
	(BudgetPeriodStatus)(0),         // 0: accounting.BudgetPeriodStatus
	(BudgetRequestStatus)(0),        // 1: accounting.BudgetRequestStatus
	(Priority)(0),                   // 2: accounting.Priority
	(JustificationCategory)(0),      // 3: accounting.JustificationCategory
	(ApprovalStatus)(0),             // 4: accounting.ApprovalStatus
	(*BudgetPeriod)(nil),            // 5: accounting.BudgetPeriod
	(*BudgetLineItem)(nil),          // 6: accounting.BudgetLineItem
	(*Alternative)(nil),             // 7: accounting.Alternative
	(*JustificationMetric)(nil),     // 8: accounting.JustificationMetric
	(*Justification)(nil),           // 9: accounting.Justification
	(*BudgetRequest)(nil),           // 10: accounting.BudgetRequest
	(*BudgetApproval)(nil),          // 11: accounting.BudgetApproval
	(*BudgetAllocation)(nil),        // 12: accounting.BudgetAllocation
	(*BudgetTracking)(nil),          // 13: accounting.BudgetTracking
	(*BudgetVarianceItem)(nil),      // 14: accounting.BudgetVarianceItem
	(*BudgetVarianceReport)(nil),    // 15: accounting.BudgetVarianceReport
	(*BudgetRequestSummary)(nil),    // 16: accounting.BudgetRequestSummary
	(*DepartmentBudgetSummary)(nil), // 17: accounting.DepartmentBudgetSummary
	nil,                             // 18: accounting.DepartmentBudgetSummary.StatusCountsEntry
	(*timestamppb.Timestamp)(nil),   // 19: google.protobuf.Timestamp
	(*Amount)(nil),                  // 20: accounting.Amount
	(*Dimension)(nil),               // 21: accounting.Dimension
}
var file_proto_accounting_zbb_proto_depIdxs = []int32{
	19, // 0: accounting.BudgetPeriod.start_date:type_name -> google.protobuf.Timestamp
	19, // 1: accounting.BudgetPeriod.end_date:type_name -> google.protobuf.Timestamp
	0,  // 2: accounting.BudgetPeriod.status:type_name -> accounting.BudgetPeriodStatus
	19, // 3: accounting.BudgetPeriod.created_at:type_name -> google.protobuf.Timestamp
	20, // 4: accounting.BudgetLineItem.amount:type_name -> accounting.Amount
	2,  // 5: accounting.BudgetLineItem.priority:type_name -> accounting.Priority
	21, // 6: accounting.BudgetLineItem.dimensions:type_name -> accounting.Dimension
	20, // 7: accounting.Alternative.cost:type_name -> accounting.Amount
	3,  // 8: accounting.Justification.category:type_name -> accounting.JustificationCategory
	7,  // 9: accounting.Justification.alternatives:type_name -> accounting.Alternative
	8,  // 10: accounting.Justification.metrics:type_name -> accounting.JustificationMetric
	19, // 11: accounting.Justification.created_at:type_name -> google.protobuf.Timestamp
	20, // 12: accounting.BudgetRequest.total_amount:type_name -> accounting.Amount
	1,  // 13: accounting.BudgetRequest.status:type_name -> accounting.BudgetRequestStatus
	6,  // 14: accounting.BudgetRequest.line_items:type_name -> accounting.BudgetLineItem
	9,  // 15: accounting.BudgetRequest.justifications:type_name -> accounting.Justification
	19, // 16: accounting.BudgetRequest.created_at:type_name -> google.protobuf.Timestamp
	19, // 17: accounting.BudgetRequest.updated_at:type_name -> google.protobuf.Timestamp
	19, // 18: accounting.BudgetRequest.submitted_at:type_name -> google.protobuf.Timestamp
	19, // 19: accounting.BudgetRequest.approved_at:type_name -> google.protobuf.Timestamp
	4,  // 20: accounting.BudgetApproval.status:type_name -> accounting.ApprovalStatus
	20, // 21: accounting.BudgetApproval.approved_amount:type_name -> accounting.Amount
	19, // 22: accounting.BudgetApproval.approved_at:type_name -> google.protobuf.Timestamp
	19, // 23: accounting.BudgetApproval.created_at:type_name -> google.protobuf.Timestamp
	20, // 24: accounting.BudgetAllocation.amount:type_name -> accounting.Amount
	20, // 25: accounting.BudgetAllocation.spent_amount:type_name -> accounting.Amount
	20, // 26: accounting.BudgetAllocation.remaining:type_name -> accounting.Amount
	21, // 27: accounting.BudgetAllocation.dimensions:type_name -> accounting.Dimension
	19, // 28: accounting.BudgetAllocation.created_at:type_name -> google.protobuf.Timestamp
	19, // 29: accounting.BudgetAllocation.updated_at:type_name -> google.protobuf.Timestamp
	20, // 30: accounting.BudgetTracking.amount:type_name -> accounting.Amount
	19, // 31: accounting.BudgetTracking.tracked_at:type_name -> google.protobuf.Timestamp
	20, // 32: accounting.BudgetTracking.remaining_budget:type_name -> accounting.Amount
	20, // 33: accounting.BudgetVarianceItem.budget_amount:type_name -> accounting.Amount
	20, // 34: accounting.BudgetVarianceItem.spent_amount:type_name -> accounting.Amount
	20, // 35: accounting.BudgetVarianceItem.variance:type_name -> accounting.Amount
	20, // 36: accounting.BudgetVarianceReport.total_budget:type_name -> accounting.Amount
	20, // 37: accounting.BudgetVarianceReport.total_spent:type_name -> accounting.Amount
	20, // 38: accounting.BudgetVarianceReport.total_variance:type_name -> accounting.Amount
	14, // 39: accounting.BudgetVarianceReport.items:type_name -> accounting.BudgetVarianceItem
	19, // 40: accounting.BudgetVarianceReport.generated_at:type_name -> google.protobuf.Timestamp
	1,  // 41: accounting.BudgetRequestSummary.status:type_name -> accounting.BudgetRequestStatus
	20, // 42: accounting.BudgetRequestSummary.requested_amount:type_name -> accounting.Amount
	20, // 43: accounting.BudgetRequestSummary.approved_amount:type_name -> accounting.Amount
	19, // 44: accounting.BudgetRequestSummary.submitted_at:type_name -> google.protobuf.Timestamp
	19, // 45: accounting.BudgetRequestSummary.approved_at:type_name -> google.protobuf.Timestamp
	20, // 46: accounting.DepartmentBudgetSummary.total_requested:type_name -> accounting.Amount
	20, // 47: accounting.DepartmentBudgetSummary.total_approved:type_name -> accounting.Amount
	18, // 48: accounting.DepartmentBudgetSummary.status_counts:type_name -> accounting.DepartmentBudgetSummary.StatusCountsEntry
	16, // 49: accounting.DepartmentBudgetSummary.requests:type_name -> accounting.BudgetRequestSummary
	19, // 50: accounting.DepartmentBudgetSummary.generated_at:type_name -> google.protobuf.Timestamp
	51, // [51:51] is the sub-list for method output_type
	51, // [51:51] is the sub-list for method input_type
	51, // [51:51] is the sub-list for extension type_name
	51, // [51:51] is the sub-list for extension extendee
	0,  // [0:51] is the sub-list for field type_name
}

func init() { file_proto_accounting_zbb_proto_init() }
func file_proto_accounting_zbb_proto_init() {
	if File_proto_accounting_zbb_proto != nil {
		return
	}
	file_proto_accounting_accounting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accounting_zbb_proto_rawDesc), len(file_proto_accounting_zbb_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_accounting_zbb_proto_goTypes,
		DependencyIndexes: file_proto_accounting_zbb_proto_depIdxs,
		EnumInfos:         file_proto_accounting_zbb_proto_enumTypes,
		MessageInfos:      file_proto_accounting_zbb_proto_msgTypes,
	}.Build()
	File_proto_accounting_zbb_proto = out.File
	file_proto_accounting_zbb_proto_goTypes = nil
	file_proto_accounting_zbb_proto_depIdxs = nil
}
